### ISSUE TITLE
python -m jcvi.assembly.syntenypath bed not working

### ISSUE THREAD

**Issue by ishengtsai** [tanghaibao/jcvi#1]
Hi, 

I tried to create synteny map using allmaps but am sure what went wrong. Please have a look if you can notice an obvious problem please.

python -m jcvi.assembly.syntenypath bed Sp34.CEL_WS248.1x1.anchors
11:46:12 [base] Load file `Sp34.CEL_WS248.1x1.anchors`
11:46:12 [synteny] Assuming --qbed=Sp34.bed --sbed=CEL_WS248.bed
11:46:12 [base] Load file `Sp34.bed`
11:46:13 [base] Load file `CEL_WS248.bed`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.5.5-py2.7.egg/jcvi/assembly/syntenypath.py", line 422, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.5.5-py2.7.egg/jcvi/assembly/syntenypath.py", line 33, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.5.5-py2.7.egg/jcvi/apps/base.py", line 77, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.5.5-py2.7.egg/jcvi/assembly/syntenypath.py", line 84, in bed
    "{0}:{1}".format(get_number(sseqid), sstart)))
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.5.5-py2.7.egg/jcvi/formats/base.py", line 480, in get_number
    return cast(d)
ValueError: invalid literal for int() with base 10: ''

**Comment by tanghaibao** [comment]
Hi,

This happens when the seqid column (first column) in the BED file does not contain numbers. Can you give the first few lines of `CEL_WS248.bed`? The convention is to identify those sequence names like `chr12`, `scaffold_32` which contain a numeric number.

Haibao
