### ISSUE TITLE
'genetic_map' is not in list

### ISSUE THREAD

**Issue by xinshuaiqi** [tanghaibao/jcvi#103]
Hi Haibao, 
I am trying to run allmaps path but encountered an error. Would you please give me some suggestion?
More details are listed below: 

My cmd:
`python -m jcvi.assembly.allmaps path  combined.bed AACC.fasta -w weights.txt`

My **combined.bed** file is like this:
```
tig00000001AA   46638   46639   genetic_map-02:118.500000       tig00000001AA:46639
tig00000001AA   72333   72334   genetic_map-02:120.200000       tig00000001AA:72334
tig00000001AA   106858  106859  genetic_map-02:120.200000       tig00000001AA:106859
tig00000001AA   107504  107505  genetic_map-02:119.900000       tig00000001AA:107505
...
```

My fasta file:
```
>tig00000001AA
GTAATCCACGGCGAGGAAAGCG...
```
This is the **error code**:
```
^[[0;33m18:47:03 [base]^[[0m^[[0;35m Load file `combined.bed`^[[0m
^[[0;33m18:47:04 [allmaps]^[[0m^[[0;35m Map contains 14509 markers in 19 linkage groups.^[[0m
^[[0;33m18:47:04 [allmaps]^[[0m^[[0;35m Retained 13,029 of 14,509 (89.8%) clean markers.^[[0m
^[[0;33m18:47:04 [base]^[[0m^[[0;35m Load file `weights.txt`^[[0m
^[[0;33m18:47:04 [base]^[[0m^[[0;35m Imported 1 records from `weights.txt`.^[[0m
^[[0;33m18:47:04 [allmaps]^[[0m^[[0;35m Weight for `genetic_map` set to 1.^[[0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/biodocker/code/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/home/biodocker/code/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/home/biodocker/code/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/biodocker/code/jcvi/assembly/allmaps.py", line 1401, in path
    weights = Weights(weightsfile, mapnames)
  File "/home/biodocker/code/jcvi/assembly/allmaps.py", line 625, in __init__
    pivot_weight, o, pivot = self.get_pivot(mapnames)
  File "/home/biodocker/code/jcvi/assembly/allmaps.py", line 646, in get_pivot
    for m, w in self.items() if m in mapnames)
  File "/home/biodocker/code/jcvi/assembly/allmaps.py", line 646, in <genexpr>
    for m, w in self.items() if m in mapnames)
ValueError: 'genetic_map' is not in list
```

What does this error mean? What is the potential problem? My bed file? or my fasta seq? Thank you very much!

**Comment by tanghaibao** [comment]
@xinshuaiqi would you mind sharing your weight.txt file? Thanks

**Comment by xinshuaiqi** [comment]
weights.txt
```
genetic_map.csv 1
```
