### ISSUE TITLE
jcvi.assembly.allmaps path error

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#110]
Hi,

running `python -m jcvi.assembly.allmaps path` I got this error. How to fix it?

```
16:24:36 [base] Load file `433_bkp55bd.scaff.bed`
16:24:36 [allmaps] Map contains 10230 markers in 349 linkage groups.
16:24:36 [allmaps] Retained 10,228 of 10,230 (100.0%) clean markers.
16:24:36 [base] Load file `weights.txt`
16:24:36 [base] Imported 1 records from `weights.txt`.
16:24:36 [allmaps] Map weights: [('433_bkp55bd', 1)]
16:24:36 [allmaps] Linkage function: double-linkage
16:24:36 [allmaps] Partition LGs based on 433_bkp55bd
AMBIGUOUS flattened_line_54 {('433_bkp55bd-197',): 8, ('433_bkp55bd-50',): 8}
16:24:37 [base] Load file `/global/lv70640/c7701100/Projects/Talp_GenomeReassemblies/433_bkp55bd/a.final/a.lines.fasta.sizes`
16:24:38 [allmaps] Working on 433_bkp55bd-0 ...
Traceback (most recent call last):
  File "/opt/sw/x86_64/glibc-2.17/ivybridge-ep/python/2.7.11/gcc/5.3/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/sw/x86_64/glibc-2.17/ivybridge-ep/python/2.7.11/gcc/5.3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/home/lv70640/c7701100/software/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 1484, in path
    ngen=ngen, npop=npop, cpus=cpus, seed=seed)
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 142, in __init__
    self.prepare_linkage_groups()  # populate all data
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 249, in prepare_linkage_groups
    function=self.function, linkage=self.linkage)
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 92, in __init__
    self.oo[k] = get_rho(physical_to_cm)
  File "/home/lv70640/c7701100/software/jcvi/assembly/allmaps.py", line 791, in get_rho
    rho = spearmanr(x, y)
  File "/home/lv70640/c7701100/software/jcvi/algorithms/formula.py", line 112, in spearmanr
    return 1 - distancematrix((x, y), dist="s")[1][0]
  File "/home/lv70640/c7701100/.local/lib/python2.7/site-packages/Bio/Cluster/__init__.py", line 500, in distancematrix
    _cluster.distancematrix(data, mask, weight, transpose, dist, matrix)
RuntimeError: unexpected format.

```

**Comment by tanghaibao** [comment]
@francicco 
Someone reported a similar issue before. Might be worth checking the version for the Biopython.

https://github.com/tanghaibao/jcvi/issues/97

Haibao

**Comment by francicco** [comment]
Hi @tanghaibao,

I'm trying to reinstall jcvi using virtualenv and pip. But I got this.

```
(jcvi_env) [c7701100@l31 jcvi]$ pip install -e . 
Obtaining file:///home/lv70640/c7701100/software/jcvi
Requirement already satisfied: biopython in ./jcvi_env/lib/python2.7/site-packages (from jcvi==0.8.4) (1.72)
Requirement already satisfied: deap in ./jcvi_env/lib/python2.7/site-packages (from jcvi==0.8.4) (1.2.2)
Requirement already satisfied: matplotlib in ./jcvi_env/lib/python2.7/site-packages (from jcvi==0.8.4) (2.2.3)
Requirement already satisfied: networkx in ./jcvi_env/lib/python2.7/site-packages (from jcvi==0.8.4) (2.2)
Requirement already satisfied: numpy in ./jcvi_env/lib/python2.7/site-packages (from jcvi==0.8.4) (1.15.3)
Requirement already satisfied: python-dateutil>=2.1 in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (2.7.3)
Requirement already satisfied: cycler>=0.10 in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (0.10.0)
Requirement already satisfied: subprocess32 in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (3.5.3)
Requirement already satisfied: pytz in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (2018.6)
Requirement already satisfied: six>=1.10 in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (1.11.0)
Requirement already satisfied: backports.functools-lru-cache in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (1.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (2.2.2)
Requirement already satisfied: kiwisolver>=1.0.1 in ./jcvi_env/lib/python2.7/site-packages (from matplotlib->jcvi==0.8.4) (1.0.1)
Requirement already satisfied: decorator>=4.3.0 in ./jcvi_env/lib/python2.7/site-packages (from networkx->jcvi==0.8.4) (4.3.0)
Requirement already satisfied: setuptools in /home/lv70640/c7701100/software/DendroPy-3.12.0/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg (from kiwisolver>=1.0.1->matplotlib->jcvi==0.8.4) (0.6rc11)
Installing collected packages: jcvi
  Running setup.py develop for jcvi
    Complete output from command /home/lv70640/c7701100/software/jcvi/jcvi_env/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/lv70640/c7701100/software/jcvi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    Collecting cython
      Using cached https://files.pythonhosted.org/packages/a3/ac/a387b278df9e738601fcc5a674de5af196f50c4b07e5ba97464acb869b5d/Cython-0.29-cp27-cp27m-manylinux1_x86_64.whl
    Collecting numpy
      Using cached https://files.pythonhosted.org/packages/a0/c2/c19f2032dd57e5acddc9399dba39925f9d94cf877c11574e97a555ed84e9/numpy-1.15.3-cp27-cp27m-manylinux1_x86_64.whl
    Installing collected packages: cython, numpy
    Successfully installed cython-0.29 numpy-1.15.3
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/numpy-1.15.3.dist-info already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/numpy already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/pyximport already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/Cython-0.29.dist-info already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/Cython already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/cython.py already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/cython.pyc already exists. Specify --upgrade to force replacement.
    Target directory /home/lv70640/c7701100/software/jcvi/setup-requires/bin already exists. Specify --upgrade to force replacement.
    running develop
    running egg_info
    writing requirements to jcvi.egg-info/requires.txt
    writing jcvi.egg-info/PKG-INFO
    writing top-level names to jcvi.egg-info/top_level.txt
    writing dependency_links to jcvi.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'jcvi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'jcvi.egg-info/SOURCES.txt'
    running build_ext
    failed to import Cython: setup-requires/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
    error: Cython does not appear to be installed
    
    ----------------------------------------
Command "/home/lv70640/c7701100/software/jcvi/jcvi_env/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/lv70640/c7701100/software/jcvi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/lv70640/c7701100/software/jcvi/
```
