### ISSUE TITLE
KeyError: 'AT2G07633.1' ( python -m jcvi.compara.catalog tandem )

### ISSUE THREAD

**Issue by rsesteves** [tanghaibao/jcvi#123]
I have received an error trying to find tandem duplication using jcvi.

hemzy@DESKTOP-J3FNUQU:~/MCScan/ATHALY/ATHATHtandem$ python -m jcvi.compara.catalog tandem ATHp.blast ATH.cds ATH.bed -o ATH.tandem --strip_gene_name=SEP --evalue=0.00001
14:55:53 [base] Load file `ATH.cds`
14:55:54 [base] Load file `ATH.bed`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 841, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 837, in tandem
    evalue=opts.evalue, strip_name=sep, ofile=ofile, genefam=opts.genefam)
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 731, in tandem_main
    subject_len = sizes[b.subject]
KeyError: 'AT2G07633.1'

Would love to hear a solution. Thanks in advance!

**Comment by rsesteves** [comment]
The issue was that the blast file was supposed to be the output of the python -m jcvi.compara.catalog ortholog command. Use that, not a blast file from somewhere else!
