### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'kpsewhich'

### ISSUE THREAD

**Issue by SCQUchenyang** [tanghaibao/jcvi#124]
Hi，
Thanks for your work of jcvi. And when I use it to deal with grape and peach.But it tells:
18:01:32 [texmanager] family: monospace, font: Computer Modern Typewriter, info: ('cmtt', '')                                              [0/964]
18:01:32 [dviread] find_tex_file(pdftex.map): ['kpsewhich', u'pdftex.map']
Traceback (most recent call last):
  File "/wtmp/user170/software/miniconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/wtmp/user170/software/miniconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 841, in <module>
    main()
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 673, in ortholog
    dotplot_main(dargs)
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 357, in dotplot_main
    title=opts.title, stdpf=(not opts.nostdpf))
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 235, in dotplot
    sepcolor=sepcolor, minfont=minfont, stdpf=stdpf)
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 79, in plot_breaks_and_labels
    th = TextHandler(fig)
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/graphics/base.py", line 53, in __init__
    self.build_height_array(fig)
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/graphics/base.py", line 67, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/wtmp/user170/software/miniconda/lib/python2.7/site-packages/jcvi/graphics/base.py", line 59, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/UserHome/user170/.local/lib/python2.7/site-packages/matplotlib/textpath.py", line 450, in __init__
    usetex=usetex)
  File "/UserHome/user170/.local/lib/python2.7/site-packages/matplotlib/textpath.py", line 530, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/UserHome/user170/.local/lib/python2.7/site-packages/matplotlib/textpath.py", line 152, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/UserHome/user170/.local/lib/python2.7/site-packages/matplotlib/textpath.py", line 305, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/UserHome/user170/.local/lib/python2.7/site-packages/matplotlib/dviread.py", line 1045, in find_tex_file
    stderr=subprocess.PIPE)
  File "/UserHome/user170/.local/lib/python2.7/site-packages/subprocess32.py", line 614, in __init__
    restore_signals, start_new_session)
  File "/UserHome/user170/.local/lib/python2.7/site-packages/subprocess32.py", line 1393, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'kpsewhich'
user170@cu02# python -m jcvi.compara.catalog ortholog grape peach
##

The file  "grape.peach.anchors" is
GSVIVT01012028001       ppa011886m      515
GSVIVT01012027001       ppa026797m      297
GSVIVT01012026001       ppa006860m      609
GSVIVT01012023001       ppa000608m      2780
GSVIVT01012018001       ppa012865m      123
GSVIVT01012018001       ppa025457m      93
GSVIVT01012012001       ppa010496m      568
GSVIVT01012008001       ppa002064m      1180
GSVIVT01012006001       ppa012698m      362
....
So，how can I do with this problem？

**Comment by LiuYemao** [comment]
@SCQUchenyang 
On Debian-like OS:
`apt-get install -y texlive texlive-latex-extra texlive-latex-recommended`
On RedHat-list OS:
`yum install tetex-latex tetex-doc tetex-fonts texlive tex-live-latex`

**Comment by AlexWanghaoming** [comment]
> @SCQUchenyang
> On Debian-like OS:
> `apt-get install -y texlive texlive-latex-extra texlive-latex-recommended`
> On RedHat-list OS:
> `yum install tetex-latex tetex-doc tetex-fonts texlive tex-live-latex`

Hello, In MacOS, What should I do? I have installed MacTex, but it still reported an error.
Thanks
