### ISSUE TITLE
ValueError: Width and height specified must be non-negative

### ISSUE THREAD

**Issue by pdimens** [tanghaibao/jcvi#128]
Good morning,

I have run `allmaps` as recommended and all the necessary outputs are created (fasta, chain, etc.), however, allmaps fails at the plotting step, thereby producing no PDF plots. I have tried troubleshooting, but have so far not arrived at the root of the issue. Below is the log of the error. `jcvi` was installed via `conda`, and perhaps that is the partly to blame?

```
Traceback (most recent call last):
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1525, in path
    "--figsize={0}".format(opts.figsize)])
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1867, in plotall
    plot(xargs + [seqid])
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1807, in plot
    ax = fig.add_axes([xx, ystart, width, height])
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/matplotlib/figure.py", line 1149, in add_axes
    a = projection_class(self, rect, **kwargs)
  File "/home/pdimens/.conda/envs/python2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 490, in __init__
    raise ValueError('Width and height specified must be non-negative')
ValueError: Width and height specified must be non-negative
```

**Comment by tanghaibao** [comment]
Closing stale issue for now. This ran on Python 2.7 which we no longer support in recent versions of `jcvi`.
Please feel free to re-open if the problem is seen again on Python 3.
