### ISSUE TITLE
image reading

### ISSUE THREAD

**Issue by kjohnsen** [tanghaibao/jcvi#13]
"seeds" simply wouldn't work on this image. It looks like it's because it's in grayscale

```shell
kyle@bioinfkyle ~/corn/scan_test/scan/quarter $ python -m jcvi.graphics.grabseeds seeds ./img009.jpg 
/usr/local/lib/python2.7/dist-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
17:11:41 [grabseeds] Image `./img009.jpg` resized from 2472px:3414px to 1000px:1381px
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/graphics/grabseeds.py", line 586, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/graphics/grabseeds.py", line 114, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 81, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/graphics/grabseeds.py", line 438, in seeds
    oimg = load_image(resizefile)
  File "/usr/local/lib/python2.7/dist-packages/jcvi/graphics/grabseeds.py", line 399, in load_image
    h, w, c = img.shape
ValueError: need more than 2 values to unpack
```

![img009](https://cloud.githubusercontent.com/assets/19983357/16134945/e4a59a52-33e5-11e6-9d20-64218b92de5f.jpg)

**Comment by tanghaibao** [comment]
@kjohnsen It should work on non-grayscale images, perhaps ``skimage`` library changed so that it is no longer compatible - I'll hack over it this weekend. Thanks for reporting.

Haibao

**Comment by tanghaibao** [comment]
@kjohnsen you are right about grayscale, the program wasn't expecting grayscale. I have fixed this issue and this is the resulting detection - thanks
![image](https://cloud.githubusercontent.com/assets/106987/16180728/e67d81dc-3642-11e6-8b82-a889aeff786c.png)
