### ISSUE TITLE
dependency "deap" is missing from requirements.txt

### ISSUE THREAD

**Issue by ostueker** [tanghaibao/jcvi#133]
I just tried to install the jcvi package from a git clone (revision: d2e31a7) and 
noticed that it failed for a missing `deap` package:

```console
$  module load python/3.6
$  virtualenv --no-download ~/env_allmaps36
$  source ~/env_allmaps36/bin/activate
(env_allmaps36) $  git clone https://github.com/tanghaibao/jcvi.git
(env_allmaps36) $  cd jcvi
(env_allmaps36) $  pip install PyPDF2 deap
(env_allmaps36) $  pip install --no-index -r requirements.txt
(env_allmaps36) $  python setup.py install
(env_allmaps36) $ wget https://www.dropbox.com/s/b497bi2b594m6fp/ALLMAPS-testdata.zip
(env_allmaps36) $ unzip ALLMAPS-testdata.zip 
(env_allmaps36) $ cd ALLMAPS-testdata
(env_allmaps36) $ bash run.sh 
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stuekero/env_allmaps36/lib/python3.6/site-packages/jcvi-0.9.2-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 27, in <module>
    from jcvi.algorithms.ec import GA_setup, GA_run
  File "/home/stuekero/env_allmaps36/lib/python3.6/site-packages/jcvi-0.9.2-py3.6-linux-x86_64.egg/jcvi/algorithms/ec.py", line 17, in <module>
    from deap import base, creator, tools
ModuleNotFoundError: No module named 'deap'
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stuekero/env_allmaps36/lib/python3.6/site-packages/jcvi-0.9.2-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 27, in <module>
    from jcvi.algorithms.ec import GA_setup, GA_run
  File "/home/stuekero/env_allmaps36/lib/python3.6/site-packages/jcvi-0.9.2-py3.6-linux-x86_64.egg/jcvi/algorithms/ec.py", line 17, in <module>
    from deap import base, creator, tools
ModuleNotFoundError: No module named 'deap'
```

Installing deap via pip resolved this:

```console
(env_allmaps36) $ pip install deap
(env_allmaps36) $ bash run.sh 
```
But nevertheless this should probably added to `requirements.txt`.

**Comment by tanghaibao** [comment]
@ostueker thanks for reporting the issue
