### ISSUE TITLE
Karyotype plot fails for four genomes

### ISSUE THREAD

**Issue by johanneswerner** [tanghaibao/jcvi#134]
Plotting works for three bacterial genomes but it fails when I try to add the fourth genome. 

```bash
$ cat seqids 
pPBL-H6-1
pPBL-E5-1
pSRS16-1
pWDL1-1_final
```

```bash
$ cat layout 
# y, xstart, xend, rotation, color, label, va,  bed
 .7,     .3,    .9,       0,      , pPBL-H6-1, top, H6P1.bed 
 .5,     .3,    .9,       0,      , pPBL-E5-1, top, E5P1.bed 
 .3,     .3,    .9,       0,      , pSRS16-1,  top, SRS16P1.bed 
 .1,     .3,    .9,       0,      , pWDL1-1,   bottom, WDLP1.bed 
# edges
e, 0, 1, H6P1.E5P1.anchors.simple
e, 1, 2, E5P1.SRS16P1.anchors.simple
e, 2, 3, SRS16P1.WDLP1.anchors.simple
```

And when I try to run it, I get the following error message. 

```bash
$ python -m jcvi.graphics.karyotype seqids layout
18:01:41 [base] Load file `layout`
18:01:41 [base] Load file `H6P1.bed`
18:01:41 [base] Load file `E5P1.bed`
18:01:41 [base] Load file `SRS16P1.bed`
18:01:41 [base] Load file `WDLP1.bed`
Traceback (most recent call last):
  File "/data/miniconda3/envs/mcscan/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/miniconda3/envs/mcscan/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/miniconda3/envs/mcscan/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 350, in <module>
    main()
  File "/data/miniconda3/envs/mcscan/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 338, in main
    plot_circles=(not opts.nocircles))
  File "/data/miniconda3/envs/mcscan/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 317, in __init__
    plot_label=plot_label, plot_circles=plot_circles)
  File "/data/miniconda3/envs/mcscan/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 182, in draw
    si = make_circle_name(sid)
  File "/data/miniconda3/envs/mcscan/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 169, in make_circle_name
    si = str(int(si))
ValueError: invalid literal for int() with base 10: ''
```

Any idea what goes wrong here?

Without the fourth genome, it plots without problems. Thank you for your help.

**Comment by tanghaibao** [comment]
@johanneswerner 

My guess is that the problem may be that there are some issues with the seqids in the fourth genome. The plotter will look for any number in the seqid to show it in the karyotype graph in a circled label. For example, `chr1`, `scaffold_23`, `plasmid_m34` would all work, but `chrM` or `my_favorite_plasmid` wouldn't since the latter cases do not have any numbers in them.

Haibao

**Comment by johanneswerner** [comment]
You were right, the label may not end with letters. Thank you again.
