### ISSUE TITLE
agp mask error while splitting chimeric contigs

### ISSUE THREAD

**Issue by pdimens** [tanghaibao/jcvi#137]
Hello,
I am following the guide you provide on splitting chimeric contigs, however, when performing this step:
`python -m jcvi.formats.agp mask genome.fasta.agp breakpoints.genome.refined.bed --splitobject --splitsingle`
I get the following error and am having difficulty diagnosing it:
``` python
python2 -m jcvi.formats.agp mask joined.chr.fasta.agp breakpoints.joined.refined.bed --splitobject --splitsingle
11:32:26 [base] Load file `joined.chr.fasta.agp`
11:32:26 [base] Load file `breakpoints.joined.refined.bed`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/jcvi/formats/agp.py", line 1873, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/jcvi/formats/agp.py", line 752, in main
    p.dispatch(globals())
  File "/usr/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/lib/python2.7/site-packages/jcvi/formats/agp.py", line 1224, in mask
    i, a = simple_agp[component]
KeyError: 'tig00000216_pilon'
```
The only thing I can recognize is that the `KeyError` is the same contig that was flagged earlier:
```python
> python2 -m jcvi.assembly.patch refine breakpoints.bed joined.chr.gaps.bed
11:27:01 [patch] File breakpoints.bed contains 3 columns.
11:27:01 [base] intersectBed -wao -a breakpoints.bed -b joined.chr.gaps.bed >breakpoints.joine
d.bed
***** WARNING: File breakpoints.bed has inconsistent naming convention for record:
tig00000216_pilon       2335112 2370467
  
***** WARNING: File breakpoints.bed has inconsistent naming convention for record:
tig00000216_pilon       2335112 2370467
```
However, the .bed files were generated exclusively using the jcvi tools, which makes the contig naming convention error confusing as well. The contig creating this issue is the very first one of the `breakpoints.bed` file:
```
tig00000216_pilon	2335112	2370467
tig00000224_pilon	2428766	2428769
tig00000277_pilon	621435	671512
tig00000277_pilon	809253	833618
tig00000277_pilon	1795472	1795482
tig00000277_pilon	1958964	1964620
tig00000290_pilon	1011920	1092047
tig00000297_pilon	185976	221747
tig00000315_pilon	263757	304782
```

Do you have thoughts or suggestions on what might be going on?

**Comment by tanghaibao** [comment]
@pdimens 

The first error seems to indicate that `tig00000216_pilon` is not present in the AGP file `joined.chr.fasta.agp`. Can you check if it is the case?

The second error (or warning, rather) is a naming convention in BEDTOOLS which I don't think is related to the first error.

Haibao

**Comment by pdimens** [comment]
Here are the contents of `joined.chr.fasta.agp`:
```
chr1	1	29279729	1	W	chr1	1	29279729	?
chr2	1	23627687	1	W	chr2	1	23627687	?
chr3	1	23884413	1	W	chr3	1	23884413	?
chr4	1	21106642	1	W	chr4	1	21106642	?
chr5	1	23935848	1	W	chr5	1	23935848	?
chr6	1	20711886	1	W	chr6	1	20711886	?
chr7	1	1901607	1	W	chr7	1	1901607	?
chr8	1	24214632	1	W	chr8	1	24214632	?
chr9	1	23490904	1	W	chr9	1	23490904	?
chr10	1	22612954	1	W	chr10	1	22612954	?
chr11	1	19479129	1	W	chr11	1	19479129	?
chr12	1	20286111	1	W	chr12	1	20286111	?
chr13	1	20857055	1	W	chr13	1	20857055	?
chr14	1	19926118	1	W	chr14	1	19926118	?
chr15	1	19625045	1	W	chr15	1	19625045	?
chr16	1	16577785	1	W	chr16	1	16577785	?
chr17	1	17412439	1	W	chr17	1	17412439	?
chr18	1	17705065	1	W	chr18	1	17705065	?
chr19	1	18253842	1	W	chr19	1	18253842	?
chr20	1	14556091	1	W	chr20	1	14556091	?
chr21	1	19682699	1	W	chr21	1	19682699	?
chr22	1	12478483	1	W	chr22	1	12478483	?
chr23	1	18247810	1	W	chr23	1	18247810	?
chr24	1	9049010	1	W	chr24	1	9049010	?
```
