### ISSUE TITLE
IOError with running "python -m jcvi.compara.catalog ortholog grape peach"

### ISSUE THREAD

**Issue by starkiller-liuzhiming** [tanghaibao/jcvi#139]
python -m jcvi.compara.catalog ortholog grape peach
10:18:19 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
10:18:19 [base] Load file `grape.bed`
10:18:19 [base] Load file `peach.bed`
10:18:20 [dotplot] Showing a random subset of 10000 data points (total 14695) for clarity.
10:18:20 [dotplot] xsize=26346 ysize=28701
10:18:20 [texmanager] serif font is not compatible with usetex.
10:18:20 [texmanager] serif font is not compatible with usetex.
10:18:20 [texmanager] family: serif, font: Computer Modern Roman, info: ('cmr', '')
10:18:20 [texmanager] family: sans-serif, font: Helvetica, info: ('phv', '\\usepackage{helvet}')
10:18:20 [texmanager] cursive font is not compatible with usetex.
10:18:20 [texmanager] cursive font is not compatible with usetex.
10:18:20 [texmanager] family: cursive, font: Zapf Chancery, info: ('pzc', '\\usepackage{chancery}')
10:18:20 [texmanager] monospace font is not compatible with usetex.
10:18:20 [texmanager] monospace font is not compatible with usetex.
10:18:20 [texmanager] family: monospace, font: Computer Modern Typewriter, info: ('cmtt', '')
10:18:20 [dviread] find_tex_file(pdftex.map): ['kpsewhich', u'pdftex.map']
10:18:20 [dviread] find_tex_file result: 
Traceback (most recent call last):
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 841, in <module>
    main()
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 673, in ortholog
    dotplot_main(dargs)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 357, in dotplot_main
    title=opts.title, stdpf=(not opts.nostdpf))
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 235, in dotplot
    sepcolor=sepcolor, minfont=minfont, stdpf=stdpf)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 79, in plot_breaks_and_labels
    th = TextHandler(fig)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/graphics/base.py", line 53, in __init__
    self.build_height_array(fig)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/graphics/base.py", line 67, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/jcvi/graphics/base.py", line 59, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/matplotlib/textpath.py", line 450, in __init__
    usetex=usetex)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/matplotlib/textpath.py", line 530, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/matplotlib/textpath.py", line 152, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/matplotlib/textpath.py", line 305, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/public/home/liuzhiming/software/Python/Python-2.7/local/lib/python2.7/site-packages/matplotlib/dviread.py", line 842, in __init__
    with open(filename, 'rb') as file:
IOError: [Errno 2] No such file or directory: u''

I have this problem with  Python 2.7 and Python 2.7.15 , but I was still blocked by this problem.  How can I do to solve this problem?
Thanks!

**Comment by MichelMoser** [comment]
Got the same problem. Running on RedHat with python 2.7.5. 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]

Guess its some latex dependency error?

**Comment by sn-hoff** [comment]
Where there a solution to this problem? 
Have the same issue

**Comment by tanghaibao** [comment]
@sn-hoff 

Yes. This is likely a latex dependency issue.

Please take a look at [Get LaTeX](https://www.latex-project.org/get/) for various options for each major OS. For example, on Debian-like Linux OS you can often do:

sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
