### ISSUE TITLE
allmaps fails in the final phase

### ISSUE THREAD

**Issue by StefanoLonardi** [tanghaibao/jcvi#14]
I am trying to anchor a draft assembly composed of 795 contigs to a genetic map with 36,828 markers in 11 linkage groups.

**ALLMAPS** works fine solving the optimization problem for each chromosome, then it fails at the end with the following error message.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1684, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 820, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 81, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1331, in path
    build([inputbed, fastafile])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1451, in build
    fromagp([combined_agp, scaffolds, combined_fasta])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/formats/chain.py", line 153, in fromagp
    tSize = componentsizes[tName]
KeyError: 'tig00000085'
```
(the full log is attached)
[log.txt](https://github.com/tanghaibao/jcvi/files/328726/log.txt)

I want to note that tig00000085 exists in the original scaffold file  `quiver62fast.fasta`, but it seems that **allmaps** overwrites the `quiver62fast.fasta` in this line:
```
11:44:56 [base] cat quiver62fast.chr.fasta quiver62fast.unplaced.fasta >quiver62fast.fasta
```
and in that new file `quiver62fast.fasta` tig00000085 does not exist anymore . Would that explain the KeyError? Why is **allmaps** overwriting the input files? Any advice on how to get rid of the error?

**Comment by tanghaibao** [comment]
@StefanoLonardi you are probably right about this. It shouldn't overwrite the original scaffolds. Is this a long process? Can you rename `quiver62fast.bed` to something like `Map.bed` and re-run the command?

**Comment by StefanoLonardi** [comment]
You are right! Renaming the name of the bedfile to something else did the trick! Thanks so much.
