### ISSUE TITLE
lastal error when running jcvi.compara.catalog on example data

### ISSUE THREAD

**Issue by floutt** [tanghaibao/jcvi#142]
Hello!

So, recently I have been trying to run jcvi.compara.catalog on the example dataset found [here](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version\)), but have been running into some issues. The first thing that I noticed was that, unlike in the tutorial, I was getting 0 BLAST hits and an interesting error message from `lastal`, a dependency of the program.

Whenever I'd run the data on the peach and grape data (as well as others as well) I'd get multiple `lastal: bad option value: -f 2` errors from lastal and then get the following errors in the jcvi program proper:
```
15:31:06 [base] File `peach.grape.last` already exists. Skipped.
15:31:06 [synteny] Assuming --qbed=peach.bed --sbed=grape.bed
15:31:06 [base] Load file `peach.bed`
15:31:06 [base] Load file `grape.bed`
15:31:07 [blastfilter] Load BLAST file `peach.grape.last` (total 0 lines)
15:31:07 [blastfilter] running the cscore filter (cscore>=0.70) ..
15:31:07 [blastfilter] after filter (0->0) ..
15:31:07 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
15:31:07 [blastfilter] after filter (0->0) ..
15:31:07 [synteny] Assuming --qbed=peach.bed --sbed=grape.bed
15:31:07 [base] Load file `peach.bed`
15:31:08 [base] Load file `grape.bed`
15:31:08 [synteny] A total of 0 BLAST imported from `peach.grape.last.filtered`.
15:31:08 [synteny] Chaining distance = 20
15:31:08 [base] Load file `peach.grape.anchors`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/compara/catalog.py", line 808, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/apps/base.py", line 81, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/compara/catalog.py", line 643, in ortholog
    "--liftover={0}".format(last)])
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/compara/synteny.py", line 1370, in scan
    summary([anchor_file])
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/compara/synteny.py", line 1004, in summary
    nranchors = [_score(c) for c in clusters]  # non-redundant anchors
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.6.1-py2.7.egg/jcvi/compara/synteny.py", line 242, in _score
    x, y = zip(*cluster)[:2]
ValueError: need more than 0 values to unpack
```

After looking at the lastal documentation I noticed that the -f flag requires a ***STRING*** of what format the output will be in, not a number. I think that, as a result of this error, nothing is being stored in the \*last files which is causing it to appear as if there are no hits when it fact there are. Is there any way to get around this issue? Is there a discrepancy between the version of lastal I'm using and jcvi? I have [the most recent version](http://last.cbrc.jp/last-982.zip) (982) installed. Thanks in advance!

**Comment by tanghaibao** [comment]
@floutt 

It seems that your `jcvi` version is too low (you have `0.6.1`, the PyPI version is `0.8.12`). Can you try upgrading it with:

```bash
pip install jcvi
```

Haibao

**Comment by floutt** [comment]
Thanks. Yeah, updating it solved the issue! Thanks.
