### ISSUE TITLE
Argument 'val' has incorrect type

### ISSUE THREAD

**Issue by lamevan** [tanghaibao/jcvi#155]
Dear Haibao,

When I run this command"python -m jcvi.compara.catalog ortholog grape peach".The error
occured:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 846, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 74, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 100, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/catalog.py", line 653, in ortholog
    blastfilter_main([last, "--cscore={0}".format(ccscore)])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/blastfilter.py", line 274, in main
    blastfilter_main(blastfile, p, opts)
  File "/usr/local/lib/python2.7/dist-packages/jcvi/compara/blastfilter.py", line 93, in blastfilter_main
    b.query, b.subject = key
TypeError: Argument 'val' has incorrect type (expected str, got unicode)

Could you try to explain why this error occured ?
Thank you very much!

**Comment by tanghaibao** [comment]
@lamevan 

Thank you for reporting the bug. This was caused by the BLAST parsing module. 

Can you see if you are able to get it to run with Python 3 (you have Python 2)? Overall, we are switching to Python 3. If this is not a choice for you, I'll try to fix it when I get a chance.

Haibao

**Comment by tanghaibao** [comment]
@lamevan 

I think I have fixed the issue and I tested it on my end. Please update the code. If you installed `jcvi` using `pip`, you can do the following to upgrade:

```console
$ pip install -U jcvi
```

Please post back if you continue to experience issues.

Haibao

**Comment by xuzhougeng** [comment]
@tanghaibao  @lamevan I  meet  the same bug , and I fix this bug in https://github.com/tanghaibao/jcvi/pull/158

**Comment by lamevan** [comment]
@tanghaibao @xuzhougeng I can run it without error now . **Thanks a lot !**
