### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by fbemm** [tanghaibao/jcvi#16]
Hey,

I am trying to run Allmaps on a GeneticMap with 5127 markers and allmaps stops shortly after loading the bed file. Any ideas why this is happening? My bed file looks like this:

SCF_9   140192  140193  GeneticMap-2:4.594      SCF_9:140193
SCF_9   156511  156512  GeneticMap-2:7.781      SCF_9:156512
SCF_9   215281  215282  GeneticMap-2:22.010     SCF_9:215282

13:43:09 [base] Load file `out.bed`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ebio/abt6_projects9/guppy_reassembly/data/geneticmap/5_allmaps/jcvi/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1721, in <module>
    main()
  File "/ebio/abt6_projects9/guppy_reassembly/data/geneticmap/5_allmaps/jcvi/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 820, in main
    p.dispatch(globals())
  File "/ebio/abt6_projects9/guppy_reassembly/data/geneticmap/5_allmaps/jcvi/local/lib/python2.7/site-packages/jcvi/apps/base.py", line 81, in dispatch
    globals[action](sys.argv[2:])
  File "/ebio/abt6_projects9/guppy_reassembly/data/geneticmap/5_allmaps/jcvi/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1248, in path
    remove_outliers=(not opts.noremoveoutliers))
  File "/ebio/abt6_projects9/guppy_reassembly/data/geneticmap/5_allmaps/jcvi/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 501, in __init__
    self.append(Marker(b))
  File "/ebio/abt6_projects9/guppy_reassembly/data/geneticmap/5_allmaps/jcvi/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 476, in __init__
    self.mapname, self.lg = b.accn.split("-")
ValueError: too many values to unpack

**Comment by tanghaibao** [comment]
@fbemm hmm ... this works for me. Can you check:

- the bed file is separated by tabs, not spaces
- you are using the latest ``jcvi`` package

```
$ python -c "import jcvi; print jcvi.__version__"
0.6.6
```

Thanks,
Haibao

**Comment by fbemm** [comment]
Hey Haibao, I am using 0.6.6 and mergebed work out of the box. It was something else instead. I had markers with negative cM's. The "-" caused the split command to return a wrong number of results, Thanks, Felix
