### ISSUE TITLE
error while running jcvi.compara.catalog ortholog

### ISSUE THREAD

**Issue by naktang** [tanghaibao/jcvi#164]
I try to run  python  -m jcvi.compara.catalog ortholog KK3_AP_full Sb but it give me a following error.

Traceback (most recent call last):
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 841, in <module>
    main()
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 673, in ortholog
    dotplot_main(dargs)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 357, in dotplot_main
    title=opts.title, stdpf=(not opts.nostdpf))
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 235, in dotplot
    sepcolor=sepcolor, minfont=minfont, stdpf=stdpf)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 79, in plot_breaks_and_labels
    th = TextHandler(fig)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/graphics/base.py", line 53, in __init__
    self.build_height_array(fig)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/graphics/base.py", line 67, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/jcvi/graphics/base.py", line 59, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/matplotlib/textpath.py", line 450, in __init__
    usetex=usetex)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/matplotlib/textpath.py", line 530, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/matplotlib/textpath.py", line 152, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/matplotlib/textpath.py", line 305, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/home/chutima/Software/anaconda2/envs/jcvi/lib/python2.7/site-packages/matplotlib/dviread.py", line 842, in __init__
    with open(filename, 'rb') as file:
IOError: [Errno 2] No such file or directory: u''

I don't know what is the problem. Could you have any suggestion to solve this problem.

**Comment by francicco** [comment]
I have the same error. I think that's because the latex lib are missing or something
F

**Comment by tanghaibao** [comment]
@naktang 

Yes, this is due to latex not installed. 
https://github.com/tanghaibao/jcvi/issues/160#issuecomment-535775163

**Comment by RCDownie** [comment]
@tanghaibao 

I encountered this same error, however I am working in a conda environment. I tried installing a number of different latex packages and none so far resolved the issue. Do you have an idea as to which conda latex package would resolve this?

Thanks
