### ISSUE TITLE
jcvi.graphics.karyotype layout error

### ISSUE THREAD

**Issue by ascendo** [tanghaibao/jcvi#20]
Dear Haibao,

Hello,

When I use karyotype.py, It couldn't read color attribute in layout file.

Here is the error.

17:04:06 [base] Load file `layout`
17:04:06 [base] Load file `ar.bed`
17:04:08 [base] Load file `pineapple.bed`
Traceback (most recent call last):
  File "/home/wyim/bin/python2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/wyim/bin/python2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/graphics/karyotype.py", line 316, in <module>
    main()
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/graphics/karyotype.py", line 304, in main
    Karyotype(fig, root, seqidsfile, layoutfile)
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/graphics/karyotype.py", line 255, in __init__
    layout = Layout(layoutfile, generank=generank)
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/graphics/karyotype.py", line 79, in __init__
    self.assign_colors()
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/graphics/base.py", line 98, in assign_colors
    self.assign_array("color", colorset)
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/graphics/base.py", line 92, in assign_array
    if not getattr(x, attrib):
AttributeError: 'LayoutLine' object has no attribute 'color'

Here is my command,

 `python -m jcvi.graphics.karyotype seqid layout`

layout file contains

**.8, .18, .81, 0, #ff7f00, *Amborella*, center, ar.bed
.7, .18, .81, 0, #377eb8, *Ananas*, center, pineapple.bed
e, 0, 1, pineapple.amborella.4x1.simple**

seqid contains

**LG01
LG02
AmTr_v1.0_scaffold00017
AmTr_v1.0_scaffold00019
AmTr_v1.0_scaffold00021**

**Comment by ascendo** [comment]
removed bottom blank line in "layout" file

**Comment by conchoecia** [comment]
@wyim-pgl you can fix this problem if you use:
```
for line in handle:
    line=line.strip()
    if line:
        process
```
