### ISSUE TITLE
ValueError in karyotype graph generation

### ISSUE THREAD

**Issue by guosongjia** [tanghaibao/jcvi#208]
Dear haibao:
I got an error in karyotype graph generation, showed below.

$ python -m jcvi.graphics.karyotype seqids layout
15:45:05 [blast] Fall back to Python implementation of BlastLine
15:45:05 [base] Load file `layout`
15:45:05 [base] Load file `octosporus.bed`
15:45:05 [base] Load file `cryophilus.bed`
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/suofang/Software/jcvi/jcvi/graphics/karyotype.py", line 350, in <module>
    main()
  File "/home/suofang/Software/jcvi/jcvi/graphics/karyotype.py", line 338, in main
    plot_circles=(not opts.nocircles))
  File "/home/suofang/Software/jcvi/jcvi/graphics/karyotype.py", line 317, in __init__
    plot_label=plot_label, plot_circles=plot_circles)
  File "/home/suofang/Software/jcvi/jcvi/graphics/karyotype.py", line 182, in draw
    si = make_circle_name(sid)
  File "/home/suofang/Software/jcvi/jcvi/graphics/karyotype.py", line 169, in make_circle_name
    si = str(int(si))
ValueError: invalid literal for int() with base 10: ''

please,
Thank you~

**Comment by guosongjia** [comment]
I have solved this question when referring to one website [https://www.omicsclass.com/article/572](url).
Numbers need to be included in the name of chromosome. When I change “chrI, chrII, chrIII” to "chr1, chr2, chr3", the error disappeared.

**Comment by tanghaibao** [comment]
@guosongjia 

Yes you are right about the name of the chromosome. I'll see if I can make the extraction more intelligent than what is currently implemented.

Haibao
