### ISSUE TITLE
allmaps fails in agp step

### ISSUE THREAD

**Issue by ascendo** [tanghaibao/jcvi#22]
I am trying to anchor a draft assembly composed of 661 contigs to close species but it failed 

 Bvchr1_un_sca011 is in our comparative species bed file.

`
```
Traceback (most recent call last):
  File "/home/wyim/bin/python2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/wyim/bin/python2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/assembly/allmaps.py", line 1721, in <module>
    main()
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/assembly/allmaps.py", line 820, in main
    p.dispatch(globals())
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/apps/base.py", line 82, in dispatch
    globals[action](sys.argv[2:])
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/assembly/allmaps.py", line 1362, in path
    gaptype="map")
  File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/formats/agp.py", line 660, in order_to_agp
    size = sizes[ctg]
KeyError: 'Bvchr1_un_sca011'
```

`

I have no clue why it failed.

Any advice on how to get rid of the error?

**Comment by tanghaibao** [comment]
@ascendo is Bvchr1_un_sca011 in the FASTA file?

**Comment by ascendo** [comment]
I made an mistake with --switch option in  python -m jcvi.assembly.syntenypath bed

Sorry about that.
