### ISSUE TITLE
 jcvi.assembly.allmaps path ERROR

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#227]
Hi @tanghaibao,

I'm getting this error, I can't understand why. Something wrong in the installation, on the other cluster I'm working with command and files work.

```
11:30:38 [base] Set text.usetex=False. Font styles may be inconsistent.
11:30:38 [base] Load file `Hheu.scaff.bed`
11:30:38 [allmaps] Map contains 12499 markers in 28 linkage groups.
11:30:38 [allmaps] Retained 12,485 of 12,499 (99.9%) clean markers.
11:30:38 [base] Load file `weights.txt`
Traceback (most recent call last):
  File "/home/tk19812/software/Python-2.7.17/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/tk19812/software/Python-2.7.17/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 2031, in <module>
    main()
  File "/home/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 857, in main
    p.dispatch(globals())
  File "/home/tk19812/software/jcvi/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/home/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 1495, in path
    weights = Weights(weightsfile, mapnames)
  File "/home/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 653, in __init__
    super(Weights, self).__init__(filename, cast=cast)
  File "/home/tk19812/software/jcvi/jcvi/formats/base.py", line 101, in __init__
    self[key] = value
  File "/home/tk19812/software/Python-2.7.17/lib/python2.7/collections.py", line 76, in __setitem__
    root = self.__root
AttributeError: 'Weights' object has no attribute '_OrderedDict__root'
```

Thanks
F

**Comment by tanghaibao** [comment]
@francicco 

Thanks for reporting the bug that impacts python2. I just added the fix and test case. Please checkout the latest commit and let me know if it works for you.

In the future, we will drop the support for python2, so if you can, please move to python3 soon.

Thanks,
Haibao

**Comment by francicco** [comment]
Hi @tanghaibao,

I'm still have problem with AllMaps installation. This is the error

During `python -m jcvi.assembly.syntenypath bed`

```
Traceback (most recent call last):
  File "/home/tk19812/software/Python-2.7.17/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/tk19812/software/Python-2.7.17/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tk19812/software/jcvi/jcvi/assembly/syntenypath.py", line 20, in <module>
    from jcvi.algorithms.graph import BiGraph
  File "/home/tk19812/software/jcvi/jcvi/algorithms/graph.py", line 23, in <module>
    trans = str.maketrans("+?-", ">><")
AttributeError: type object 'str' has no attribute 'maketrans'
```

Best,
F

**Comment by tanghaibao** [comment]
@francicco 

Would you please try to run ALLMAPS with Python 3? We are going to end the support of Python 2 very soon. 

Haibao

**Comment by francicco** [comment]
Ok, I will.
Thanks
F
