### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by pdimens** [tanghaibao/jcvi#233]
Good morning,

I am using a fresh/clean pip(3) installation of JCVI and when running
```bash
python -m jcvi.assembly.allmaps path
```
I get this TypeError during the `Mapping coordinates` phase:

```
Reading liftover chains
Mapping coordinates
20:51:40 [base] sort -k1,1 -k2,2n -k3,3n -k4,4 YFT-splitsex.lifted.bed -o YFT-splitsex.lifted.bed
20:51:40 [base] Load file `YFT-splitsex.bed`
20:51:40 [allmaps] Map contains 15080 markers in 44 linkage groups.
20:51:40 [base] Load file `../../yft_quickmerge_final.fasta.sizes`
20:51:40 [base] Load file `YFT-splitsex.chr.agp`
20:51:41 [base] Load file `YFT-splitsex.chr.agp`
20:51:41 [base] Load file `YFT-splitsex.lifted.bed`
20:51:41 [allmaps] Map contains 15080 markers in 44 linkage groups.
20:51:41 [base] Load file `weights.txt`
20:51:41 [base] Imported 2 records from `weights.txt`.
20:51:41 [allmaps] Map weights: odict_items([('female_distances_ALLMAPS', 1), ('male_distances_ALLMAPS', 1)])
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/jcvi/assembly/allmaps.py", line 2031, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/jcvi/assembly/allmaps.py", line 857, in main
    p.dispatch(globals())
  File "/usr/lib/python3.8/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/lib/python3.8/site-packages/jcvi/assembly/allmaps.py", line 1637, in path   
    plotall(
  File "/usr/lib/python3.8/site-packages/jcvi/assembly/allmaps.py", line 2027, in plotall
    plot(xargs + [seqid])
  File "/usr/lib/python3.8/site-packages/jcvi/assembly/allmaps.py", line 1895, in plot   
    tlg = shorten(mlg.replace("_", "."))  # Latex does not like underscore char
  File "/usr/lib/python3.8/site-packages/jcvi/graphics/base.py", line 152, in shorten
    return s[:pad] + "..." + s[-pad:]
TypeError: slice indices must be integers or None or have an __index__ method
```
I have run this several times with the same outcome. Is this issue familiar to you?

Pavel

**Comment by tanghaibao** [comment]
@pdimens 

Thanks for reporting the bug. This is due to the integer division bug introduced during Py2 -> Py3 migration. I just fixed it in the master branch and also the pip version.

Let me know if this fixes the issue for you.

Haibao

**Comment by pdimens** [comment]
Thank you! I'll reinstall from pip and try again this afternoon.

**Comment by pdimens** [comment]
After installing the latest version with `pip install git+` it all works and the error not longer shows. Thank you!
