### ISSUE TITLE
ZeroDivision error when plotting karytype

### ISSUE THREAD

**Issue by MichelMoser** [tanghaibao/jcvi#24]
Dear JCVI developer, 

i would like to plot a karyotype but get a nasty Zerodivision error back. 
``` 
python -m jcvi.graphics.karyotype seqids layout
21:41:31 [base] Load file `layout`
21:41:31 [base] Load file `paxillaris.bed`
21:41:32 [base] Load file `tomato_p.bed`
Traceback (most recent call last):
  File "/home/moser/Tools/anaconda3/envs/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/moser/Tools/anaconda3/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/moser/Tools/ALLMAPs/code/jcvi/graphics/karyotype.py", line 316, in <module>
    main()
  File "/home/moser/Tools/ALLMAPs/code/jcvi/graphics/karyotype.py", line 304, in main
    Karyotype(fig, root, seqidsfile, layoutfile)
  File "/home/moser/Tools/ALLMAPs/code/jcvi/graphics/karyotype.py", line 280, in __init__
    tr = Track(root, lo, gap=gap, height=height, lw=lw, draw=False)
  File "/home/moser/Tools/ALLMAPs/code/jcvi/graphics/karyotype.py", line 130, in __init__
    ratio = span / total
ZeroDivisionError: float division by zero
```

I suspect the layout file to cause the error. Could the rotation = 0 cause the problem? 

i changed it to integers but the error persits.

Could you give me some help to resolve this? 

Thank you very much, 
Michel

layout: 
```
# y, xstart, xend, rotation, color, label, va,  bed
 .6, .1, .8, 0, blue, axillaris, top, paxillaris.bed
 .4, .1, .8, 0, red, tomato, top, tomato_p.bed
# edges
e, 0, 1, paxillaris.tomato_p.anchors.simple
```

seqids:
```
SL2_40ch01,SL2_40ch02,SL2_40ch03,SL2_40ch04,SL2_40ch05,SL2_40ch06,SL2_40ch07,SL2_40ch08,SL2_40ch09,SL2_40ch10,SL2_40ch11,SL2_40ch12
chrchr1,chrchr2,chrchr3,chrchr4,chrchr5,chrchr6,chrchr7
```

**Comment by MichelMoser** [comment]
Sorry, my own fault, i switched chromosome names between species. 
Problem solved!

**Comment by yanz711** [comment]
I also have this error, but do not know how to solve it?

**Comment by MichelMoser** [comment]
make sure species of layout:line1 corresponds to chromsome names from seqids:line1
it will not work otherwise
when you look at my previous comment, you see that i had the order wrong between the layout file and seqid file.
