### ISSUE TITLE
zero anchor after running  jcvi.compara.catalog ortholog

### ISSUE THREAD

**Issue by Qiaojilim** [tanghaibao/jcvi#247]
I downloaded python 3.7 and latest jcvi according to your instructions but failed when I tried the second step to do pairwise synteny search, I have no idea what is wrong. could you help me solve this issue?
`
$ python3 -m jcvi.compara.catalog ortholog grape peach --no_strip_names    
`

15:24:41 [base] Set text.usetex=False. Font styles may be inconsistent.
15:24:41 [cbook] File `peach.prj` exists. Computation skipped.
15:24:41 [base] lastal -u 0 -P 12 -i3G -f BlastTab peach grape.cds >./grape.peach.last
/bin/bash: line 1: 79173 Bus error: 10           lastal -u 0 -P 12 -i3G -f BlastTab peach grape.cds > ./grape.peach.last
15:24:42 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
15:24:42 [base] Load file `grape.bed`
15:24:42 [base] Load file `peach.bed`
15:24:43 [blastfilter] Load BLAST file `grape.peach.last` (total 0 lines)
15:24:43 [base] Load file `grape.peach.last`
15:24:43 [blastfilter] running the cscore filter (cscore>=0.70) ..
15:24:43 [blastfilter] after filter (0->0) ..
15:24:43 [blastfilter] running the local dups filter (tandem_Nmax=10) ..
15:24:43 [blastfilter] after filter (0->0) ..
15:24:43 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
15:24:43 [base] Load file `grape.bed`
15:24:43 [base] Load file `peach.bed`
15:24:43 [base] Load file `grape.peach.last.filtered`
15:24:43 [synteny] A total of 0 BLAST imported from `grape.peach.last.filtered`.
15:24:43 [synteny] Chaining distance = 20
15:24:43 [base] Load file `grape.peach.anchors`
15:24:43 [synteny] A total of 0 anchor was found. Aborted.
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 939, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/usr/local/lib/python3.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 707, in ortholog
    scan(dargs)
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1902, in scan
    summary([anchor_file])
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1441, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

**Comment by tanghaibao** [comment]
@Qiaojilim 

Your LASTAL command failed - see the line where it says:

```
lastal -u 0 -P 12 -i3G -f BlastTab peach grape.cds
```

Try redownloading/recompiling LASTAL to see if you can get this fixed. If LASTAL fails, `jcvi` won't have anything to process on.

Haibao

**Comment by Qiaojilim** [comment]
@tanghaibao 
thanks  a lot for your quick reply. yes, I recompile and works but exists a new problem that shows 'savefig failed' and  'Failed to process string with tex because latex could not be found'
However  I have downloaded different version latex but just same error appears all the time. any hint  or suggestion I  would be appreciated.  I know this is kind of straightforward problem, but I already tried a lot to fix that
good day!

here is the error 
~~~

 [base] savefig failed. Reset usetex to False.
Failed to process string with tex because latex could not be found
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jcvi/graphics/base.py", line 217, in savefig
    plt.savefig(figname, dpi=dpi, format=format)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)

  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/text.py", line 670, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 47, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 939, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/usr/local/lib/python3.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 724, in ortholog
    dotplot_main(dargs)
  File "/usr/local/lib/python3.7/site-packages/jcvi/graphics/dotplot.py", line 478, in dotplot_main
    savefig(image_name, dpi=iopts.dpi, iopts=iopts)
  File "/usr/local/lib/python3.7/site-packages/jcvi/graphics/base.py", line 223, in savefig
    plt.savefig(figname, dpi=dpi)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/text.py", line 714, in draw
    mtext=mtext)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 1893, in draw_tex
    dvifile = texmanager.make_dvi(s, fontsize)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found

**Comment by Qiaojilim** [comment]
Dear prof. Tang

Just found some hint from issue#160 which helps a lot. I actually installed MacTex successfully but just need to add that executable file to my PAYH


Good day
