### ISSUE TITLE
Synteny in dotplot disappear in karyotype plot.

### ISSUE THREAD

**Issue by cfc424** [tanghaibao/jcvi#258]
Hi Dr.Tang,
I'm trying to plot synteny links, but the blocks exhibited in dotplot missed in synteny plot. 
Here is dotplot:
![image](https://user-images.githubusercontent.com/30213207/84412402-c8352800-ac41-11ea-9dde-c126a99a6f9a.png)
Here is synteny plot:
![image](https://user-images.githubusercontent.com/30213207/84412523-f3b81280-ac41-11ea-8c31-00f10e386fb9.png)

Maybe the high collinearity information was omitted in several chromosomes, how can I fix this and plot all links?

Thanks in advance

**Comment by cfc424** [comment]
Sorry， I found that my anchors file contain the synteny
I tried to find some...
# keep all blocks
`python -m jcvi.compara.synteny screen --simple zjn.mucao.anchors zjn.mucao.anchors.new`
09:41:44 [base] Load file `zjn.mucao.anchors`
09:41:44 [synteny] Assuming --qbed=zjn.bed --sbed=mucao.bed
09:41:44 [base] Load file `zjn.bed`
09:41:45 [base] Load file `mucao.bed`
09:41:45 [base] Load file `zjn.mucao.anchors.new`
09:41:45 [base] Load file `zjn.bed`
09:41:46 [base] Load file `mucao.bed`
09:41:47 [synteny] A total of 258 blocks written to `zjn.mucao.anchors.simple`.
09:41:47 [synteny] Before: **258 blocks, After: 258 blocks**

# test chr1 synteny gene
`grep -f test.simple.anchors  test.chr1.bed`
**Zjn_sc00013.1.g10750.1.sm.mkhc**
Zjn_sc00013.1.g09800.1.es.mkhc
Zjn_sc00013.1.g07420.1.am.mk
Zjn_sc00046.1.g01450.1.sm.mkhc
Zjn_sc00010.1.g01600.1.sm.mkhc
Zjn_sc00002.1.g00030.1.am.mk

# grep `Zjn_sc00013.1.g10750.1.sm.mkhc` block
`grep Zjn_sc00013.1.g10750.1.sm.mkhc   zjn.mucao.anchors.simple `
**Zjn_sc00013.1.g10750.1.sm.mkhc  Zjn_sc00046.1.g00870.1.am.mkhc  evm.model.LG07.1977 evm.model.LG07.3485 1495    -**

Blocks like this didn't show in karyotypes
.....

**Comment by cfc424** [comment]
Sorry, the synteny information exist in anchors.simple file.
I test chr1 blocks....
# keep all blocks
`python -m jcvi.compara.synteny screen --simple zjn.mucao.anchors zjn.mucao.anchors.new`
09:41:44 [base] Load file `zjn.mucao.anchors`
09:41:44 [synteny] Assuming --qbed=zjn.bed --sbed=mucao.bed
09:41:44 [base] Load file `zjn.bed`
09:41:45 [base] Load file `mucao.bed`
09:41:45 [base] Load file `zjn.mucao.anchors.new`
09:41:45 [base] Load file `zjn.bed`
09:41:46 [base] Load file `mucao.bed`
09:41:47 [synteny] A total of 258 blocks written to `zjn.mucao.anchors.simple`.
09:41:47 [synteny] Before: 258 blocks, After: 258 blocks

# test chr1 synteny gene
`grep -f test.simple.anchors  test.chr1.bed`
Zjn_sc00013.1.g10750.1.sm.mkhc
Zjn_sc00013.1.g09800.1.es.mkhc
Zjn_sc00013.1.g07420.1.am.mk
Zjn_sc00046.1.g01450.1.sm.mkhc
Zjn_sc00010.1.g01600.1.sm.mkhc
Zjn_sc00002.1.g00030.1.am.mk

# grep `Zjn_sc00013.1.g10750.1.sm.mkhc` block
`grep Zjn_sc00013.1.g10750.1.sm.mkhc zjn.mucao.anchors.simple `
Zjn_sc00013.1.g10750.1.sm.mkhc  Zjn_sc00046.1.g00870.1.am.mkhc  evm.model.LG07.1977 evm.model.LG07.3485 1495    -
I extracted zjn chr1 blocks to `chr1.anchors.simple`
`python -m jcvi.graphics.karyotype seqids2 layout`
10:13:43 [base] Set text.usetex=False. Font styles may be inconsistent.
10:13:43 [base] Load file `layout`
10:13:43 [base] Load file `zjn.bed`
10:13:44 [base] Load file `mucao.bed`
Traceback (most recent call last):
  File "/home/cfc424/bin/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cfc424/bin/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cfc424/bin/miniconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 435, in <module>
    main()
  File "/home/cfc424/bin/miniconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 422, in main
    generank=(not opts.basepair),
  File "/home/cfc424/bin/miniconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 371, in __init__
    tr = Track(root, lo, gap=gap, height=height, lw=lw, draw=False)
  File "/home/cfc424/bin/miniconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 175, in __init__
    ratio = span / total
ZeroDivisionError: float division by zero

**Comment by cfc424** [comment]
Sorry to bother you，I found seqids information was wrong....when I correct it, everything is OK.
