### ISSUE TITLE
KeyError: 'LOC100779511'

### ISSUE THREAD

**Issue by lkiko** [tanghaibao/jcvi#263]
Hello,

When I run the command:

python -m jcvi.compara.synteny mcscan vv.bed vv.mg.lifted.anchors --iter=1 -o vv.mg.i1.
blocks

I got error messages as below:

20:52:19 [base] Load file `vv.bed`
20:52:19 [base] Load file `vv.mg.lifted.anchors`
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 1969, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 560, in main
    p.dispatch(globals())
  File "/usr/local/lib/python3.6/dist-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 1604, in mcscan
    ranges, block_pairs = ac.make_ranges(order, clip=clip)
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 68, in make_ranges
    r = make_range(q, s, t, i, order, block_pairs, clip=clip)
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 1531, in make_range
    q = [order[x][0] for x in q]
  File "/usr/local/lib/python3.6/dist-packages/jcvi/compara/synteny.py", line 1531, in <listcomp>
    q = [order[x][0] for x in q]
KeyError: 'LOC100779511'

How should this issue be resolved?

Thanks!

**Comment by Qiaojilim** [comment]
I have the same problem, anyone. could help solve it or some suggestion?

**Comment by wyim-pgl** [comment]
There's no 'LOC100779511' in bed file. Maybe it has some suffix in the end of gene name.
Test below first.
```
grep LOC100779511 vv.bed
```

**Comment by Qiaojilim** [comment]
> There's no 'LOC100779511' in bed file. Maybe it has some suffix in the end of gene name.
> Test below first.
> 
> ```
> grep LOC100779511 vv.bed
> ```

thank you Won, yes,   LOC100779511 is not  in vv.bed but it is in mg.bed. and I do not understand why I have this error? though I did try command grep which does not change the result. do you know the reason? appreciate for your help!
Qiaoji

**Comment by wyim-pgl** [comment]
your anchor file should be mg.vv.lifted.anchors. You need to create vv.mg.lifted.anchors when you try to use grape as reference.
