### ISSUE TITLE
output format of jcvi.graphics.karyotype

### ISSUE THREAD

**Issue by qymeng996** [tanghaibao/jcvi#296]
Dear Professor Haibao Tang,
I can get the PDF format file by use "python -m jcvi.graphics.karyotype   seqids layout", however when I modify the format, I met an error:
python -m jcvi.graphics.karyotype --format=emf --figsize=14x7 seqids layout
09:54:13 [base] Load file `layout`
09:54:13 [base] Load file `bgi.bed`
09:54:15 [base] Load file `nbi.bed`
09:54:18 [base] savefig failed. Reset usetex to False.
Format 'emf' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)
Traceback (most recent call last):
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/jcvi/graphics/base.py", line 269, in savefig
    plt.savefig(figname, dpi=dpi, format=format)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2014, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1956, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'emf' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/jcvi/graphics/karyotype.py", line 435, in <module>
    main()
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/jcvi/graphics/karyotype.py", line 431, in main
    savefig(image_name, dpi=iopts.dpi, iopts=iopts)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/jcvi/graphics/base.py", line 275, in savefig
    plt.savefig(figname, dpi=dpi)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2014, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/qymeng/miniconda3/envs/py35/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1956, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'emf' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)
Could you give me some advise to solve this error ? 
Thank you very much.

**Comment by tanghaibao** [comment]
@qymeng996 

It says in the error message:

```
ValueError: Format 'emf' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)
```

So use a format within the supported formats.
