### ISSUE TITLE
jcvi.assembly.allmaps: problem importing weights file

### ISSUE THREAD

**Issue by erikvdbergh** [tanghaibao/jcvi#3]
Hello Haibao,

I am trying to run allmaps using three different maps, but when importing the weights.txt file, I get the following error:
 ```
<a lot of logs, all is well>
10:55:41 [base] Load file `weights.txt`
10:55:41 [base] Imported 3 records from `weights.txt`.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1442, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 759, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi/apps/base.py", line 77, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1109, in path
    plotall([inputbed, "--links={0}".format(opts.links)])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1438, in plotall
    plot(xargs + [seqid])
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 1275, in plot
    weights = Weights(weightsfile, mapnames)
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 562, in __init__
    pivot_weight, o, pivot = self.get_pivot(mapnames)
  File "/usr/local/lib/python2.7/dist-packages/jcvi/assembly/allmaps.py", line 583, in get_pivot
    for m, w in self.items() if m in mapnames)
ValueError: max() arg is an empty sequence
```
I am running python 2.7 on Ubunutu 14.04 with the last versions of the required packages.

my weights.txt file:
```
joinmap 1
mstmap 1
rqtl 1

```

I was hoping you could help me out.

Best,
Erik

**Comment by tanghaibao** [comment]
Erik (@erikvdbergh),

My guess is that the map name in your input does not match what's in the weights file.
Would you please send me a snippet of your input .bed file? Email: tanghaibao@gmail.com

Haibao

**Comment by erikvdbergh** [comment]
The first few lines of my .bed:

```
scaffold00001   2042227 2042228 rqtl-1:47.210600        scaffold00001:2042228
scaffold00001   3570090 3570091 mstmap-11:54.305000     scaffold00001:3570091
scaffold00001   3620911 3620912 mstmap-11:35.466000     scaffold00001:3620912
scaffold00001   3884104 3884105 mstmap-11:0.000000      scaffold00001:3884105
scaffold00001   3935059 3935060 mstmap-11:18.198000     scaffold00001:3935060
scaffold00001   9139640 9139641 mstmap-33:38.050000     scaffold00001:9139641
scaffold00001   9139640 9139641 rqtl-1:88.841990        scaffold00001:9139641
scaffold00001   13215155        13215156        rqtl-1:82.024570        scaffold00001:13215156
scaffold00002   4124049 4124050 joinmap-5:8.241000      scaffold00002:4124050
scaffold00002   4124049 4124050 mstmap-73:81.890000     scaffold00002:4124050
scaffold00002   4197790 4197791 joinmap-5:5.034000      scaffold00002:4197791
scaffold00002   4197790 4197791 mstmap-73:0.000000      scaffold00002:4197791
scaffold00002   4252709 4252710 joinmap-5:9.876000      scaffold00002:4252710
scaffold00002   4252709 4252710 mstmap-73:62.712000     scaffold00002:4252710
scaffold00002   4305780 4305781 joinmap-5:40.997000     scaffold00002:4305781
scaffold00002   4305780 4305781 mstmap-73:31.926000     scaffold00002:4305781
scaffold00002   4544808 4544809 joinmap-5:0.000000      scaffold00002:4544809
```

The weights.txt was autogenerated by the allmaps -merge option.

Thanks,
Erik

**Comment by tanghaibao** [comment]
Erik,

The crash happens on the plotting stage which means it mostly finished. You should be able to see an .agp file and .lifted.bed file which corresponds to the stitched molecule and new positions of the markers.

Can you post the first few lines of the generated .lifted.bed file?

Sorry to debug this back and forth.

Haibao

**Comment by erikvdbergh** [comment]
Looking in the .lifted.bed file, it seems to be empty:
```
vandene@n79460:~$ wc -l tha_n50.lifted.bed
0 tha_n50.lifted.bed
```
I also spotted this in the log:
```
09:47:34 [base] sort -k1,1 -k2,2n -k4,4 tha_n50.lifted.bed -o tha_n50.lifted.bed
09:47:34 [base] Load file `tha_n50.bed`
09:47:34 [allmaps] Map contains 408 markers in 32 linkage groups.
09:47:35 [base] Load file `../../synteny/fasta/C.spinosa_reassembly.fa.sizes`
09:47:35 [base] Load file `tha_n50.chr.agp`
09:47:38 [base] Load file `tha_n50.agp`
09:47:39 [base] Load file `tha_n50.lifted.bed`
09:47:39 [allmaps] Map contains 0 markers in 0 linkage groups.
09:47:39 [base] Load file `weights.txt`
09:47:39 [base] Imported 3 records from `weights.txt`.
<same error as before>
```

Somehow the .lifted.bed file is not being populated?

Thanks for your help, I will try and dive in the code further to see where the error is exactly.

Erik

**Comment by erikvdbergh** [comment]
I've run the liftOver command separately as:
```
vandene@n79460:~$ liftOver -minMatch=1 tha_n50.bed tha_n50.chain tha_n50.lifted.bed unmapped
Reading liftover chains
Killed
```

As you can see it gets killed because it runs out of memory. I think this would also cause the .lifted.bed to not be written. Is there any indication how much it needs? I am running this on a not-so-fancy desktop with only 4GB of RAM, but I will try other options.

Thanks,
Erik

**Comment by erikvdbergh** [comment]
I tried on a bigger machine and it took around 6GB of RAM, so I was just out of memory. Thanks for your help. Maybe a check if liftOver has completed succesfully would be handy?

Erik

**Comment by tanghaibao** [comment]
@erikvdbergh,

Excellent debugging. Thanks, I'll add in some validation in ALLMAPS so that at least the error message would be somewhat more informative.

Haibao
