### ISSUE TITLE
 Load file error

### ISSUE THREAD

**Issue by shiyi-pan** [tanghaibao/jcvi#302]
Hi, I run the jcvi path module use the followling command :

DIR=/gss1/home/hjb20181119/panyongpeng/NN1138-2/genome_assess/ALLMAPS-testdata
python3 -m jcvi.assembly.allmaps path $DIR/JM-2.bed $DIR/scaffolds.fasta -w /gss1/home/hjb20181119/panyongpeng/NN1138-2/genome_assess/ALLMAPS-testdata/weights.txt

When loading other files , it works well, but meet an error when loading weights.txt :

19:41:07 [base] Load file `weights.txt`
Traceback (most recent call last):
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 2037, in <module>
    main()
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 863, in main
    p.dispatch(globals())
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 1647, in path
    "--figsize={0}".format(opts.figsize),
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 2033, in plotall
    plot(xargs + [seqid])
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 1851, in plot
    weights = Weights(weightsfile, mapnames)
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 653, in __init__
    super(Weights, self).__init__(filename, cast=cast)
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/formats/base.py", line 77, in __init__
    fp = must_open(filename)
  File "/gss1/home/hjb20181119/panyongpeng/ruanjian/Python365/lib/python3.6/site-packages/jcvi-1.0.9+6.g6732285-py3.6-linux-x86_64.egg/jcvi/formats/base.py", line 421, in must_open
    fp = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'weights.txt'

Can you help me fix this problem ? Thank you very much.

**Comment by shiyi-pan** [comment]
I think I know why. the weights.txt should be in corrent path.
