### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 3)

### ISSUE THREAD

**Issue by chaimol** [tanghaibao/jcvi#327]
i have install `jcvi` by `conda`.
I am run command `python -m jcvi.graphics.karyotype seqids layout`。
return error info like this :
```
16:49:59 [base] Set text.usetex=False. Font styles may be inconsistent.
16:49:59 [base] Load file `layout`
16:49:59 [base] Load file `Fve.bed`
16:50:00 [base] Load file `Spo.bed`
Traceback (most recent call last):
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 435, in <module>
    main()
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 422, in main
    generank=(not opts.basepair),
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 340, in __init__
    layout = Layout(layoutfile, generank=generank)
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 78, in __init__
    blocks = self.parse_blocks(fn, i)
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 87, in parse_blocks
    return SimpleFile(simplefile, order=order).blocks
  File "/share/home/miniconda3/envs/mmdetection/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 269, in __init__
    a, b, c, d, score, orientation = row.split()
ValueError: not enough values to unpack (expected 6, got 3)
```
my seqids file is
```
Fvb1,Fvb2,Fvb3,Fvb4,Fvb5,Fvb6,Fvb7
Chr01,Chr02,Chr03,Chr04,Chr05,Chr06,Chr07,Chr08,Chr09,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16,Chr17
```
my layout file is
```
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .1,    .8,       0,      , Fve, top, Fve.bed
 .4,     .1,    .8,       0,      , Cpo, top, Cpo.bed
# edges
e, 0, 1, Cpo_Fve.collinearity

```

**Comment by tanghaibao** [comment]
@chaimol 

The file `Cpo_Fve.collinearity` file should have 6 columns and should be of `.simple` format. Please take a look at the tutorial in the wiki to understand how to format this file properly.

https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)

**Comment by chaimol** [comment]
Thank you very much! @tanghaibao my `.simple` file is wrong .
