### ISSUE TITLE
ValueError when generating .simple files

### ISSUE THREAD

**Issue by markchan94** [tanghaibao/jcvi#347]
Dear Haibao,

I'm getting the following error when I tried to generate a `.simple` file between two chromosomes p1 and bt34:

```
$ python -m jcvi.compara.synteny screen --minspan=30 --simple p1.bt34.anchors p1.bt34.anchors.new
17:28:15 [base] Load file `p1.bt34.anchors`
17:28:15 [synteny] Assuming --qbed=p1.bed --sbed=bt34.bed
17:28:15 [base] Load file `p1.bed`
17:28:15 [base] Load file `bt34.bed`
17:28:15 [base] Load file `p1.bt34.anchors.new`
17:28:15 [base] Load file `p1.bed`
17:28:15 [base] Load file `bt34.bed`
Traceback (most recent call last):
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/site-packages/jcvi/compara/synteny.py", line 2007, in <module>
    main()
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/site-packages/jcvi/compara/synteny.py", line 562, in main
    p.dispatch(globals())
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/site-packages/jcvi/compara/synteny.py", line 1439, in screen
    simple(
  File "/cm/shared/apps/devel/anaconda/3/envs/jcvi/lib/python3.8/site-packages/jcvi/compara/synteny.py", line 1214, in simple
    a, b, scores = zip(*block)
ValueError: not enough values to unpack (expected 3, got 0)
```

Can you help to advice on the error and how to fix it? I have attached my `.bed`, `.anchors`, and `.last` files here. Thank you.

[IDO3.bed.txt](https://github.com/tanghaibao/jcvi/files/5819655/IDO3.bed.txt)
[p1.bed.txt](https://github.com/tanghaibao/jcvi/files/5819656/p1.bed.txt)
[p1.IDO3.anchors.txt](https://github.com/tanghaibao/jcvi/files/5819657/p1.IDO3.anchors.txt)
[p1.IDO3.last.txt](https://github.com/tanghaibao/jcvi/files/5819658/p1.IDO3.last.txt)

**Comment by tanghaibao** [comment]
@markchan94 

Thanks for sending the files for debugging. These are very helpful. After screening with `--minspan=30`, we have 0 blocks hence the error. Try something like `--minspan=10` so you'll still have blocks remained after screening. I'll also modify the error message so it's clear what the error means.

**Comment by markchan94** [comment]
@tanghaibao many thanks for the advice. It's working well now and I managed to retain some blocks after screening. Thank you!
