### ISSUE TITLE
ValueError when run python -m jcvi.graphics.karyotype seqids layout

### ISSUE THREAD

**Issue by xfwangNo1** [tanghaibao/jcvi#353]
When I run 'python -m jcvi.graphics.karyotype seqids layout', I encountered the following problem.
/pub/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
04:19:58 [base] Set text.usetex=False. Font styles may be inconsistent.
04:19:58 [base] Load file `layout`
04:19:58 [base] Load file `Cil.bed`
Traceback (most recent call last):
  File "/pub/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/pub/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pub/anaconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 435, in <module>
    main()
  File "/pub/anaconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 422, in main
    generank=(not opts.basepair),
  File "/pub/anaconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 340, in __init__
    layout = Layout(layoutfile, generank=generank)
  File "/pub/anaconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 81, in __init__
    self.append(LayoutLine(row, delimiter=delimiter, generank=generank))
  File "/pub/anaconda3/lib/python3.7/site-packages/jcvi/graphics/karyotype.py", line 46, in __init__
    self.xend = float(args[2])
ValueError: could not convert string to float:

My seqids file:
Chr01,Chr02,Chr03,Chr04,Chr05,Chr06,Chr07,Chr08,Chr09,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16
Chr1,Chr2,Chr3,Chr4,Chr5
My layout file:
# y, xstart, xend, rotation, color, label, va, bed
 .6,    .1,    .8,    0,    red,    Cillinoinensis,    top,   Cil.bed
 .4,    .1,    ,8,    0,    blue,   Athaliana,    top,    Ath.bed
# edges
e, 0, 1, Cil.Ath.anchors.simple

Thanks in advance.

**Comment by tanghaibao** [comment]
@xfwangNo1

You may have a typo here in column 3 of your layout file, which is what the code is complaining about (could not convert `args[2]`):

```diff
-    .4, .1, ,8, 0, blue, Athaliana, top, Ath.bed
+    .4, .1, .8, 0, blue, Athaliana, top, Ath.bed
```
