### ISSUE TITLE
IndexError: list index out of range when running jcvi.compara.catalog ortholog

### ISSUE THREAD

**Issue by eddiemyers** [tanghaibao/jcvi#358]
Hi,

When I run the following

python -m jcvi.compara.catalog ortholog Sp_1 Sp_2 --no_strip_names

I get this error message:

[14:52:17] DEBUG    lastdb Sp_2 Sp_2.cds                                                                                                                                    base.py:1186
[14:54:12] DEBUG    lastal -u 0 -P 28 -i3G -f BlastTab Sp_2 Sp_1.cds >./Sp_1.Sp_2.last                                                                                          base.py:1186
[14:56:45] DEBUG    Assuming --qbed=Sp_1.bed --sbed=Sp_2.bed                                                                                                                  synteny.py:500
           DEBUG    Load file `Sp_1.bed`                                                                                                                                          base.py:37
Traceback (most recent call last):
  File "/zfs/gcl/software/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/zfs/gcl/software/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 949, in <module>
    main()
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 699, in ortholog
    blastfilter_main(dargs)
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/compara/blastfilter.py", line 328, in main
    blastfilter_main(blastfile, p, opts)
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/compara/blastfilter.py", line 40, in blastfilter_main
    qbed, sbed, qorder, sorder, is_self = check_beds(blast_file, p, opts)
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 515, in check_beds
    qbed = Bed(opts.qbed, sorted=sorted)
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/formats/bed.py", line 147, in __init__
    b = BedLine(line)
  File "/home/eamyers/.local/lib/python3.7/site-packages/jcvi/formats/bed.py", line 50, in __init__
    self.start = int(args[1]) + 1
IndexError: list index out of range

A number of intermediate files are produced with the Sp_2 prefix and the Sp_1.Sp_2.last file is also written. I see that other folks have had a similar IndexError issue (e.g., https://github.com/tanghaibao/jcvi/issues/129), but I can't see how their solution will work here. Any help is much appreciated!

Thanks!

**Comment by tanghaibao** [comment]
@eddiemyers 

In your case, the bed file `Sp_1.bed` is invalid. The error is complaining that it could not find the 2nd column on some lines as it goes through the file. 

The BED file format should be tab-delimited and contain at least 4 columns each line. How did you generate the BED format?

**Comment by eddiemyers** [comment]
I wasn't able to find an issue with my original bed file... However when I remade it using

python -m jcvi.formats.gff bed --type=gene --key=Name Sp_1_genes.scaf.gff -o Sp_1.bed

the analysis works. Thanks for point out my problem!
