### ISSUE TITLE
problem in running liftOver on grid

### ISSUE THREAD

**Issue by lfaino** [tanghaibao/jcvi#36]
Dear Authors,
I have an issue when I run the software. The problem is when the allmaps.py script calls liftOver from the grid. I tried to run liftOver on the grid calling the only the software from the bash shell and it works. 

the error that I get is:

16:30:11 [chain] File written to `mapMerged.chain`.
16:30:11 [base] liftOver -minMatch=1 mapMerged.bed mapMerged.chain mapMerged.lifted.bed unmapped
/bin/bash: liftOver: command not found
16:30:11 [base] sort -k1,1 -k2,2n -k3,3n -k4,4 mapMerged.lifted.bed -o mapMerged.lifted.bed
sort: open failed: mapMerged.lifted.bed: No such file or directory
16:30:11 [base] Load file `mapMerged.bed`
16:30:11 [allmaps] Map contains 5584 markers in 14 linkage groups.
16:30:11 [base] Load file `CUCSA_B10_PCCGS_PacBio_gDNA_contig_1_0.mod.fasta.sizes`
16:30:11 [base] Load file `mapMerged.chr.agp`
16:30:11 [base] Load file `mapMerged.agp`
16:30:12 [base] Load file `mapMerged.lifted.bed`
Traceback (most recent call last):
  File "/tools/general/app/anaconda-python-2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/tools/general/app/anaconda-python-2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/assembly/allmaps.py", line 1725, in <module>
    main()
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/assembly/allmaps.py", line 824, in main
    p.dispatch(globals())
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/apps/base.py", line 82, in dispatch
    globals[action](sys.argv[2:])
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/assembly/allmaps.py", line 1379, in path
    "--figsize={0}".format(opts.figsize)])
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/assembly/allmaps.py", line 1721, in plotall
    plot(xargs + [seqid])
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/assembly/allmaps.py", line 1550, in plot
    cc = Map(bedfile, function=function)
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/assembly/allmaps.py", line 503, in __init__
    bed = Bed(filename)
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/formats/bed.py", line 110, in **init**
    for line in must_open(filename):
  File "/home/ghefd/.local/lib/python2.7/site-packages/jcvi-0.6.9-py2.7.egg/jcvi/formats/base.py", line 391, in must_open
    fp = open(filename, mode)
IOError: [Errno 2] No such file or directory: 'mapMerged.lifted.bed'

I think that the software is not found in the bash environment. 

Any ideas?

thanks
Luigi

**Comment by tanghaibao** [comment]
@lfaino yes you are right. Please refer to the installation "External Dependencies" and install liftOver and put it in your ``$PATH``.

https://github.com/tanghaibao/jcvi/wiki/ALLMAPS

**Comment by lfaino** [comment]
@tanghaibao, I have done it. I place in .bashrc and bash_profile. the other software like faSize and concorde work. all the external software are in the same bin folder. any other idea?

Luigi

**Comment by tanghaibao** [comment]
@lfaino what happens if you type ``liftOver`` on the command line?

**Comment by lfaino** [comment]
@tanghaibao, it works. and if I run qig liftOver, where qig is the name of the q system, works as well.

only if python call it, do not work

**Comment by tanghaibao** [comment]
@lfaino relevant code is [here](https://github.com/tanghaibao/jcvi/blob/master/assembly/allmaps.py#L1496). Would you try to modify so that it contains the full path to liftOver? Also, try to login to the grid node and see if you can execute liftOver. Sometimes the grid node does not copy your environment in the head node.

**Comment by lfaino** [comment]
Hi @tanghaibao, 
liftOver can be run from the node when I ssh it. I already tried using the absolute path and it did not work. I can try again.

Luigi
