### ISSUE TITLE
python -m jcvi.assembly.patch refine Error

### ISSUE THREAD

**Issue by agroppi** [tanghaibao/jcvi#363]
With the last version of jcvi (1.1.10) installed in python 3.6.14 on CentOS 7 I had this issue : 

`python -m jcvi.assembly.patch refine my_genome_breakpoints.bed my_genome.gaps.bed`

```
Traceback (most recent call last):
  File "/module/apps/python/3.6.4-lzma/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/module/apps/python/3.6.4-lzma/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/module/apps/python/3.6.4-lzma/lib/python3.6/site-packages/jcvi/assembly/patch.py", line 1133, in <module>
    main()
  File "/module/apps/python/3.6.4-lzma/lib/python3.6/site-packages/jcvi/assembly/patch.py", line 65, in main
    p.dispatch(globals())
  File "/module/apps/python/3.6.4-lzma/lib/python3.6/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/module/apps/python/3.6.4-lzma/lib/python3.6/site-packages/jcvi/assembly/patch.py", line 992, in refine
    ncols = len(open(breakpointsbed).next().split())
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'
```
Thanks for looking at this

Best

Alexis

**Comment by tanghaibao** [comment]
@agroppi 

This is an issue upgrading from Python 2 to Python 3. 
I think I have fixed the issue so try upgrading (`pip install -U jcvi`) but please let me know if the problem persists.

Haibao

**Comment by agroppi** [comment]
@tanghaibao update done and tested
Works perfectly :)
Thanks
Have a nice week-end
