### ISSUE TITLE
not a PNG file 

### ISSUE THREAD

**Issue by installmyy** [tanghaibao/jcvi#384]
hello tang, how to solve this problem?

[22:59:39] ERROR    savefig failed. Reset usetex to False.                                                                                                                                         ]8;id=1625669979.6812723-836696;file:///home/miniconda3/lib/python3.7/site-packages/jcvi/graphics/base.py\base.py]8;;\:287  not a PNG file        
File "/home/miniconda3/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 676, in _open
    raise SyntaxError("not a PNG file")
SyntaxError: not a PNG file

**Comment by tanghaibao** [comment]
@installmyy 

which command generates this error? 
thanks

**Comment by installmyy** [comment]
Thank you for you prompt reply, when i used "jcvi.graphics.synteny" then got this error-message.

**Comment by installmyy** [comment]
@tanghaibao 
Thank you for you prompt reply, when i used "jcvi.graphics.synteny" then got this error-message.

**Comment by installmyy** [comment]
python -m jcvi.graphics.synteny blocks X.bed  blocks.layout  --shadestyle=line --glyphstyle=arrow --genelabelsize 4

**Comment by wangxiaokun-520** [comment]
python -m jcvi.compara.catalog ortholog grape peach --no_strip_names
this command generates a error:
[03:39:22 PM] DEBUG    Dot plot title: Inter-genomic comparison:  dotplot.py:381
                       grape vs peach (14,279 gene pairs)
[03:39:23 PM] INFO     savefig failed. Reset usetex to False.        base.py:287
                       Failed to process string with tex because
                       dvipng could not be found
……

full informations:
[15:35:25] DEBUG    lastdb peach peach.cds                          base.py:1185
[15:38:47] DEBUG    lastal -u 0 -P 80 -i3G -f BlastTab peach        base.py:1185
                    grape.cds >./grape.peach.last
[15:38:53] DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed    synteny.py:499
           DEBUG    Load file `grape.bed`                             base.py:33
           DEBUG    Load file `peach.bed`                             base.py:33
[15:38:54] DEBUG    Load BLAST file `grape.peach.last` (total  blastfilter.py:47
                    515965 lines)
           DEBUG    Load file `grape.peach.last`                      base.py:33
[15:39:02] DEBUG    running the cscore filter (cscore>=0.70)  blastfilter.py:108
                    ..
[15:39:04] DEBUG    after filter (379462->50584) ..           blastfilter.py:111
           DEBUG    running the local dups filter             blastfilter.py:116
                    (tandem_Nmax=10) ..
[15:39:05] DEBUG    after filter (50584->21696) ..            blastfilter.py:156
[15:39:07] DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed    synteny.py:499
           DEBUG    Load file `grape.bed`                             base.py:33
           DEBUG    Load file `peach.bed`                             base.py:33
[15:39:08] DEBUG    Load file `grape.peach.last.filtered`             base.py:33
[15:39:09] DEBUG    A total of 21696 BLAST imported from          synteny.py:387
                    `grape.peach.last.filtered`.
           DEBUG    Chaining distance = 20                       synteny.py:1931
           DEBUG    Load file `grape.peach.anchors`                   base.py:33
A total of 14279 (NR:14160) anchors found in 687 clusters.
Stats: Min=4 Max=269 N=687 Mean=20.78 SD=35.36 Median=8.0 Sum=14279
NR stats: Min=4 Max=268 N=687 Mean=20.61 SD=35.11 Median=8.0 Sum=14160
           DEBUG    Load file `grape.bed`                             base.py:33
           DEBUG    Load file `peach.bed`                             base.py:33
[15:39:10] DEBUG    Load file `grape.peach.last`                      base.py:33
[15:39:15] DEBUG    A total of 379462 BLAST imported from         synteny.py:387
                    `grape.peach.last`.
[15:39:17] DEBUG    Load file `grape.peach.anchors`                   base.py:33
           DEBUG    A total of 14279 anchors imported.            synteny.py:412
[15:39:18] DEBUG    31884 new pairs found (dist=10).             synteny.py:2009
           DEBUG    Removed 6 existing anchors.                    synteny.py:93
           DEBUG    Corrected scores for 1523 anchors.             synteny.py:94
           DEBUG    Anchors written to                             synteny.py:95
                    `grape.peach.lifted.anchors`.
           DEBUG    Load file `grape.peach.lifted.anchors`            base.py:33
A total of 46157 (NR:18271) anchors found in 687 clusters.
Stats: Min=4 Max=1002 N=687 Mean=67.19 SD=110.65 Median=27.0 Sum=46157
NR stats: Min=4 Max=356 N=687 Mean=26.60 SD=43.05 Median=11.0 Sum=18271
[15:39:19] DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed    synteny.py:499
           DEBUG    Load file `grape.bed`                             base.py:33
           DEBUG    Load file `peach.bed`                             base.py:33
[15:39:21] DEBUG    Showing a random subset of 10000 data points  dotplot.py:229
                    (total 14279) for clarity.
           DEBUG    xsize=26346 ysize=47089                       dotplot.py:338
[03:39:22 PM] DEBUG    Dot plot title: Inter-genomic comparison:  dotplot.py:381
                       grape vs peach (14,279 gene pairs)
[03:39:23 PM] INFO     savefig failed. Reset usetex to False.        base.py:287
                       Failed to process string with tex because
                       dvipng could not be found
Traceback (most recent call last):
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 235, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 411, in check_output
    **kwargs).stdout
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 800, in __init__
    restore_signals, start_new_session)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'dvipng': 'dvipng'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/graphics/base.py", line 283, in savefig
    plt.savefig(figname, dpi=dpi, format=format)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/pyplot.py", line 959, in savefig
    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/figure.py", line 2811, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/axes/_base.py", line 3083, in draw
    renderer, self, artists, self.figure.suppressComposite)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/text.py", line 731, in draw
    mtext=mtext)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/backends/backend_agg.py", line 285, in draw_tex
    Z = texmanager.get_grey(s, size, self.dpi)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 310, in get_grey
    pngfile = self.make_png(tex, fontsize, dpi)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 298, in make_png
    self._run_checked_subprocess(cmd, tex)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 239, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because dvipng could not be foun                                                                             d

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 235, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 411, in check_output
    **kwargs).stdout
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 800, in __init__
    restore_signals, start_new_session)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/subprocess.py"                                                                             , line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'dvipng': 'dvipng'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/runpy.py", lin                                                                             e 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/runpy.py", lin                                                                             e 85, in _run_code
    exec(code, run_globals)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/compara/catalog.py", line 740, in ortholog
    dotplot_main(dargs)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/graphics/dotplot.py", line 532, in dotplot_main
    savefig(image_name, dpi=iopts.dpi, iopts=iopts)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             jcvi/graphics/base.py", line 289, in savefig
    plt.savefig(figname, dpi=dpi)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/pyplot.py", line 959, in savefig
    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/figure.py", line 2811, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/axes/_base.py", line 3083, in draw
    renderer, self, artists, self.figure.suppressComposite)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/text.py", line 731, in draw
    mtext=mtext)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/backends/backend_agg.py", line 285, in draw_tex
    Z = texmanager.get_grey(s, size, self.dpi)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 310, in get_grey
    pngfile = self.make_png(tex, fontsize, dpi)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 298, in make_png
    self._run_checked_subprocess(cmd, tex)
  File "/home/wangxiaokun/miniconda3/envs/env1py3.7/lib/python3.7/site-packages/                                                                             matplotlib/texmanager.py", line 239, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because dvipng could not be foun                                                                             d
