### ISSUE TITLE
No such file or directory: '.bed'  (jcvi.compara.catalog ortholog)

### ISSUE THREAD

**Issue by mcsimenc** [tanghaibao/jcvi#389]
Hi, I would like to use `jcvi.compara.catalog ortholog` but encountered an error.

Here is my call and result
```
$ python -m jcvi.compara.catalog ortholog ./at ./gm

[11:11:47] DEBUG    File `./gm.prj` exists. Computation skipped.                                                                                  cbook.py:70
           DEBUG    lastal -u 0 -P 32 -i3G -f BlastTab ./gm ./at.cds >./at.gm.last                                                               base.py:1184
[11:12:02] DEBUG    Assuming --qbed=.bed --sbed=.bed                                                                                           synteny.py:499
           DEBUG    Looks like self-self comparison.                                                                                           synteny.py:512
           DEBUG    Load file `.bed`                                                                                                               base.py:34
Traceback (most recent call last):
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 947, in <module>
    main()
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 697, in ortholog
    blastfilter_main(dargs)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/blastfilter.py", line 322, in main
    blastfilter_main(blastfile, p, opts)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/blastfilter.py", line 38, in blastfilter_main
    qbed, sbed, qorder, sorder, is_self = check_beds(blast_file, p, opts)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 514, in check_beds
    qbed = Bed(opts.qbed, sorted=sorted)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/formats/bed.py", line 144, in __init__
    for line in must_open(filename):
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/formats/base.py", line 435, in must_open
    fp = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: '.bed'
```
Here are the  first few rows in the input files:

```
$ head ./at.bed -n 3
Chr1	3630	5899	AT1G01010	0	+
Chr1	5927	8737	AT1G01020	0	-
Chr1	11648	13714	AT1G01030	0	-
```

```
$ head ./at.cds -n 3
>ATCG00500
ATGGAAAAATCGTGGTTCAATTTTATGTTTTCTAAGGGAGAATTGGAATACAGAGGTGAGCTAAGTAAAGCAATGGATAG
TTTTGCTCCTGGTGAAAAGACTACTATAAGTCAAGACCGTTTTATATATGATATGGATAAAAACTTTTATGGTTGGGATG
```
```
$ head ./gm.bed -n 3
Chr01	27354	28320	Glyma_01G000100	0	-
Chr01	58974	67527	Glyma_01G000200	0	-
Chr01	67769	69968	Glyma_01G000300	0	+
```

```
$ head ./gm.cds -n 3
>Glyma_10G030500
ATGGCAAATGCATGGACAGAAGATCAAATAGCTATATTCCATGAAGCCTTTGTCGTTGTTGACAAGGACTCCGACGGTTT
CATTACGGTGGACGAACTGATATCCATTGTCCGATCATTAGAAGGAAACGCAACAAAAGAAAAAATTCAAGAAATGATTA
```

Does anyone know what a solution to this might be?

Thanks!

**Comment by tanghaibao** [comment]
@mcsimenc 

The easiest fix on your end is to remove the `./`

```
$ python -m jcvi.compara.catalog ortholog at gm
```

I'll also modify the code so that a relative path would still work. Thanks for reporting the issue.

**Comment by mcsimenc** [comment]
Thanks for the quick reply. I tried without the current directory symbols but get this error
```
$ python -m jcvi.compara.catalog ortholog at gm
[05:05:46] DEBUG    Assuming --qbed=at.bed --sbed=gm.bed                                                                                        synteny.py:499
           DEBUG    Load file `at.bed`                                                                                                              base.py:34
           DEBUG    Load file `gm.bed`                                                                                                              base.py:34
[05:05:47] DEBUG    Load BLAST file `at.gm.last` (total 787509 lines)                                                                        blastfilter.py:46
           DEBUG    Load file `at.gm.last`                                                                                                          base.py:34
[05:05:52] DEBUG    running the cscore filter (cscore>=0.70) ..                                                                             blastfilter.py:108
           DEBUG    after filter (327904->66517) ..                                                                                         blastfilter.py:110
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                                                       blastfilter.py:115
           DEBUG    after filter (66517->56830) ..                                                                                          blastfilter.py:155
[05:05:53] DEBUG    Assuming --qbed=at.bed --sbed=gm.bed                                                                                        synteny.py:499
           DEBUG    Load file `at.bed`                                                                                                              base.py:34
           DEBUG    Load file `gm.bed`                                                                                                              base.py:34
[05:05:54] DEBUG    Load file `at.gm.last.filtered`                                                                                                 base.py:34
           DEBUG    A total of 56830 BLAST imported from `at.gm.last.filtered`.                                                                 synteny.py:386
           DEBUG    Chaining distance = 20                                                                                                     synteny.py:1931
           DEBUG    Load file `at.gm.anchors`                                                                                                       base.py:34
A total of 28779 (NR:28599) anchors found in 2705 clusters.
Stats: Min=4 Max=93 N=2705 Mean=10.64 SD=8.89 Median=7.0 Sum=28779
NR stats: Min=4 Max=93 N=2705 Mean=10.57 SD=8.85 Median=7.0 Sum=28599
           DEBUG    Load file `at.bed`                                                                                                              base.py:34
           DEBUG    Load file `gm.bed`                                                                                                              base.py:34
[05:05:55] DEBUG    Load file `at.gm.last`                                                                                                          base.py:34
[05:05:59] DEBUG    A total of 327904 BLAST imported from `at.gm.last`.                                                                         synteny.py:386
[05:06:00] DEBUG    Load file `at.gm.anchors`                                                                                                       base.py:34
           DEBUG    A total of 28779 anchors imported.                                                                                          synteny.py:412
           DEBUG    12028 new pairs found (dist=10).                                                                                           synteny.py:2009
           DEBUG    Removed 57 existing anchors.                                                                                                 synteny.py:93
           DEBUG    Corrected scores for 2215 anchors.                                                                                           synteny.py:94
           DEBUG    Anchors written to `at.gm.lifted.anchors`.                                                                                   synteny.py:95
           DEBUG    Load file `at.gm.lifted.anchors`                                                                                                base.py:34
A total of 40750 (NR:33909) anchors found in 2705 clusters.
Stats: Min=4 Max=161 N=2705 Mean=15.06 SD=13.63 Median=10.0 Sum=40750
NR stats: Min=4 Max=112 N=2705 Mean=12.54 SD=10.78 Median=9.0 Sum=33909
[05:06:01] DEBUG    Assuming --qbed=at.bed --sbed=gm.bed                                                                                        synteny.py:499
           DEBUG    Load file `at.bed`                                                                                                              base.py:34
           DEBUG    Load file `gm.bed`                                                                                                              base.py:34
[05:06:02] DEBUG    Showing a random subset of 10000 data points (total 28779) for clarity.                                                     dotplot.py:227
           DEBUG    xsize=27416 ysize=56044                                                                                                     dotplot.py:338
Traceback (most recent call last):
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 947, in <module>
    main()
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 732, in ortholog
    dotplot_main(dargs)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/graphics/dotplot.py", line 507, in dotplot_main
    dotplot(
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/graphics/dotplot.py", line 341, in dotplot
    xlim, ylim = plot_breaks_and_labels(
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/graphics/dotplot.py", line 156, in plot_breaks_and_labels
    th = TextHandler(fig)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/graphics/base.py", line 68, in __init__
    self.build_height_array(fig)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/graphics/base.py", line 86, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/jcvi/graphics/base.py", line 78, in get_text_width_height
    tp = mpl.textpath.TextPath((0, 0), txt, size=size, usetex=usetex)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/textpath.py", line 388, in __init__
    self._vertices, self._codes = text_to_path.get_text_path(
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/textpath.py", line 114, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/textpath.py", line 232, in get_glyphs_tex
    page, = dvi
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/dviread.py", line 251, in __iter__
    while self._read():
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/dviread.py", line 331, in _read
    self._dtable[byte](self, byte)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/dviread.py", line 174, in wrapper
    return method(self, *[f(self, byte-min) for f in get_args])
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/dviread.py", line 476, in _fnt_def
    self._fnt_def_real(k, c, s, d, a, l)
  File "/home/msimenc/software/anaconda3/envs/last/lib/python3.9/site-packages/matplotlib/dviread.py", line 483, in _fnt_def_real
    raise FileNotFoundError("missing font metrics file: %s" % fontname)
FileNotFoundError: missing font metrics file: phvr7t
```
I read that a possible solution is to install the font with `tlmgr` like `tlmgr install fontspec` but I am working on a CentOS server without root acces. Thanks!

**Comment by tanghaibao** [comment]
@mcsimenc 

The synteny run is done, just the final dot plot failed.

Try run just the dot plot without using Tex:

```
python -m jcvi.graphics.dotplot am.gm.anchors --notex
```
