### ISSUE TITLE
problems in drawing dotplot

### ISSUE THREAD

**Issue by zengxiaofei** [tanghaibao/jcvi#39]
I downloaded the `fasta` and `bed` file of  Athaliana (*Arabidopsis thaliana*) and Alyrata (*Arabidopsis lyrata*) from Phytozome as test data. And then I followed the steps from the wiki page of MCscan (Python version). The `.anchors` file was generated successfully, but an error occurred when I wanted to use command `python -m jcvi.graphics.dotplot Ath.Aly.anchors` to draw a synteny dotplot.

Here's the error info, and the `.anchors` file has been attached: [Ath.Aly.zip](https://github.com/tanghaibao/jcvi/files/707474/Ath.Aly.zip)

```
14:49:19 [synteny] Assuming --qbed=Ath.bed --sbed=Aly.bed
14:49:19 [base] Load file `Ath.bed`
14:49:20 [base] Load file `Aly.bed`
14:49:20 [dotplot] Showing a random subset of 10000 data points (total 22326) for clarity.
14:49:21 [dotplot] xsize=35386 ysize=32670
Traceback (most recent call last):
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 342, in <module>
    minfont=opts.minfont, palette=palette)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 83, in dotplot_main
    minfont=minfont, palette=palette, chrlw=chrlw, title=title)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 180, in dotplot
    th = TextHandler(fig)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/jcvi/graphics/base.py", line 52, in __init__
    self.build_height_array(fig)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/jcvi/graphics/base.py", line 66, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/jcvi/graphics/base.py", line 58, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/matplotlib/textpath.py", line 434, in __init__
    self._vertices, self._codes = self.text_get_vertices_codes(prop, s, usetex=usetex)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/matplotlib/textpath.py", line 515, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/matplotlib/textpath.py", line 139, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/matplotlib/textpath.py", line 290, in get_glyphs_tex
    self.tex_font_map = dviread.PsfontsMap(dviread.find_tex_file('pdftex.map'))
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/site-packages/matplotlib/dviread.py", line 853, in find_tex_file
    stderr=subprocess.PIPE)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/PUBLIC/software/public/System/Python-2.7.6/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Thanks for your attention.
Xiaofei Zeng

**Comment by tanghaibao** [comment]
@zengxiaofei there are two issues:

- First issue is that the Athaliana gene names are somehow incorrect. Below are my complete commands. Notice that in order to collapse isoforms, I set ``--type=gene`` when generating ``Ath.bed``.

```bash
$ python -m jcvi.formats.gff bed --type=gene --key=Name Athaliana_167_gene.gff3.gz -o Ath.bed
$ python -m jcvi.formats.gff bed --type=mRNA --key=Name Alyrata_107_gene.gff3.gz -o Aly.bed
$ python -m jcvi.formats.fasta format --sep="|" Athaliana_167_cds.fa.gz Ath.cds
$ python -m jcvi.formats.fasta format --sep="|" Alyrata_107_cds.fa.gz Aly.cds
$ python -m jcvi.compara.catalog ortholog Ath Aly
$ python -m jcvi.graphics.dotplot Ath.Aly.anchors
```

- Second issue is that tex support (for matplotlib plotting) on your system is not installed/configured. You can check how to properly install tex using the following command. 

```bash
$ sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
```

If you have trouble installing tex, you can also just run it using the docker image like this:

```bash
$ docker pull tanghaibao/jcvi
$ docker run -it --rm -v `pwd`:/tmp tanghaibao/jcvi
root@4792876110d6:/# cd /tmp/
root@4792876110d6:/tmp# python -m jcvi.graphics.dotplot Ath.Aly.anchors
```

You will then see the dot plot in ``Ath.Aly.pdf``.

<img width="693" alt="2017-01-18_1732" src="https://cloud.githubusercontent.com/assets/106987/22090060/25f9e892-dda4-11e6-99a7-ecd095c08902.png">

**Comment by zengxiaofei** [comment]
I forgot to tell you that it solved my problems. 👍 
Thank you very much! 
Xiaofei
