### ISSUE TITLE
Microsynteny Value Error: min() arg is an empty sequence

### ISSUE THREAD

**Issue by KEBRhoades** [tanghaibao/jcvi#416]
Hi, trying to get Microsynteny visualization to work for just two species, not really deviating at all from the example code given in the wiki. Python and JCVI are both updated. I've played around with the layout file but that doesn't fix or change anything about the error. My blocks file only has 10-15 genes. 

Error output below:

```
Traceback (most recent call last):
  File "/mnt/home/rhoade24/anaconda3/envs/Yocca/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/home/rhoade24/anaconda3/envs/Yocca/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/home/rhoade24/anaconda3/envs/Yocca/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/mnt/home/rhoade24/anaconda3/envs/Yocca/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 625, in main
    Synteny(
  File "/mnt/home/rhoade24/anaconda3/envs/Yocca/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 403, in __init__
    ext = bf.get_extent(i, order)
  File "/mnt/home/rhoade24/anaconda3/envs/Yocca/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 184, in get_extent
    si, start = min(ocol)
ValueError: min() arg is an empty sequence
```

Thanks for the help!

Edit: For anyone else having this problem I believe I've figured it out. I needed a larger blocks file to get the program to run, 10-15 genes isn't enough. When I copied the example code of the first 50 lines of the i1.blocks file it worked just fine.

**Comment by KEBRhoades** [comment]
Ah goddammit I spoke too soon. Still having an issue when I use my blocks file.

**Comment by KEBRhoades** [comment]
Alright for real this time: blocks file needs to be tab separated, not space separated. If like me you are very irritated with this and need a quick command to sub tabs in for 2 spaces I used ``` sed -i 's/  /\t/g' test2.blocks ```
