### ISSUE TITLE
Did anyone have this error?

### ISSUE THREAD

**Issue by yanz711** [tanghaibao/jcvi#42]
Traceback (most recent call last):
  File "/software/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1725, in <module>
    main()
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 824, in main
    p.dispatch(globals())
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/apps/base.py", line 82, in dispatch
    globals[action](sys.argv[2:])
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1379, in path
    "--figsize={0}".format(opts.figsize)])
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1721, in plotall
    plot(xargs + [seqid])
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1599, in plot
    g = GeneticMap(ax1, x, y1, y2, markers, tip=tip, flip=flip)
  File "/software/UHTS/jcvi/0.7.1/lib/python2.7/site-packages/jcvi/graphics/chromosome.py", line 181, in __init__
    ratio = r / max_chr_len
ZeroDivisionError: float division by zero

**Comment by tanghaibao** [comment]
See related discussion in https://github.com/tanghaibao/jcvi/issues/24.

**Comment by tanghaibao** [comment]
Closing issue since this is related to #24. Please feel free to re-open for additional issues.
