### ISSUE TITLE
An error with blast.py and base.py

### ISSUE THREAD

**Issue by wook2014** [tanghaibao/jcvi#460]
I have tried to run 
```
python -m jcvi.compara.catalog ortholog G1 G9 --no_strip_names --cpu=35
```
but an error occured
```
Traceback (most recent call last):
  File "/data/home/wuk/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/wuk/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/wuk/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 12, in <module>
    from jcvi.formats.blast import BlastLine
  File "/data/home/wuk/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/blast.py", line 12, in <module>
    from jcvi.formats.base import LineFile, BaseFile, must_open
  File "/data/home/wuk/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py", line 14, in <module>
    from jcvi.apps.base import (
  File "/data/home/wuk/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.py", line 14, in <module>
    from more_itertools import flatten
ModuleNotFoundError: No module named 'more_itertools'
```
jcvi and lastal version 1268 were installed through conda.

**Comment by wook2014** [comment]
I installed more_itertools by
```
pip3 install more_itertools
```
with an error message
```
Installing collected packages: more-itertools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jcvi 1.2.7 requires cython, which is not installed.
jcvi 1.2.7 requires deap, which is not installed.
jcvi 1.2.7 requires ftpretty, which is not installed.
jcvi 1.2.7 requires graphviz, which is not installed.
jcvi 1.2.7 requires ortools, which is not installed.
jcvi 1.2.7 requires pybedtools, which is not installed.
jcvi 1.2.7 requires scikit-image, which is not installed.
jcvi 1.2.7 requires webcolors, which is not installed.
```

**Comment by wook2014** [comment]
The problem solved after I have installed all packages above
