### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xiehui1991** [tanghaibao/jcvi#465]
When I run "python -m jcvi.graphics.synteny blocks scz_zj2.bed blocks.layout", the last step of MCScan,  it got a error that "IndexError: list index out of range". The details are as follows:
[18:01:36] DEBUG    Load file `scz_zj2.bed`                                                                                                                       base.py:34
Traceback (most recent call last):
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/site-packages/jcvi/graphics/synteny.py", line 639, in main
    glyphcolor=opts.glyphcolor,
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/site-packages/jcvi/graphics/synteny.py", line 392, in __init__
    bed = Bed(bedfile)
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/site-packages/jcvi/formats/bed.py", line 147, in __init__
    b = BedLine(line)
  File "/home/houyan/.conda/envs/jcvi/lib/python3.6/site-packages/jcvi/formats/bed.py", line 50, in __init__
    self.start = int(args[1]) + 1
IndexError: list index out of range

Please help me.  Thank you very much.

**Comment by tanghaibao** [comment]
@xiehui1991 

Can you make that the bed file contains tabs instead of space to separate the columns? It should be this format:

```
chr    start    end    name
```

**Comment by xiehui1991** [comment]
Thanks for your guidance.
