### ISSUE TITLE
lastdb-avx2: that's some funny-lookin DNA

### ISSUE THREAD

**Issue by BourbonZhang** [tanghaibao/jcvi#473]
hi，
111) zwh@zwh:~/test/cds$ python -m jcvi.compara.catalog ortholog ac am --no_strip_names
[17:26:27] INFO     Note: NumExpr detected 12 cores but      utils.py:147
                    "NUMEXPR_MAX_THREADS" not set, so
                    enforcing safe limit of 8.
           INFO     NumExpr defaulting to 8 threads.         utils.py:159
           INFO     Set text.usetex=False. Font styles may be base.py:402
                    inconsistent.
           **DEBUG    lastdb am am.cds                         base.py:1185
/usr/lib/last-align/lastdb-avx2: that's some funny-lookin DNA**
[17:26:28] DEBUG    lastal -u 0 -P 12 -i3G -f BlastTab am    base.py:1185
                    ac.cds >./ac.am.last
[17:26:29] DEBUG    Assuming --qbed=ac.bed --sbed=am.bed   synteny.py:499
           DEBUG    Load file `ac.bed`                         base.py:33
           DEBUG    Load file `am.bed`                         base.py:33
           DEBUG    Load BLAST file `ac.am.last` (total blastfilter.py:46
                    129 lines)
           DEBUG    Load file `ac.am.last`                     base.py:33
           DEBUG    running the cscore filter          blastfilter.py:108
                    (cscore>=0.70) ..
           DEBUG    after filter (20->20) ..           blastfilter.py:110
           DEBUG    running the local dups filter      blastfilter.py:115
                    (tandem_Nmax=10) ..
           DEBUG    after filter (20->20) ..           blastfilter.py:155
           DEBUG    Assuming --qbed=ac.bed --sbed=am.bed   synteny.py:499
           DEBUG    Load file `ac.bed`                         base.py:33
           DEBUG    Load file `am.bed`                         base.py:33
           DEBUG    Load file `ac.am.last.filtered`            base.py:33
           DEBUG    A total of 20 BLAST imported from      synteny.py:386
                    `ac.am.last.filtered`.
           DEBUG    Chaining distance = 20                synteny.py:1931
           DEBUG    Load file `ac.am.anchors`                  base.py:33
           DEBUG    A total of 0 anchor was found.        synteny.py:1480
                    Aborted.
Traceback (most recent call last):
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 721, in ortholog
    scan(dargs)
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1948, in scan
    summary([anchor_file])
  File "/home/zwh/miniconda3/envs/111/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1481, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

the am.cds is:
>CYTB
MKKFMNFFSSNEFLKMIMSTIYLPTPVNINYMWNFGSILGIFLMIQIISGFILSMHYCPN
IDIAFWSITNIMKDMNSGWLFRLIHMNGASFYFLMMYIHISRNLFYCSYKLNNVWGIGIM
ILLMSMAAAFMGYVLPWGQMSYWGATVITNLLSAIPYIGDTIVLWIWGGFSINNATLNRF
FSLHFILPLLILFMVILHLFALHLTGSSNPLGSNFNNYKISFHPYFSIKDLLGFYIILFI
FMFINFQFPYHLGDPDNFKIANPMNTPTHIKPEWYFLFAYSILRAIPNKLGGVIGLVMSI
LILYIMIFYNNKMMNNKFNMLNKIYYWMFINNFILLTWLGKQLIEYPFTNINMLFTTTYF
LYFFLNFYLSKLWDNLIWNSPLN
>ND1
MWVLINLLILMIMVLISVAFLTLLERKILGYIQDRKGPNKIMLFGMFQPFSDALKLLSKE
WFFFNYSNLFIYSPMLMFFLSLVMWILYPWFGFMYYIEFSILFMLLVLGLSVYPVLFVGW
ISNCNYAILGSMRLVSTMISFEINLFFLVFSLMMMVESFSFNEFFFFQNNIKFAILLYPL
YLMMFTSMLIELNRTPFDLIEGESELVSGFNIEYHSSMFVLIFLSEYMNIMFMSVILSLM
FYGFKYWSIKFILIYLFHICLIIWIRGILPRIRYDKLMNMCWTEMLMLVMIYLMYLYFMK
EFLCI

**Comment by BourbonZhang** [comment]
hi, Dr Tang:
These are my input file, I  think the format is rigt. I hope g
[am.bed.txt](https://github.com/tanghaibao/jcvi/files/8749661/am.bed.txt)
[ac.cds.txt](https://github.com/tanghaibao/jcvi/files/8749662/ac.cds.txt)
[ac.bed.txt](https://github.com/tanghaibao/jcvi/files/8749663/ac.bed.txt)
[am.cds.txt](https://github.com/tanghaibao/jcvi/files/8749664/am.cds.txt)
et you help. and I search _lastdb-avx2: that's some funny-lookin DNA_ in google and bing can't find anything.

**Comment by BourbonZhang** [comment]
the cds sequense i used the aa squences
