### ISSUE TITLE
lines connecting syntenic blocks not appearing

### ISSUE THREAD

**Issue by sjfleck** [tanghaibao/jcvi#484]
I installed the software and ran through the test data, but I'm not getting lines connecting the grape and peach genome in the karyotype.pdf file. I didn't get the light grey lines in the first command:

python -m jcvi.graphics.karyotype seqids layout

and I also tried the next step where I edited the grape.peach.anchors.simple file and added "g*" before the second line, but the green highlight didn't appear either. I haven't seen any errors or warnings and these are the modules/software that I'm loading:

module load bedtools/2.27.1
module load anaconda3
module load lastal-1296
module load EMBOSS-6.6.0
module load kent_tools
module load LaTeX-20220623

**Comment by sjfleck** [comment]
For reference, these are the files that I was able to generate.

grape vs peach syntenic dot plot:
[grape.peach.pdf](https://github.com/tanghaibao/jcvi/files/8994715/grape.peach.pdf)

grape vs peach syntenic depths:
[grape.peach.depth.pdf](https://github.com/tanghaibao/jcvi/files/8994721/grape.peach.depth.pdf)

grape vs peach macrosynteny visualization:
[karyotype-2.pdf](https://github.com/tanghaibao/jcvi/files/8994726/karyotype-2.pdf)

**Comment by sjfleck** [comment]
I decided to delete all the files and try again. Now I can't get the karyotype plot generated. I'm not sure what changed between attempts. This is the error:

[sjfleck@vortex1:.../mcscan_test]$ python -m jcvi.graphics.karyotype seqids layout
[17:32:41] DEBUG    Load file `layout`                                                                                                                  base.py:33
           DEBUG    Load file `grape.bed`                                                                                                               base.py:33
[17:32:42] DEBUG    Load file `peach.bed`                                                                                                               base.py:33
Traceback (most recent call last):
  File "/projects/academic/vaalbert/modulefiles/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/projects/academic/vaalbert/modulefiles/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/projects/academic/vaalbert/modulefiles/jcvi/jcvi/graphics/karyotype.py", line 464, in <module>
    main()
  File "/projects/academic/vaalbert/modulefiles/jcvi/jcvi/graphics/karyotype.py", line 443, in main
    Karyotype(
  File "/projects/academic/vaalbert/modulefiles/jcvi/jcvi/graphics/karyotype.py", line 361, in __init__
    t = layout[i]
IndexError: list index out of range

**Comment by sjfleck** [comment]
I ran it over again for a 3rd time and now everything is working. It must have been a simple typo or an extra space somewhere. Closing the issue
