### ISSUE TITLE
jcvi.compara.catalog ortholog Error.

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#512]
Hi,

I'm trying to build a synteny map using ALLMAPS, it's a while that I didn't perform this analysis. I used to run `jcvi.compara.catalog ortholog` between the two species. But now I'm getting this error. I don't quite understand what's going on

```
python -m jcvi.compara.catalog ortholog --full --cscore=0.7 Mpol Mmen
Traceback (most recent call last):
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/user/work/tk19812/software/jcvi/jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/user/work/tk19812/software/jcvi/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/user/work/tk19812/software/jcvi/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/user/work/tk19812/software/jcvi/jcvi/compara/catalog.py", line 687, in ortholog
    last_main([bfasta, afasta, cpus_flag], dbtype)
  File "/user/work/tk19812/software/jcvi/jcvi/apps/align.py", line 529, in last
    run_lastdb(
  File "/user/work/tk19812/software/jcvi/jcvi/utils/cbook.py", line 72, in wrapper
    assert op.exists(x), "Something went wrong, `{0}` not found".format(x)
AssertionError: Something went wrong, `Mmen.prj` not found

```

Any help? What am I doing wrong?
Cheers
Francesco

**Comment by tanghaibao** [comment]
@francicco 

Thanks for reporting the issue.
This is a regression due to a recent change (and there was no unit test to cover it).
I think I have fixed the issue, so try to update to latest version (e.g. `pip install -U jcvi`).

Haibao

**Comment by tanghaibao** [comment]
Regression from #504.

**Comment by francicco** [comment]
Thanks a lot! That was quick!

I'm also getting this:

```
Traceback (most recent call last):
  File "/sw/lang/anaconda.3.8.8-2021.05/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/sw/lang/anaconda.3.8.8-2021.05/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/user/work/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 2035, in <module>
    main()
  File "/user/work/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 862, in main
    p.dispatch(globals())
  File "/user/work/tk19812/software/jcvi/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/user/work/tk19812/software/jcvi/jcvi/assembly/allmaps.py", line 1626, in path
    order_to_agp(s.object, s.tour, sizes, fwagp, gapsize=gapsize, evidence="map")
  File "/user/work/tk19812/software/jcvi/jcvi/formats/agp.py", line 800, in order_to_agp
    size = sizes[ctg]
KeyError: 'Scf0000067'
```

At the end of `python -m jcvi.assembly.allmaps path `
Don't know why.
It didn't generate the dotplots, I guess the error is related to it?

Cheers
F

**Comment by tanghaibao** [comment]
`allmaps` is a different tool from `ortholog` - can you verify the initial problem of generating the dot plot was fixed?

For the `allmaps` error, this seems to say that the `Scf0000067` contig/scaffold isn't found in the FASTA file.

**Comment by francicco** [comment]
Hi @tanghaibao 

I fixed the latex error, I swapped the assemblies. I also fix the pdf problem, it was a latex one.

Thanks a lot
F
