### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by RNieuwenhuis** [tanghaibao/jcvi#519]
Hi,

I am trying to scaffold a genome using a genetic map but get an error in the logging process that I cannot find the cause of.
Could you please shed some light on it?

```
python -m jcvi.assembly.allmaps path --cpus=12 --dpi=600 --format=svg X_allmaps_input_01.bed /lustre/scratch/X/X/Hifi_assembly/X_hifiasm_primary_busco_based_purging_1.fasta
15:37:44 [base] Load file `X_wur_allmaps_input_01.bed`
15:37:44 [allmaps] Map contains 3091 markers in 8 linkage groups.
15:37:44 [allmaps] Retained 3,022 of 3,091 (97.8%) clean markers.
15:37:44 [base] Load file `weights.txt`
15:37:44 [base] Imported 1 records from `weights.txt`.
15:37:44 [allmaps] Weight for `X_WUR` set to 1.
Traceback (most recent call last):
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file allmaps.py, line 679
```

```
python --version
Python 2.7.15
```
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argcomplete               1.12.1             pyh9f0ad1d_0    conda-forge
argh                      0.26.2                py27_1001    conda-forge
atk                       2.36.0               ha770c72_4    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                      py27_0    conda-forge
biopython                 1.68                     py27_0    bioconda
blas                      1.1                    openblas    conda-forge
boto3                     1.17.53            pyhd8ed1ab_0    conda-forge
botocore                  1.20.112           pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py27h516909a_1000    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
cffi                      1.14.0           py27hd463f26_0    conda-forge
chardet                   3.0.4           py27h8c360ce_1006    conda-forge
configparser              3.7.3            py27h8c360ce_2    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
coverage                  5.0.4            py27hdf8410d_0    conda-forge
coveralls                 1.11.1                     py_0    conda-forge
cryptography              2.8              py27h2c19f6a_2    conda-forge
cycler                    0.10.0                   py27_0    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
deap                      1.3.1            py27hb3f55d8_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docopt                    0.6.2                    py27_0    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
ete3                      3.1.1                    py27_0    bioconda
expat                     2.4.1                h9c3ff4c_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
functools32               3.2.3.2                  py27_2    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gdk-pixbuf                2.42.2               h19a9c64_1    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
gffutils                  0.10.1             pyh864c0ab_1    bioconda
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
goatools                  1.1.6              pyh5e36f6f_0    bioconda
gobject-introspection     1.56.1           py27hbc4ca2d_2  
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.42.3               h6939c30_2    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gtk2                      2.24.32              h586f36d_1    conda-forge
gts                       0.7.6                h1fc3fae_2    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib_metadata        1.5.0                    py27_0    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jcvi                      1.0.13           py27h0a581ac_0    bioconda
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_ha53f305_2    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1           default_hc23dcda_4    conda-forge
libopenblas               0.3.10               h5a2b251_0  
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.1                h3452ae3_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lxml                      4.5.0            py27hcde611f_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
matplotlib                2.2.5                ha770c72_3    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
mmtf-python               1.0.2                    py27_0    bioconda
more-itertools            5.0.0                      py_0    conda-forge
msgpack-python            1.0.0            py27h9e3301b_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.2                        py_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.72                 hb5efdd6_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1s               h166bdaf_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    6.2.1            py27hd70f55b_1    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-cpuinfo                8.0.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydot                     1.4.1           py27h8c360ce_1002    conda-forge
pyfaidx                   0.6.3.1            pyh5e36f6f_0    bioconda
pygraphviz                1.3.1                    py27_0    bioconda
pyopenssl                 19.1.0                   py27_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypdf2                    1.26.0                   py27_1    conda-forge
pyqt                      5.12.3           py27hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1            py27h8c360ce_1    conda-forge
pytest                    4.6.4                    py27_0    conda-forge
pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
pytest-cov                2.11.0             pyh44b312d_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-wget               3.2                      py27_0    bioconda
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.2              py27h516909a_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reportlab                 3.5.42           py27heca39a3_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
s3transfer                0.3.3                    py27_0    conda-forge
scandir                   1.10.0           py27hdf8410d_1    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
simplejson                3.8.1                    py27_0    bioconda
singledispatch            3.6.1              pyh44b312d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
statsmodels               0.10.2           py27hc1659b7_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xlsxwriter                2.0.0              pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxpm               3.5.13               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

**Comment by tanghaibao** [comment]
@RNieuwenhuis 

The real cause of this issue is that the map names in the `weights` file do not agree with the map names used in the input.
Would you paste the contents in `weights.txt` and a few lines of `X_allmaps_input_01.bed`?

**Comment by RNieuwenhuis** [comment]
Thanks for reaching out so quickly! It seems indeed the there was an underscore instead of a hyphen. Writing the map name in `weights.txt` correctly fixed the issue. Very grateful!
