### ISSUE TITLE
Integer overflow faSize

### ISSUE THREAD

**Issue by RNieuwenhuis** [tanghaibao/jcvi#521]
Hi, 

I just ran into another issue. I did use a different version this time compared to [this issue](https://github.com/tanghaibao/jcvi/issues/519l) (because I thought that issue was maybe a version issue, but it turned out not to be)

```
python -m jcvi.assembly.allmaps path --cpus=12 --dpi=600 --format=svg Leek_wur_allmaps_input_01.bed /lustre/scratch/WUR/PRI/nieuw133/Leek/Hifi_assembly/Leek_hifiasm_primary_busco_based_purging_1.fasta
```
The scaffolding works as intended. But when the `.sizes` file is written there seems to be an issue that seems caused by the size of the chromosomes. There are 8 chromosomes of several Gbp in length. 

```
              DEBUG    Load file `/lustre/scratch/WUR/PRI/nieuw133/Leek/Hifi_assembly/Leek_hifiasm_primary_busco_based_purging_1.fasta.sizes`                                                            base.py:33
              DEBUG    faSize -detailed /lustre/scratch/WUR/PRI/nieuw133/Leek/Genetic_map_scaffolding/Leek_wur_allmaps_input_01.fasta >Leek_wur_allmaps_input_01.fasta.sizes                           base.py:1185
expandFaFastBuf: integer overflow when trying to increase buffer size from 2147483648 to a min of 61.
[07:07:36 PM] DEBUG    Load file `Leek_wur_allmaps_input_01.fasta.sizes`                                                                                                                                 base.py:33
Traceback (most recent call last):
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 2034, in <module>
    main()
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 861, in main
    p.dispatch(globals())
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 1631, in path
    build([inputbed, fastafile])
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 1765, in build
    fromagp([combined_agp, scaffolds, combined_fasta])
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/formats/chain.py", line 168, in fromagp
    qSize = objectsizes[qName]
KeyError: 'chr5'

```

The `faSize` binary from UCSC is the culprit it seems.  Quite some time ago somebody already raised awareness on this in [this issue](https://github.com/ucscGenomeBrowser/kent/issues/44). Now I can create the `.sizes` file manually, but can I restart the whole process so it accepts such a manual file somehow? It seems AllMaps works on both the `.sizes`file and `.chain` simultaneously..

Thanks for actively replying, helping with issues and maintaining this software.

**Comment by tanghaibao** [comment]
@RNieuwenhuis 

Yes, I think I saw this behavior once before. 

If you manually generate `.sizes` file and place it inside the same folder and make sure it has a timestamp newer than the `.fasta`f file, the script won't call `faSize`. So it'll be fine.

Also, if you remove `faSize` from the `PATH`, I think the script will try to generate a `.sizes` file with a Python-based method. Slower but I don't think it suffers the overflow.

**Comment by tanghaibao** [comment]
Related to https://github.com/tanghaibao/jcvi/issues/126

**Comment by RNieuwenhuis** [comment]
Indeed I removed `faSize` from my `$PATH` and Allmaps determined the sizes. Took only a tiny bit longer.
