### ISSUE TITLE
liftOver exits with error 255 in subprocess.CalledProcessError

### ISSUE THREAD

**Issue by RNieuwenhuis** [tanghaibao/jcvi#522]
Hi,

After using your advice to resolve [Issue 521](https://github.com/tanghaibao/jcvi/issues/521). I run into another issue in the liftOver step.

```
[11:00:28 AM] DEBUG    Load file `Leek_wur_allmaps_input_01.fasta.sizes`                                                                                                                    base.py:33
[11:00:29 AM] DEBUG    File written to `Leek_wur_allmaps_input_01.chain`.                                                                                                                 chain.py:204
              DEBUG    liftOver -minMatch=1 Leek_wur_allmaps_input_01.bed Leek_wur_allmaps_input_01.chain Leek_wur_allmaps_input_01.lifted.bed unmapped                                   base.py:1185
Reading liftover chains
Start before zero line 379 of Leek_wur_allmaps_input_01.chain
Traceback (most recent call last):
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 2034, in <module>
    main()
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 861, in main
    p.dispatch(globals())
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 1631, in path
    build([inputbed, fastafile])
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/assembly/allmaps.py", line 1772, in build
    sh(cmd, check=True)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/site-packages/jcvi/apps/base.py", line 1188, in sh
    return call_func(cmd, shell=True, executable=shell)
  File "/home/WUR/nieuw133/miniconda3/envs/Allmaps_3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'liftOver -minMatch=1 Leek_wur_allmaps_input_01.bed Leek_wur_allmaps_input_01.chain Leek_wur_allmaps_input_01.lifted.bed unmapped' returned non-zero exit status 255.
```

To see what error liftOver gave I ran the command outside of the Allmaps context:
```
liftOver -minMatch=1 Leek_wur_allmaps_input_01.bed Leek_wur_allmaps_input_01.chain Leek_wur_allmaps_input_01.lifted.bed unmapped
Reading liftover chains
Start before zero line 379 of Leek_wur_allmaps_input_01.chain
```

```
echo $?
255
```

So that is in agreement with each other and points me to a line. However, I fail to see any issue with the chain file itself and searching for this message online combined with liftOver has not yielded any usable pointers or users with similar issues.

I decided to test with CrossMap to see if I could lift over the `.bed` file. 

```
CrossMap.py bed --unmap-file unmapped Leek_wur_allmaps_input_01.chain Leek_wur_allmaps_input_01.bed Leek_wur_allmaps_input_01.lifted.bed
2022-11-26 10:45:16 [INFO]  Read the chain file "Leek_wur_allmaps_input_01.chain"
```

And that works without errors. Do you have any idea what is going on? Can I feed the chain file I created with CrossMap somehow into Allmaps?
I attached the chain file. 
[Leek_wur_allmaps_input_01.chain.txt](https://github.com/tanghaibao/jcvi/files/10096042/Leek_wur_allmaps_input_01.chain.txt)

Would be very grateful for your help.

**Comment by tanghaibao** [comment]
@RNieuwenhuis 

Yes, you are right. The first reported issue occurs on this line:

```
chain   1000    ptg012825l  31289717    +   0   31289717    chr5    2380182336  -   2348892619  2380182336  127
```

The size of `chr5` seems to be larger than `int32` max, so it seems to be related to #521. Glad that you've found `crossover` to work in this case.

**Comment by RNieuwenhuis** [comment]
Hi @tanghaibao ,

Thanks for your reply. So it was indeed integer overflow again. Good to know the cause and thanks for confirming.
 
Somehow I cannot get Allmaps to accept the drop in file produced with CrossMap. You mentioned in a different thread that it checks if the timestamp is more recent than the previous file [(here I guess)](https://github.com/tanghaibao/jcvi/blob/649270828742537cec9287569ec6322a57fb5ca3/jcvi/apps/base.py#L1331) So far I have not been able to restart a scaffolding process from the most recent file. Am I missing a commandline option to do this? It seems that the first file that is always created is the `.tour` file and all subsequent files will have a timestamp earlier than that one and are thus newly produced again, overwrinting my `.lifted.bed` file.

**Comment by tanghaibao** [comment]
@RNieuwenhuis 

I just added support for CrossMap, just add a flag `--crossmap` after your `path` command. `CrossMap.py` must be on your `PATH`.

In the log, confirm that the command is run.

**Comment by tanghaibao** [comment]
@RNieuwenhuis 

I did a few tests today and decided that `CrossMap` is a good alternative to `liftOver`, so I switched to using `CrossMap`. Please try it with the new version (`pip install -U jcvi`) and let me know if anything breaks.

**Comment by RNieuwenhuis** [comment]
@tanghaibao 

Can confirm that everything now works as expected, even for such a large genome. Thanks for your active support and swift actions. Simply wonderful!
