### ISSUE TITLE
Disk quota error

### ISSUE THREAD

**Issue by MikeEHMatson** [tanghaibao/jcvi#53]
Hello,
I am having an issue with ALLMAPS in which I get an error:
```
python -m jcvi.assembly.allmaps plotall Map.bed --figsize=12x8 --dpi=600 --format=eps
/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/bigdata/bioinfo/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/jcvi-0.5.5-py2.7.egg/jcvi/assembly/allmaps.py", line 1442, in <module>
    main()
  File "/bigdata/bioinfo/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/jcvi-0.5.5-py2.7.egg/jcvi/assembly/allmaps.py", line 759, in main
    p.dispatch(globals())
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/jcvi-0.5.5-py2.7.egg/jcvi/apps/base.py", line 77, in dispatch
    globals[action](sys.argv[2:])
  File "/bigdata/bioinfo/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/jcvi-0.5.5-py2.7.egg/jcvi/assembly/allmaps.py", line 1427, in plotall
    opts, args, iopts = p.set_image_options(xargs, figsize="10x6")
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/jcvi-0.5.5-py2.7.egg/jcvi/apps/base.py", line 316, in set_image_options
    from jcvi.graphics.base import ImageOptions, setup_theme
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/jcvi-0.5.5-py2.7.egg/jcvi/graphics/base.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/textpath.py", line 15, in <module>
    import matplotlib.font_manager as font_manager
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 1421, in <module>
    _rebuild()
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 1408, in _rebuild
    pickle_dump(fontManager, _fmcache)
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.5/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py", line 957, in pickle_dump
    pickle.dump(data, fh)
IOError: [Errno 122] Disk quota exceeded
```

I am working in a cluster environment, have plenty of storage space, and gave the script 100gb of RAM to work with.  Searching the net for "IOError: [Errno 122] Disk quota exceeded" message makes it seem like this might be a general issue in python and not necessarily an issue with jcvi and ALLMAPS, but any insight into this would be appreciated.  Interestingly, after running allmaps path, the same error was given as well, but the resulting files (scaffolded fasta, AGP, .chain, etc...) were present in my directory, so I'm not sure how detrimental it was.

I am waiting on our SysAdmin to update from 0.5.5 to the most recent version (0.6.6 ?), so perhaps that could fixe the issue? 

Mike

**Comment by ascendo** [comment]
I think this is an issue from permission. if you install it locally, it will resolve the problem.
