### ISSUE TITLE
Attempting to run the example given but got 0 Anchors found

### ISSUE THREAD

**Issue by Wongolini** [tanghaibao/jcvi#536]
```
(mcscan) [~/Documents/Cleves_lab/mcscan $]python3 -m jcvi.compara.catalog ortholog grape peach
[18:07:37] DEBUG    lastdb peach peach.cds                                                                                                                                                                                     base.py:1181
/bin/bash: lastdb: command not found
           DEBUG    lastal -u 0 -P 8 -i3G -f BlastTab peach grape.cds >./grape.peach.last                                                                                                                                      base.py:1181
/bin/bash: lastal: command not found
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                                                                                                                               synteny.py:496
           DEBUG    Load file `grape.bed`                                                                                                                                                                                        base.py:34
           DEBUG    Load file `peach.bed`                                                                                                                                                                                        base.py:34
           DEBUG    Load BLAST file `grape.peach.last` (total 0 lines)                                                                                                                                                    blastfilter.py:46
           DEBUG    Load file `grape.peach.last`                                                                                                                                                                                 base.py:34
           DEBUG    running the cscore filter (cscore>=0.70) ..                                                                                                                                                          blastfilter.py:108
           DEBUG    after filter (0->0) ..                                                                                                                                                                               blastfilter.py:110
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                                                                                                                                    blastfilter.py:115
           DEBUG    after filter (0->0) ..                                                                                                                                                                               blastfilter.py:155
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                                                                                                                               synteny.py:496
           DEBUG    Load file `grape.bed`                                                                                                                                                                                        base.py:34
           DEBUG    Load file `peach.bed`                                                                                                                                                                                        base.py:34
[18:07:38] DEBUG    Load file `grape.peach.last.filtered`                                                                                                                                                                        base.py:34
           DEBUG    A total of 0 BLAST imported from `grape.peach.last.filtered`.                                                                                                                                            synteny.py:383
           DEBUG    Chaining distance = 20                                                                                                                                                                                  synteny.py:1928
           DEBUG    Load file `grape.peach.anchors`                                                                                                                                                                              base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.                                                                                                                                                                 synteny.py:1477
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/opt/homebrew/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/opt/homebrew/lib/python3.10/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/opt/homebrew/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 721, in ortholog
    scan(dargs)
  File "/opt/homebrew/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 1945, in scan
    summary([anchor_file])
  File "/opt/homebrew/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 1478, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

```

**Comment by tanghaibao** [comment]
@Wongolini 

```
/bin/bash: lastal: command not found
```

Would you try installing [LAST](https://gitlab.com/mcfrith/last) so that the anchors can be aligned?

**Comment by ABDULLAHGUJJAR** [comment]
(base) padanas-MacBook-Pro:phyto padana$ python -m jcvi.compara.catalog ortholog grape peach --no_strip_names
[22:27:55] INFO     NumExpr defaulting to 8 threads.                utils.py:157
[22:27:56] INFO     Set text.usetex=False. Font styles may be        base.py:402
                    inconsistent.                                               
           DEBUG    lastdb peach peach.cds                          base.py:1185
[22:29:13] DEBUG    lastal -u 0 -P 8 -i3G -f BlastTab peach         base.py:1185
                    grape.cds >./grape.peach.last                               
lastal: illegal option -- P
lastal: bad option
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed    synteny.py:499
           DEBUG    Load file `grape.bed`                             base.py:33
[22:29:14] DEBUG    Load file `peach.bed`                             base.py:33
           DEBUG    Load BLAST file `grape.peach.last` (total  blastfilter.py:46
                    0 lines)                                                    
           DEBUG    Load file `grape.peach.last`                      base.py:33
           DEBUG    running the cscore filter (cscore>=0.70)  blastfilter.py:108
                    ..                                                          
           DEBUG    after filter (0->0) ..                    blastfilter.py:110
           DEBUG    running the local dups filter             blastfilter.py:115
                    (tandem_Nmax=10) ..                                         
           DEBUG    after filter (0->0) ..                    blastfilter.py:155
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed    synteny.py:499
           DEBUG    Load file `grape.bed`                             base.py:33
           DEBUG    Load file `peach.bed`                             base.py:33
[22:29:15] DEBUG    Load file `grape.peach.last.filtered`             base.py:33
           DEBUG    A total of 0 BLAST imported from              synteny.py:386
                    `grape.peach.last.filtered`.                                
           DEBUG    Chaining distance = 20                       synteny.py:1931
           DEBUG    Load file `grape.peach.anchors`                   base.py:33
           DEBUG    A total of 0 anchor was found. Aborted.      synteny.py:1480
Traceback (most recent call last):
  File "/Users/padana/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/padana/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/padana/opt/anaconda3/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/Users/padana/opt/anaconda3/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/Users/padana/opt/anaconda3/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/padana/opt/anaconda3/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 721, in ortholog
    scan(dargs)
  File "/Users/padana/opt/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1948, in scan
    summary([anchor_file])
  File "/Users/padana/opt/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1481, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

**Comment by ABDULLAHGUJJAR** [comment]
i am facing almost same type of problem. Even i have lastal but its shows bad
lastal: illegal option -- P
Anchor 0
can you guide us about this ?

**Comment by tanghaibao** [comment]
@ABDULLAHGUJJAR 

What is your LAST version (`lastal -V`)?
I just tried the latest version, this option `-P` is still there.
