### ISSUE TITLE
jcvi.assembly.geneticmap breakpoint with MSTmap

### ISSUE THREAD

**Issue by wyim-pgl** [tanghaibao/jcvi#541]
Hi Haibao,
I am trying to use genetic map (MSTmap) to break chimeric scaffolds.
For `jcvi.assembly.geneticmap breakpoint`, can we use the input of MSTmap such as [MSTmap_input](http://alumni.cs.ucr.edu/~yonghui/mstmap/example.txt) ?
Thanks.
Won

**Comment by tanghaibao** [comment]
@wyim-pgl 

I haven't touched this for many years but I think it might be still ok to use.

This checks adjacent markers and see if they differ by some percentage (`--diff=0.1`, i.e. 10%), then a breakpoint is found and printed in .bed format.

**Comment by wyim-pgl** [comment]
Thanks Haibao,
```
 python -m jcvi.assembly.geneticmap breakpoint
Usage:
    geneticmap.py breakpoint mstmap.input > breakpoints.bed

    Find scaffold breakpoints using genetic map. Use variation.vcf.mstmap() to
    generate the input for this routine.
```
The usage looks like that.
When I tried to use [MSTmap_input](http://alumni.cs.ucr.edu/~yonghui/mstmap/example.txt) with below command, it generate an error.
```bash
python -m jcvi.assembly.geneticmap breakpoint example.txt
```
```
[08:34:30] DEBUG    Load file `example.txt`                                                                                            base.py:34
Traceback (most recent call last):
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/site-packages/jcvi/assembly/geneticmap.py", line 724, in <module>
    main()
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/site-packages/jcvi/assembly/geneticmap.py", line 172, in main
    p.dispatch(globals())
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/site-packages/jcvi/assembly/geneticmap.py", line 699, in breakpoint
    data = MSTMap(mstmap)
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/site-packages/jcvi/assembly/geneticmap.py", line 114, in __init__
    self.append(MSTMapLine(row, startidx=startidx))
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/lib/python3.7/site-packages/jcvi/assembly/geneticmap.py", line 86, in __init__
    self.seqid, pos = self.id.split(".")
ValueError: not enough values to unpack (expected 2, got 1)
```
Do you have any example input for it?
Thanks.
Won
