### ISSUE TITLE
--iter=1  key error 

### ISSUE THREAD

**Issue by SAMANDOLL** [tanghaibao/jcvi#544]
python -m jcvi.compara.synteny mcscan hap1.bed hap1.hap2.lifted.anchors --iter=1 -o grape.cacao.i1.blocks
[14:02:58] DEBUG    Load file `hap1.bed`                                                          base.py:34
           DEBUG    Load file `hap1.hap2.lifted.anchors`                                          base.py:34
Traceback (most recent call last):
  File "/home/parallels/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/parallels/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 2015, in <module>
    main()
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 568, in main
    p.dispatch(globals())
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1641, in mcscan
    ranges, block_pairs = ac.make_ranges(order, clip=clip)
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 65, in make_ranges
    r = make_range(q, s, t, i, order, block_pairs, clip=clip)
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1568, in make_range
    q = [order[x][0] for x in q]
  File "/home/parallels/anaconda3/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1568, in <listcomp>
    q = [order[x][0] for x in q]
KeyError: 'g3249.t1'

I have tried both ways by making hap2 as a reference(hap2.hap1.lifted.anchors) but still again the same problem with key error 
 for different gene IDs, please guide me on how I can solve this problem.

**Comment by seashore001x** [comment]
I had the same problem

**Comment by seashore001x** [comment]
I found the cause of process error, because the gene names are too similar in the two species. Renaming the gene names of one of the species gives no error

**Comment by hungweichen0327** [comment]
> I found the cause of process error, because the gene names are too similar in the two species. Renaming the gene names of one of the species gives no error

Yes, I also encountered the same situation and solved the problem by renaming the gene names.
