### ISSUE TITLE
Add checks to jcvi.compara.catalog ortholog before running  LAST

### ISSUE THREAD

**Issue by Adamtaranto** [tanghaibao/jcvi#545]
## Issues:

- jcvi.compara.catalog ortholog does not check that LAST is available on the path before running alignment, this leads to some confusing errors and the creation of empty alignment files: `grape.peach.anchors`, `grape.peach.last`, and `grape.peach.last.filtered`.

- If `LAST` is installed via bioconda multi-threading is disabled. Manually running the lastal command with `-P 1` works fine.

## Suggested fixes:

- Have [last function](https://github.com/tanghaibao/jcvi/blob/main/jcvi/apps/align.py#L477) check that lastdb and lastal are on the path before running cmds. Exit with error if not available.
- If lastal cmd returns error containing string "multi-threading disabled" then try again with `-P 1`. Maybe add a catch for  subprocess.CalledProcessError [here](https://github.com/tanghaibao/jcvi/blob/main/jcvi/apps/align.py#L557) after `sh()` call
- If lastal still fails then do not create empty alignment files. Exit with error.
- Add check that .last alignment file is not empty. Exit if empty and don't create filtered and anchors files.

Error if no LAST:
```
python -m jcvi.compara.catalog ortholog grape peach --no_strip_names
[05:07:30] INFO     Set text.usetex=False. Font styles may be inconsistent.                                                    base.py:452
           DEBUG    lastdb peach peach.cds                                                                                    base.py:1181
/bin/bash: line 1: lastdb: command not found
           DEBUG    lastal -u 0 -P 2 -i3G -f BlastTab peach grape.cds >./grape.peach.last                                     base.py:1181
/bin/bash: line 1: lastal: command not found
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                              synteny.py:498
           DEBUG    Load file `grape.bed`                                                                                       base.py:34
           DEBUG    Load file `peach.bed`                                                                                       base.py:34
[05:07:31] DEBUG    Load BLAST file `grape.peach.last` (total 0 lines)                                                   blastfilter.py:46
           DEBUG    Load file `grape.peach.last`                                                                                base.py:34
           DEBUG    running the cscore filter (cscore>=0.70) ..                                                         blastfilter.py:108
           DEBUG    after filter (0->0) ..                                                                              blastfilter.py:110
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                                   blastfilter.py:115
           DEBUG    after filter (0->0) ..                                                                              blastfilter.py:155
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                              synteny.py:498
           DEBUG    Load file `grape.bed`                                                                                       base.py:34
           DEBUG    Load file `peach.bed`                                                                                       base.py:34
           DEBUG    Load file `grape.peach.last.filtered`                                                                       base.py:34
           DEBUG    A total of 0 BLAST imported from `grape.peach.last.filtered`.                                           synteny.py:385
           DEBUG    Chaining distance = 20                                                                                 synteny.py:1930
           DEBUG    Load file `grape.peach.anchors`                                                                             base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.                                                                synteny.py:1479
Traceback (most recent call last):
  File "/opt/conda/envs/jcvitest/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/jcvitest/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/jcvi/jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/workspaces/jcvi/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/workspaces/jcvi/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/workspaces/jcvi/jcvi/compara/catalog.py", line 721, in ortholog
    scan(dargs)
  File "/workspaces/jcvi/jcvi/compara/synteny.py", line 1947, in scan
    summary([anchor_file])
  File "/workspaces/jcvi/jcvi/compara/synteny.py", line 1480, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.
```

Error if LAST from bioconda & does not support multithreading:
```
python -m jcvi.compara.catalog ortholog grape peach --no_strip_names
[05:14:14] INFO     Set text.usetex=False. Font styles may be inconsistent.                                                    base.py:452
           DEBUG    lastdb peach peach.cds                                                                                    base.py:1181
[05:16:09] DEBUG    lastal -u 0 -P 2 -i3G -f BlastTab peach grape.cds >./grape.peach.last                                     base.py:1181
lastal: I was installed here with multi-threading disabled
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                              synteny.py:498
           DEBUG    Load file `grape.bed`                                                                                       base.py:34
[05:16:10] DEBUG    Load file `peach.bed`                                                                                       base.py:34
           DEBUG    Load BLAST file `grape.peach.last` (total 0 lines)                                                   blastfilter.py:46
           DEBUG    Load file `grape.peach.last`                                                                                base.py:34
           DEBUG    running the cscore filter (cscore>=0.70) ..                                                         blastfilter.py:108
           DEBUG    after filter (0->0) ..                                                                              blastfilter.py:110
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                                   blastfilter.py:115
           DEBUG    after filter (0->0) ..                                                                              blastfilter.py:155
           DEBUG    Assuming --qbed=grape.bed --sbed=peach.bed                                                              synteny.py:498
           DEBUG    Load file `grape.bed`                                                                                       base.py:34
           DEBUG    Load file `peach.bed`                                                                                       base.py:34
           DEBUG    Load file `grape.peach.last.filtered`                                                                       base.py:34
           DEBUG    A total of 0 BLAST imported from `grape.peach.last.filtered`.                                           synteny.py:385
           DEBUG    Chaining distance = 20                                                                                 synteny.py:1930
           DEBUG    Load file `grape.peach.anchors`                                                                             base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.                                                                synteny.py:1479
Traceback (most recent call last):
  File "/opt/conda/envs/jcvitest/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/jcvitest/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/jcvi/jcvi/compara/catalog.py", line 955, in <module>
    main()
  File "/workspaces/jcvi/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/workspaces/jcvi/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/workspaces/jcvi/jcvi/compara/catalog.py", line 721, in ortholog
    scan(dargs)
  File "/workspaces/jcvi/jcvi/compara/synteny.py", line 1947, in scan
    summary([anchor_file])
  File "/workspaces/jcvi/jcvi/compara/synteny.py", line 1480, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.
```

**Comment by Adamtaranto** [comment]
Separate issue. I did the above tests in a devcontainer without any latex version installed. The info warning `Set text.usetex=False. Font styles may be inconsistent.` came up suggesting that usetex was being turned off but the script still died with a latex not found error after I fixed the `lastal` issue. 

However, it did run to completion when I added the `--notex` flag to the command (albeit with a lot of complaining about missing fonts).

What is `--notex`  doing that `text.usetex=False` is failing to do??

**Comment by tanghaibao** [comment]
@Adamtaranto 

Thank you. Your issue and suggested fixes are very thorough.
I tried to address these two things separately although I can't guarantee that I have fixed all these cases (somehow I can't install the conda lastal version which is single threaded).
Let me know what you see anything that I haven't covered ..

**Comment by Adamtaranto** [comment]
Awesome!! Thanks @tanghaibao, that seems to have bypassed the issues with matplotlib throwing fatal errors when savefig() is called without latex installed. 

I tested it without `last` installed and with single threaded bioconda version of `last`. All working fine now. Could potentially update the bioconda recipe to include `bioconda::last` as a dependency?

Do you think this fix makes the [error handling in savefig()](https://github.com/tanghaibao/jcvi/blob/main/jcvi/graphics/base.py#L322) redundant? (if it ever actually did anything). I think it's still a good idea to return an error message here, maybe telling the user to try running the command again with the `--notex` flag.

**Comment by Adamtaranto** [comment]
I've made a PR #548 that removes the redundant error handling in savefig and a few other things.

**Comment by Adamtaranto** [comment]
I noticed that the current version of savefig() will still create an empty file if it fails on a latex error and go on to log that the file has been saved.

I've pushed a fix to those issues here: https://github.com/tanghaibao/jcvi/compare/main...Adamtaranto:jcvi:master#

- Call sys.exit(1) after a savefig error
- Cleanup any existing output file < 1Kb 

If you think this is a good fix I can do a new PR

**Comment by tanghaibao** [comment]
@Adamtaranto 

Good idea. Feel free to open a PR.

**Comment by Adamtaranto** [comment]
PR #549
