### ISSUE TITLE
Microsynteny ValueError: invalid literal for int() with base 10: '.'

### ISSUE THREAD

**Issue by erya-song** [tanghaibao/jcvi#550]
Hi, 

Thanks a lot for the wonderful tools!

I have been using the microsynteny visualization pipeline. I met this error：

[17:00:05] DEBUG    Load file `test.blocks`                                                                            base.py:33
Traceback (most recent call last):
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/graphics/synteny.py", line 639, in main
    glyphcolor=opts.glyphcolor,
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/graphics/synteny.py", line 392, in __init__
    bed = Bed(bedfile)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/formats/bed.py", line 147, in __init__
    b = BedLine(line)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/formats/bed.py", line 50, in __init__
    self.start = int(args[1]) + 1
**ValueError: invalid literal for int() with base 10: '.'**

command：
`python -m jcvi.graphics.synteny SIGL.SPSU.bed test.blocks test.layout`

test.blocks:
`SIGL.021931	.
SIGL.021178	.
SIGL.022966	.
SIGL.022088	.
SIGL.023557	.
SIGL.021644	SPSU.009825
SIGL.021260	.
SIGL.020594	SPSU.010827
SIGL.022870	SPSU.010370
SIGL.022110	SPSU.010370
SIGL.022292	SPSU.007805
SIGL.023512	.
SIGL.021196	SPSU.008824
SIGL.021658	SPSU.008824
SIGL.023564	SPSU.008824`

SIGL.SPSU.bed
```
HIC_ASM_0	20006	21140	SIGL.021931	0	+
HIC_ASM_0	56314	60341	SIGL.021178	0	-
HIC_ASM_0	60493	64530	SIGL.022966	0	+
HIC_ASM_0	77310	79010	SIGL.022088	0	+
HIC_ASM_0	101443	104260	SIGL.023557	0	+
HIC_ASM_0	136985	137567	SIGL.021644	0	-
CM014731.1	25131	27365	SPSU.010335	0	-
CM014731.1	82203	83403	SPSU.010734	0	-
CM014731.1	112396	114265	SPSU.007768	0	+
CM014731.1	128594	130520	SPSU.008176	0	+
CM014731.1	133275	136770	SPSU.008570	0	-
```

test.layout:
`# x,	y,	rotation,	ha,	va,	color,	ratio,	label
0.5,	0.6,	0,	left,	center,	m,	1,	SIGL HIC_ASM_0
0.5,	0.4,	0,	left,	center,	#fc8d62,	1,	SPSU CM014731.1
# edges
e, 0, 1`
 
How to deal with it?

Thanks

**Comment by tanghaibao** [comment]
@erya-song 

This is complaining that there is a weird value (`.`) in the second column of your BED file (`SIGL.SPSU.bed`).
Your snippet looks fine though. Would you check?

**Comment by erya-song** [comment]
I have checked the BED file, but have not found the weird value (.). And I tried to replace all the "." with "_" in all input files, but the same error still occurred.

I wondered if the blocks file did not meet the requirements, so I remove all the rows with ".", new error was:

```
Traceback (most recent call last):
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/graphics/synteny.py", line 639, in main
    glyphcolor=opts.glyphcolor,
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/graphics/synteny.py", line 392, in __init__
    bed = Bed(bedfile)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/formats/bed.py", line 147, in __init__
    b = BedLine(line)
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/jcvi/formats/bed.py", line 50, in __init__
    self.start = int(args[1]) + 1
ValueError: invalid literal for int() with base 10: 'SPSU_009825'
```

**Comment by tanghaibao** [comment]
@erya-song 

This error is only about the BED file, not the `.blocks` file. For debugging the new error, could you send the output for command:

```
grep SPSU_009825 SIGL.SPSU.bed
```

The error suggests `SPSU_009825` was found in the *2nd* column - which should actually be in the *4th* column.

**Comment by erya-song** [comment]
The output is:

`CM014731_1	84725942	84726398	SPSU_009825	0	-`

`SPSU_009825` was found in the 4th column.

**Comment by tanghaibao** [comment]
Hmm ... might be worth checking if the columns are delimited by tab (`\t`) and not spaces.
The error message did point to its presence in the wrong column -

**Comment by erya-song** [comment]
This problem has been solved. It worked when I corrected the order of the three input files in my commands.  The order must be `block bed layout`, other orders like `bed block layout` will meet the above error.
