### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by suying77** [tanghaibao/jcvi#555]
Dear @tanghaibao

When I run the following

python -m jcvi.graphics.synteny blocks.txt all.bed block1.layout  --glyphcolor=orthogroup --glyphstyle=arrow --genelabelsize 2 --notex

I get this error message:

[10:31:34] INFO     Set text.usetex=False. Font styles may be inconsistent.                                                   base.py:402
           DEBUG    Load file `all.bed`                                                                                        base.py:33
[10:31:39] DEBUG    Load file `blocks.txt`                                                                                     base.py:33
           DEBUG    Load file `block1.layout`                                                                                  base.py:33
Column 0: Bacca023988 - Bacca032124 (None:2282924-43314)
  None .. 427372 (7) features .. +
Column 1: M1 - M1 (msichr2A:2141204-2939224)
  msichr2A .. 106 (3) features .. +
Column 2: Ms1 - Ms1 (msichr2B:2207505-3669933)
  msichr2B .. 155 (11) features .. -
Column 3: Ms2 - M21 (msychr2A:2766666-3088947)
  msychr2A .. 34 (3) features .. -
[10:31:40] DEBUG    A total of 1 orthogroups formed                                                                        synteny.py:266
Traceback (most recent call last):
  File "/home/f/anaconda3/envs/jcvi1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/f/anaconda3/envs/jcvi1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/f/anaconda3/envs/jcvi1/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/home/f/anaconda3/envs/jcvi1/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 625, in main
    Synteny(
  File "/home/f/anaconda3/envs/jcvi1/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 465, in __init__
    for ga, gb, h in bf.iter_pairs(i, j):
  File "/home/f/anaconda3/envs/jcvi1/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 211, in iter_pairs
    a, b = d[i], d[j]
IndexError: list index out of range

However, I don't know what I did wrong, as the format of the input file is the same as the test data. I would really appreciate it if you could help me figure this out. Thank you very much!

Thanks!

**Comment by tanghaibao** [comment]
@suying77 

Would you mind sending the `block1.layout` file, this is usually a problem of specifying a number that's larger than the total track counts (in your case 4 tracks, so the largest index is 3). Thanks ~

**Comment by suying77** [comment]
Thank you very much for your reply, I have successfully solved this problem. But now I have a new question, I want to use different colors to represent different types of genes, such as TE, the forward gene and the reverse gene. How should this be realized, thank you very much!
