### ISSUE TITLE
jcvi.graphics.karyotype:IndexError: list index out of range

### ISSUE THREAD

**Issue by trubohe** [tanghaibao/jcvi#557]
when i run "python3 -m jcvi.graphics.karyotype seqids.txt layout.txt" the last step of JCVI, it got a error that "IndexError: list index out of range". The details are as follows:
(JCVI) python3 -m jcvi.graphics.karyotype seqids.txt layout.txt
[19:55:32] DEBUG    Load file `layout.txt`                                                                 base.py:34
           DEBUG    Load file `hap1.bed`                                                             base.py:34
[19:55:33] DEBUG    Load file `hap2.bed`                                                             base.py:34
Traceback (most recent call last):
  File "/home/appl/anaconda3/envs/JCVI/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/appl/anaconda3/envs/JCVI/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appl/anaconda3/envs/JCVI/lib/python3.6/site-packages/jcvi/graphics/karyotype.py", line 447, in <module>
    main()
  File "/home/appl/anaconda3/envs/JCVI/lib/python3.6/site-packages/jcvi/graphics/karyotype.py", line 434, in main
    generank=(not opts.basepair),
  File "/home/appl/anaconda3/envs/JCVI/lib/python3.6/site-packages/jcvi/graphics/karyotype.py", line 354, in __init__
    t = layout[i]
IndexError: list index out of range
and here is my layout file :

# y, xstart, xend, rotation, color, label, va,  bed
 .7,  .15,    .85,       0,       , hap1, top, hap1.bed
 .5,  .15,    .85,       0,       , hap2, top, hap2.bed
# edges
e, 0, 1, hap1.hap2.anchors.simple

**Comment by ZhX-Ni** [comment]
i have the same error, but i don't know how to fix it

**Comment by ZhX-Ni** [comment]
i have the same error, but i don't know how to fix it. 
hear is my layout
#y, xstart, xend, rotation, color, label, va, bed
0.5,     0.025,    0.625,      60,      , Qm, top, Qm.bed
0.2,     0.2,    0.8,       0,      , Qv, top, Qv.bed
0.5,     0.375,    0.975,     -60,      , Qa, top, Qa.bed
#edges
e, 0, 1, Qm.Qv.anchors.simple
e, 1, 2, Qv.Qa.anchors.simple

**Comment by trubohe** [comment]
you can try this way：
vim config 
hap1 hap2

cat config | while read id
do
    arr=($id)
    name1=${arr[0]}
    name2=${arr[1]}
    dir=${name1}_${name2}
    mkdir ${dir}
    cp ${name1}.uniq.bed ${dir}/${name1}.bed
    cp ${name2}.uniq.bed ${dir}/${name2}.bed
    cp ${name1}.cds ${dir}/
    cp ${name2}.cds ${dir}/
    cd ${dir}
    python -m jcvi.compara.catalog ortholog --no_strip_names ${name1} ${name2} --cscore=.99
    python -m jcvi.compara.synteny screen --minspan=30 --simple ${name1}.${name2}.anchors ${name1}.${name2}.anchors.new
    tmpstr1=`less -S ${name1}.bed | awk '{print $1}' | uniq | tr '\n' ','`
    str1=${tmpstr1%?}
    echo $str1 > seqids
    tmpstr2=`less -S ${name2}.bed | awk '{print $1}' | uniq | tr '\n' ',' `
    str2=${tmpstr2%?}
    echo $str2 >> seqids
content="
# y, xstart, xend, rotation, color, label, va,  bed\n .6,     .1,    .8,       0,      , ${name1#*_}, top, ${name1}.bed\n .4,     .1,    .8,       0,      , ${name2#*_}, bottom, ${name2}.bed\n# edges\ne, 0, 1, ${name1}.${name2}.anchors.simple
"

echo -e $content > layout

python -m jcvi.graphics.karyotype seqids layout
cd ../

done

**Comment by ZhX-Ni** [comment]
> you can try this way： vim config hap1 hap2
> 
> cat config | while read id do arr=($id) name1=${arr[0]} name2=${arr[1]} dir=${name1}_${name2} mkdir ${dir} cp ${name1}.uniq.bed ${dir}/${name1}.bed cp ${name2}.uniq.bed ${dir}/${name2}.bed cp ${name1}.cds ${dir}/ cp ${name2}.cds ${dir}/ cd ${dir} python -m jcvi.compara.catalog ortholog --no_strip_names ${name1} ${name2} --cscore=.99 python -m jcvi.compara.synteny screen --minspan=30 --simple ${name1}.${name2}.anchors ${name1}.${name2}.anchors.new tmpstr1=`less -S ${name1}.bed | awk '{print $1}' | uniq | tr '\n' ','` str1=${tmpstr1%?} echo $str1 > seqids tmpstr2=`less -S ${name2}.bed | awk '{print $1}' | uniq | tr '\n' ',' ` str2=${tmpstr2%?} echo $str2 >> seqids content="
> 
> # y, xstart, xend, rotation, color, label, va, bed\n .6, .1, .8, 0, , ${name1#__}, top, ${name1}.bed\n .4, .1, .8, 0, , ${name2#__}, bottom, ${name2}.bed\n# edges\ne, 0, 1, ${name1}.${name2}.anchors.simple
> "
> 
> echo -e $content > layout
> 
> python -m jcvi.graphics.karyotype seqids layout cd ../
> 
> done

thanks for your help. but the error still in there
