### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Alalakikun** [tanghaibao/jcvi#579]
[08:03:45] ERROR    Set text.usetex=False. Font styles may be        base.py:403
                    inconsistent.
           DEBUG    Load file `layout3`                               base.py:37
           DEBUG    Load file `Cs.bed`                                base.py:37
           DEBUG    Load file `Rp.bed`                                base.py:37
[08:03:46] DEBUG    Load file `Mme.bed`                               base.py:37
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/jcvi/graphics/karyotype.py", line                                                                                                                                    447, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/jcvi/graphics/karyotype.py", line                                                                                                                                    427, in main
    Karyotype(
  File "/usr/local/lib/python3.8/dist-packages/jcvi/graphics/karyotype.py", line                                                                                                                                    354, in __init__
    t = layout[i]
IndexError: list index out of range

"""""
How should i solve this problem. I would sincirely appreciate any help

**Comment by Alalakikun** [comment]
[08:03:45] ERROR    Set text.usetex=False. Font styles may be        base.py:403
                    inconsistent.
           DEBUG    Load file `layout3`                               base.py:37
           DEBUG    Load file `Cs.bed`                                base.py:37
           DEBUG    Load file `Rp.bed`                                base.py:37
[08:03:46] DEBUG    Load file `Mme.bed`                               base.py:37
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/jcvi/graphics/karyotype.py", line                                                                                                                                    447, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/jcvi/graphics/karyotype.py", line                                                                                                                                    427, in main
    Karyotype(
  File "/usr/local/lib/python3.8/dist-packages/jcvi/graphics/karyotype.py", line                                                                                                                                    354, in __init__
    t = layout[i]
IndexError: list index out of range
"""""
How should i solve this problem. I would sincirely appreciate any hel

**Comment by jgroh** [comment]
Hi, I'm seeing the same error message when attempting to generate the local synteny plot. Any suggestions would be appreciated!

**Comment by tanghaibao** [comment]
@jgroh 

This is usually due to the index (in the `e` line, note that this is 0-indexed) exceeds the number of tracks specified in the `layout`. Would you mind posting the `layout` file if that's not the case?

Haibao

**Comment by Alalakikun** [comment]
seqids3.txt
Chr1,Chr2,Chr3,Chr4,Chr5,Chr6,Chr7,Chr8,Chr9,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16,Chr17,Chr18,Chr19
CM017555.1,CM017556.1,CM017557.1,CM017558.1,CM017559.1,CM017560.1,CM017561.1,CM017562.1,CM017563.1,CM017564.1	,CM017565.1,CM017566.1,CM017567.1,CM017568.1,CM017569.1,CM017570.1,CM017571.1,CM017572.1,CM017573.1
NC_059306.1,NC_059307.1,NC_059308.1,NC_059309.1,NC_059310.1,NC_059311.1,NC_059312.1,NC_059313.1,NC_059314.1,NC_059315.1,NC_059316.1,NC_059317.1,NC_059318.1,NC_059319.1	NC_059320.1,NC_059321.1,NC_059322.1,NC_059323.1

_____________________________________________________________

layout3.txt
# y, xstart, xend, rotation, color, label, va,  bed
 .7,     .1,    .8,	0,      , manila clam, top, Rp.bed
 .5,     .1,    .8,	0,      , razor clam, top, Sc.bed
 .3,     .1,    .8,	0,      , hard clam, bottom, Mme.bed
# edges
e, 0, 1, Rp.Sc.anchors.simple
e, 1, 2, Mme.Sc.anchors.simple

___________________________________________________
These are the two documents

**Comment by mixle18** [comment]
Hi, I'm seeing the same error message when attempting to generate the local synteny plot. Any suggestions would be appreciated!

My layout file looks like this,
# y, xstart, xend, rotation, color, label, va, bed
.6, .1, .4, 0, red, Grape, top, saf_du.bed
.4, .3, .6, 0, blue, Athaliana, top, saf_chinese.bed
# edges
e, 0, 1, saf_chinese.saf_du.anchors.simple

**Comment by etheteal** [comment]
May this will help you: https://www.omicsclass.com/question/2620
