### ISSUE TITLE
Issue with  jcvi.compara.synfind : ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by UpalabdhaD** [tanghaibao/jcvi#583]
❯ python -m jcvi.compara.synfind Pgiganteus.Palecto.last --qbed=Pgiganteus.bed --sbed=Palecto.bed

[02:35:50] DEBUG    Load file `Pgiganteus.bed`                                          base.py:34
           DEBUG    Load file `Palecto.bed`                                             base.py:34
[02:35:51] DEBUG    Load file `Pgiganteus.Palecto.last`                                 base.py:34
           DEBUG    A total of 0 BLAST imported from `Pgiganteus.Palecto.last`.     synteny.py:277
Traceback (most recent call last):
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/synfind.py", line 282, in <module>
    main(blastfile, p, opts)
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/synfind.py", line 233, in main
    batch_query(qbed, sbed, all_data, opts, fw=fw, c=c, transpose=True)
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/synfind.py", line 143, in batch_query
    all_data = transposed(all_data)
  File "/home/upalabdha/mambaforge/envs/jcvi_env/lib/python3.10/site-packages/jcvi/compara/synfind.py", line 42, in transposed
    x, y = zip(*data)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by tanghaibao** [comment]
@UpalabdhaD 

```
DEBUG A total of 0 BLAST imported from Pgiganteus.Palecto.last.
```

Do you have an empty LAST file? Can you check if LAST completed successfully?
