### ISSUE TITLE
AttributeError: 'LayoutLine' object has no attribute 'color'

### ISSUE THREAD

**Issue by YYsama11** [tanghaibao/jcvi#585]
老师您好！依照MCscan (Python version)页面中的bed以及cds的生成原理，我利用blast结果制作了bed文件与cds文件。利用此文件我能够正常生成X.cp.anchors 与 X.cp.anchors.simple，当使用python3 -m jcvi.graphics.karyotype seqids2 layout2指令时出现以下问题：
ug1360@gs82:~/Jiakeli/yy/test2$ python3 -m jcvi.graphics.karyotype seqids2 layout2
[14:20:14] INFO     Note: NumExpr detected 56 cores but "NUMEXPR_MAX_THREADS" not set, so          utils.py:145
                    enforcing safe limit of 8.
           INFO     NumExpr defaulting to 8 threads.                                               utils.py:157
[14:20:15] ERROR    Set text.usetex=False. Font styles may be inconsistent.                         base.py:393
           DEBUG    Load file `layout2`                                                              base.py:37
           DEBUG    Load file `X.bed`                                                                base.py:37
           DEBUG    Load file `cp.bed`                                                               base.py:37
Traceback (most recent call last):
  File "/pub/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/pub/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/pub/anaconda3/lib/python3.8/site-packages/jcvi/graphics/karyotype.py", line 447, in <module>
    main()
  File "/pub/anaconda3/lib/python3.8/site-packages/jcvi/graphics/karyotype.py", line 427, in main
    Karyotype(
  File "/pub/anaconda3/lib/python3.8/site-packages/jcvi/graphics/karyotype.py", line 346, in __init__
    layout = Layout(layoutfile, generank=generank)
  File "/pub/anaconda3/lib/python3.8/site-packages/jcvi/graphics/karyotype.py", line 83, in __init__
    self.assign_colors()
  File "/pub/anaconda3/lib/python3.8/site-packages/jcvi/graphics/base.py", line 124, in assign_colors
    self.assign_array("color", colorset)
  File "/pub/anaconda3/lib/python3.8/site-packages/jcvi/graphics/base.py", line 114, in assign_array
    if not getattr(x, attrib):
AttributeError: 'LayoutLine' object has no attribute 'color'

X.bed 与 cp.bed前几行内容如下：

GWHBHNV00000014 3875    3961    ID=nupt_XX_2516 0       +
GWHBHNV00000014 3879    3966    ID=nupt_XX_4423 0       +
GWHBHNV00000014 3879    3969    ID=nupt_XX_867  0       +
GWHBHNV00000014 3880    3990    ID=nupt_XX_2185 0       +
GWHBHNV00000014 3880    4027    ID=nupt_XX_868  0       +

cp    0       484     nupt_Y4932      0       +
cp    31      320     nupt_X5031      0       +
cp    59      141     nupt_X5043      0       +
cp    123     247     nupt_X5032      0       +
cp    201     247     nupt_X5206      0       +

X.cp.anchors前几行内容如下：
###
ID=nupt_XX_4423 nupt_X4423      63
ID=nupt_XX_2185 nupt_Y4130      44
ID=nupt_XX_2185 nupt_X4775      42
ID=nupt_XX_2185 nupt_X4921      42

X.cp.anchors.simple前几行内容如下：
ID=nupt_XX_4423 ID=nupt_XX_1887 nupt_Y4130      nupt_Y4868      24      +
ID=nupt_XX_3390 ID=nupt_XX_2951 nupt_X3864      nupt_Y4621      16      +
ID=nupt_XX_3452 ID=nupt_XX_5158 nupt_Y4130      nupt_Y4365      30      +
ID=nupt_XX_170  ID=nupt_XX_80   nupt_Y4130      nupt_Y4047      37      +
ID=nupt_XX_4013 ID=nupt_XX_4015 nupt_Y4280      nupt_X4989      23      +

layout2文件内容如下：

#       y,      xstart, xend,   rotation,       color,  label,  va,     bed
        .6,     .2,     .8,     0,      ,    X,    top,    X.bed
        .4,     .5,     .6,     0,      ,  cp,  top,    cp.bed

#       edges
e,      0,      1,      X.cp.anchors.simple

请问这个问题应该怎么解决？

**Comment by biopig** [comment]
You can have a try the parameter `--figsize=FIGSIZE`， for example  `--figsize=15x10`.
