### ISSUE TITLE
Error when trying to generate pdf plots of anchoring a genome to a genetic map

### ISSUE THREAD

**Issue by hrpelg** [tanghaibao/jcvi#587]
Command used: 
python -m jcvi.assembly.allmaps path map.bed $hap1 -w weights.txt

Error:
Traceback (most recent call last):
  File "/workspace/appscratch/miniconda/MAP/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/workspace/appscratch/miniconda/MAP/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hrpelg/.local/lib/python3.10/site-packages/jcvi/assembly/allmaps.py", line 2034, in <module>
    main()
  File "/home/hrpelg/.local/lib/python3.10/site-packages/jcvi/assembly/allmaps.py", line 861, in main
    p.dispatch(globals())
  File "/home/hrpelg/.local/lib/python3.10/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/hrpelg/.local/lib/python3.10/site-packages/jcvi/assembly/allmaps.py", line 1625, in path
    order_to_agp(s.object, s.tour, sizes, fwagp, gapsize=gapsize, evidence="map")
  File "/home/hrpelg/.local/lib/python3.10/site-packages/jcvi/formats/agp.py", line 793, in order_to_agp
    size = sizes[ctg]
KeyError: '\ufeffh1tg000005l'

**Comment by tanghaibao** [comment]
@hrpelg 

Did you happen to edit the input files with Microsoft Notepad or some other editor?

FEFF is the [BOM](https://github.com/clld/clldutils/issues/65) character that these editor adds to the start of the file, can you try using VSCode or vim to open the input files?
