### ISSUE TITLE
Problem estimating gap sizes

### ISSUE THREAD

**Issue by HebbeD** [tanghaibao/jcvi#6]
Hello there,
I am trying to estimating gap sizes, but I get the following errors:

/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:188: UserWarning:
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/jcvi-0.5.7-py2.7.egg/jcvi/assembly/allmaps.py", line 1574, in <module>
    main()
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/jcvi-0.5.7-py2.7.egg/jcvi/assembly/allmaps.py", line 788, in main
    p.dispatch(globals())
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/jcvi-0.5.7-py2.7.egg/jcvi/apps/base.py", line 78, in dispatch
    globals[action](sys.argv[2:])
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/jcvi-0.5.7-py2.7.egg/jcvi/assembly/allmaps.py", line 908, in estimategaps
    verbose=verbose)
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/jcvi-0.5.7-py2.7.egg/jcvi/assembly/allmaps.py", line 736, in compute_all_gaps
    minsize, maxsize, verbose=verbose)
  File "/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/jcvi-0.5.7-py2.7.egg/jcvi/assembly/allmaps.py", line 709, in compute_one_gap
    converted_dist = int(round(cm_dist / ratio))
ValueError: cannot convert float NaN to integer

I was hoping you could help me out.
Best
Hebbe

**Comment by tanghaibao** [comment]
@HebbeD thanks for reporting this. My current recommendation is to not compute the gap sizes from ALLMAPS.  These estimates may not be reliable and have large variance and it's difficult to foresee all different cases before hand. Your error message may come from a numerical error - we can try to disable this error and let the script complete - but at this point my recommendation is to avoid the gap estimate altogether.

**Comment by HebbeD** [comment]
Thank you for your reply!
I'll follow your advice.

**Comment by hrpelg** [comment]
Hi I got this issue just for some of the bed files I got for some chromosomes

ESC[0;33m11:14:56 [allmaps]ESC[0mESC[0;35m Extracted 205 markers for chr3-LG-3ESC[0m
Traceback (most recent call last):
  File "/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/powerplant/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/powerplant/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/powerplant/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1158, in estimategaps
    g = GapEstimator(cc, agp, ob, mlg)
  File "/powerplant/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 714, in __init__
    self.get_splines()
  File "/powerplant/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 726, in get_splines
    spl = UnivariateSpline(xx, yy)
  File "/workspace/appscratch/miniconda/hrpelg_1/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py", line 176, in __init__
    raise ValueError('x must be strictly increasing')
ValueError: x must be strictly increasing

**Comment by jgroh** [comment]
@tanghaibao I would like to estimate gap sizes but am experiencing this exact same issue - do you know how it can be resolved?
