### ISSUE TITLE
ValueError when running "python -m jcvi.graphics.synteny"

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#609]
Dear @tanghaibao and community,

When I run "python -m jcvi.graphics.synteny CQ3649.Crystal.i1.PAP.blocks CQ3649_Crystal.bed PAP1_block.layout", I encountered the following error.
```
[10:35:39] DEBUG    Load file `CQ3649_Crystal.bed`                                                                                          base.py:33
           DEBUG    Load file `CQ3649.Crystal.i1.PAP.blocks`                                                                                base.py:33
           DEBUG    Load file `PAP1_block.layout`                                                                                           base.py:33
Traceback (most recent call last):
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 625, in main
    Synteny(
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 395, in __init__
    self.layout = lo = Layout(layoutfile)
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 108, in __init__
    self.append(LayoutLine(row, delimiter=delimiter))
  File "/home/hpc/crlee/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 63, in __init__
    self.x = float(args[0])
ValueError: could not convert string to float: ''
```

The interesting blocks are listed in `CQ3649.Crystal.i1.PAP.blocks`:
```
CQ3649_Chr_4.429	Crystal_Chr_4.395
CQ3649_Chr_4.430	Crystal_Chr_4.396
CQ3649_Chr_4.431	Crystal_Chr_4.396
CQ3649_Chr_4.432	.
CQ3649_Chr_4.433	.
CQ3649_Chr_4.434	.
CQ3649_Chr_4.435	.
CQ3649_Chr_4.436	Crystal_Chr_4.396
CQ3649_Chr_4.437	Crystal_Chr_4.396
CQ3649_Chr_4.438	.
CQ3649_Chr_4.439	Crystal_Chr_4.396
CQ3649_Chr_4.440	Crystal_Chr_4.397
```

The `PAP1_block.layout` is below:
```
# x,   y, rotation,   ha,     va,   color, ratio,            label
0.5, 0.6,        0, left, center,      red,     1,      CQ3649_Chr4
0.5, 0.4,        0, left, center,     blue,     1,     Crystal_Chr4

# edges
e, 0, 1
```

The first 10 rows of the `CQ3649_Crystal.bed` is below:
```
CQ3649_CQ3649_Chr_1	1684	3469	CQ3649_Chr_1.1	0	-
CQ3649_CQ3649_Chr_1	15951	21085	CQ3649_Chr_1.2	0	-
CQ3649_CQ3649_Chr_1	24312	26274	CQ3649_Chr_1.3	0	+
CQ3649_CQ3649_Chr_1	62066	62838	CQ3649_Chr_1.4	0	-
CQ3649_CQ3649_Chr_1	65712	68984	CQ3649_Chr_1.5	0	-
CQ3649_CQ3649_Chr_1	72845	73172	CQ3649_Chr_1.6	0	-
CQ3649_CQ3649_Chr_1	78879	81617	CQ3649_Chr_1.7	0	-
CQ3649_CQ3649_Chr_1	82997	88213	CQ3649_Chr_1.8	0	+
CQ3649_CQ3649_Chr_1	92281	92644	CQ3649_Chr_1.9	0	-
CQ3649_CQ3649_Chr_1	97886	98619	CQ3649_Chr_1.10	0	-
```

Thank you for the help.

**Comment by hungweichen0327** [comment]
I find the error is due to the layout file. I copied the contents of the .bed file from other people and revised it.
It worked!
```
# x,	y,	rotation,	ha,	va,	color,	ratio,	label
0.5,	0.6,	0,	left,	center,	blue,	1,	CQ3649_Chr4
0.5,	0.4,	0,	left,	center,	red,	1,	Crystal_Chr4
# edges
e, 0, 1
```


But I don't know the reason that the previous version of layout file could not work.

**Comment by tanghaibao** [comment]
thanks, glad this works for you now. The previous error may be due to the empty line before `# edges`
