### ISSUE TITLE
Pairwise synteny visualization

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [tanghaibao/jcvi#61]
kindly guide i am facing this problem.i am trying so much but i ca't solve this problem.anybody 
can guide me about this????
```
appledeMacBook-Pro-3:mcscan Abdullah$ python -m jcvi.graphics.dotplot grape.peach.anchors
22:29:54 [base] ***ERROR: Cannot execute binary `yn00`. Some functions may not work.***
22:29:54 [base] ***ERROR: Cannot execute binary `pal2nal.pl`. Some functions may not work.***
22:29:54 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
22:29:54 [base] Load file `grape.bed`
22:29:54 [base] Load file `peach.bed`
22:29:55 [dotplot] Showing a random subset of 10000 data points (total 14695) for clarity.
22:29:55 [dotplot] xsize=26346 ysize=28701
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/dotplot.py", line 342, in <module>
    minfont=opts.minfont, palette=palette)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/dotplot.py", line 83, in dotplot_main
    minfont=minfont, palette=palette, chrlw=chrlw, title=title)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/dotplot.py", line 180, in dotplot
    th = TextHandler(fig)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/base.py", line 52, in __init__
    self.build_height_array(fig)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/base.py", line 66, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/base.py", line 58, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 446, in __init__
    usetex=usetex)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 526, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 152, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 305, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/dviread.py", line 868, in find_tex_file
    stderr=subprocess.PIPE)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/subprocess32.py", line 825, in __init__
    restore_signals, start_new_session)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/subprocess32.py", line 1574, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'kpsewhich'
```

**Comment by vivekkrish** [comment]
Hi @ABDULLAHGUJJAR,

From looking at the error message above, it would seem that your system is missing the following required packages/dependencies:
* PAML: http://abacus.gene.ucl.ac.uk/software/paml.html (which contains the binary, `yn00`)
* pal2nal: http://www.bork.embl.de/pal2nal/ (which contains the script `pal2nal.pl`)

You should find instructions regarding downloading & installing these packages at the links above. Once you have these set up, please try the command once again.

Thank you!

**Comment by ABDULLAHGUJJAR** [comment]
Thanks for your reply.i am trying it.if I feel any other problem i can contact you through this email?

Sent from my iPhone

On 19 Aug 2017, at 12:17 AM, Vivek Krishnakumar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ABDULLAHGUJJAR<https://github.com/abdullahgujjar>,

From looking at the error message above, it would seem that your system is missing the following required packages/dependencies:

  *   PAML: http://abacus.gene.ucl.ac.uk/software/paml.html (which contains the binary, yn00)
  *   pal2nal: http://www.bork.embl.de/pal2nal/ (which contains the script pal2nal.pl)

You should find instructions regarding downloading & installing these packages at the links above. Once you have these set up, please try the command once again.

Thank you!

**Comment by vivekkrish** [comment]
Yes, you can continue to reply to this email and we will receive your messages.

**Comment by ABDULLAHGUJJAR** [comment]
muhammad abdullah has shared a OneDrive file with you. To view it, click the link below.


<https://1drv.ms/u/s!AhQGATZXTCspkSZFPcdFfFOIZlx6>
[https://r1.res.office365.com/owa/prem/images/dc-jpg_20.png]<https://1drv.ms/u/s!AhQGATZXTCspkSZFPcdFfFOIZlx6>

WechatIMG4.jpeg<https://1drv.ms/u/s!AhQGATZXTCspkSZFPcdFfFOIZlx6>




Hi dear, you can guide me.i have problem in making file PAML.( make -f Makefile).kindly guide me about this error.


________________________________
