### ISSUE TITLE
AttributeError: 'LayoutLine' object has no attribute 'color

### ISSUE THREAD

**Issue by mixle18** [tanghaibao/jcvi#616]
Hi, 
I am trying to run microsynteny And i am getting this issue with colour. Can you help?

(allmap) safflower2@safflower2:/media/safflower2/Data/megha/validation/synteny/data/pairwise$ python -m jcvi.graphics.karyotype seqids layout
[04:22:37] DEBUG    Load file `layout`                                                        base.py:34
           DEBUG    Load file `saf_chinese.bed`                                               base.py:34
[04:22:38] DEBUG    Load file `saf_du.bed`                                                    base.py:34
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/safflower2/anaconda3/envs/allmap/lib/python3.11/site-packages/jcvi/graphics/karyotype.py", line 469, in <module>
    main()
  File "/home/safflower2/anaconda3/envs/allmap/lib/python3.11/site-packages/jcvi/graphics/karyotype.py", line 447, in main
    Karyotype(
  File "/home/safflower2/anaconda3/envs/allmap/lib/python3.11/site-packages/jcvi/graphics/karyotype.py", line 350, in __init__
    layout = Layout(layoutfile, generank=generank, seed=seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/safflower2/anaconda3/envs/allmap/lib/python3.11/site-packages/jcvi/graphics/karyotype.py", line 87, in __init__
    self.assign_colors(seed=seed)
  File "/home/safflower2/anaconda3/envs/allmap/lib/python3.11/site-packages/jcvi/graphics/base.py", line 151, in assign_colors
    self.assign_array("color", colorset)
  File "/home/safflower2/anaconda3/envs/allmap/lib/python3.11/site-packages/jcvi/graphics/base.py", line 141, in assign_array
    if not getattr(x, attrib):
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'LayoutLine' object has no attribute 'color

**Comment by biopig** [comment]
You can have a try the parameter `--figsize=FIGSIZE`， for example  `--figsize=15x10`.
