### ISSUE TITLE
mscan-Pairwise synteny visualization

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [tanghaibao/jcvi#62]
As per your instruction,i have downloaded PAML: http://abacus.gene.ucl.ac.uk/software/paml.html (which contains the binary, yn00) pal2nal: http://www.bork.embl.de/pal2nal/ (which contains the script pal2nal.pl) but still its not working.i have this error.can you guide me.
```
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.graphics.dotplot grape.peach.anchors
13:47:50 [synteny] Assuming --qbed=grape.bed --sbed=peach.bed
13:47:50 [base] Load file `grape.bed`
13:47:50 [base] Load file `peach.bed`
13:47:51 [dotplot] Showing a random subset of 10000 data points (total 14695) for clarity.
13:47:51 [dotplot] xsize=26346 ysize=28701
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/dotplot.py", line 342, in <module>
    minfont=opts.minfont, palette=palette)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/dotplot.py", line 83, in dotplot_main
    minfont=minfont, palette=palette, chrlw=chrlw, title=title)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/dotplot.py", line 180, in dotplot
    th = TextHandler(fig)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/base.py", line 52, in __init__
    self.build_height_array(fig)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/base.py", line 66, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/base.py", line 58, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 446, in __init__
    usetex=usetex)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 526, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 152, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/textpath.py", line 305, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/matplotlib/dviread.py", line 868, in find_tex_file
    stderr=subprocess.PIPE)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/subprocess32.py", line 825, in __init__
    restore_signals, start_new_session)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/subprocess32.py", line 1574, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'kpsewhich'

appledeMacBook-Pro-3:Downloads Abdullah$ 
```

**Comment by vivekkrish** [comment]
Hi @ABDULLAHGUJJAR,

Looks like you've been able to install the `PAML` and `pal2nal` dependencies properly.

Now, the only issue remaining is that your Macbook does not have the TexLive package (which is required for the TeX typsetting system, e.g. LaTeX). On the Mac, you can install MacTex, which should be available for download here: https://www.tug.org/mactex/.

Once installed, please try running the `jcvi.graphics.dotplot` command once again.

Thank you!

--
Close #61 (as duplicate)

**Comment by ABDULLAHGUJJAR** [comment]
Macrosynteny visualization.i have installed mactex.now i want macrosynteny visualization.i found this error.but i have grape.bed file with data in my data list.i try many time with format changing of grape.bed file.
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.graphics.karyotype seqids layout
20:08:01 [base] Load file `layout`
20:08:01 [base] Load file `grape.bed\`
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 320, in <module>
    main()
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 308, in main
    Karyotype(fig, root, seqidsfile, layoutfile)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 259, in __init__
    layout = Layout(layoutfile, generank=generank)
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 81, in __init__
    generank=generank))
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 52, in __init__
    self.bed = Bed(args[7])
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/formats/bed.py", line 110, in __init__
    for line in must_open(filename):
  File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/formats/base.py", line 391, in must_open
    fp = open(filename, mode)
IOError: [Errno 2] No such file or directory: 'grape.bed\\'
appledeMacBook-Pro-3:Downloads Abdullah$

**Comment by vivekkrish** [comment]
Hi @ABDULLAHGUJJAR,

Looking at your updated message, it seems that you are now trying to run `jcvi.graphics.karyotype` (for macro-synteny visualization) instead of `jcvi.graphics.dotplot` (your original inquiry).

After installing PAML, pal2nal and MacTex, were you able to generate a dotplot successfully?

Now, in order to generate a macro-synteny visualization, please follow the documentation available on the wiki: https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)#macrosynteny-visualization, which describes the steps to generate the `seqids` and `layouts` files.

Looking at this latest error message `IOError: [Errno 2] No such file or directory: 'grape.bed\\'`, it would seem that your `layout` file is malformed. Could you please check to see the line endings of your file?

Thank you.

**Comment by vivekkrish** [comment]
@ABDULLAHGUJJAR, was this error resolved? I'm assuming yes, since you have opened a new issue (#65) regarding the `layouts` file.

Can we go ahead and close this issue?
