### ISSUE TITLE
jcvi.compara.catalog - 0 anchors issue

### ISSUE THREAD

**Issue by erika-r-moore** [tanghaibao/jcvi#622]
Hello!

I am trying to run jcvi.compara.catalog on two genomes (Acicarpha and Helianthus) but keep getting the "ValueError: A total of 0 anchor was found. Aborted" error:
```
(py37) [ermoore3@karen jcvi]$ python -m jcvi.compara.catalog ortholog Acicarpha Helianthus --no_strip_names
[11:45:44] DEBUG    File `Acicarpha.Helianthus.last` found. Computation skipped.                                   base.py:1380
           DEBUG    Assuming --qbed=Acicarpha.bed --sbed=Helianthus.bed                                          synteny.py:390
           DEBUG    Load file `Acicarpha.bed`                                                                        base.py:34
           DEBUG    Load file `Helianthus.bed`                                                                       base.py:34
[11:45:45] DEBUG    Load BLAST file `Acicarpha.Helianthus.last` (total 1163986 lines)                         blastfilter.py:47
           DEBUG    Load file `Acicarpha.Helianthus.last`                                                            base.py:34
[11:45:48] WARNING  g5457.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g46313.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g46313.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g44872.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g3545.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g25365.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g6290.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g48404.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g5849.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g6290.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g48404.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g6290.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g48404.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g48404.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g2448.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g2448.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g43773.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g31725.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g43317.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g42955.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g31725.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g42955.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g2536.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g2536.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g5457.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g2536.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g16230.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g5457.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g7799.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g11141.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g7799.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g7051.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g46846.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g28324.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g24727.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g28561.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g6701.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g2539.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g15372.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g9839.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g6701.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g17670.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g39913.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g5849.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g39913.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g25837.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g48404.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g14142.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g25837.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g48770.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g48404.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g20735.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g45921.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g6701.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g25379.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g39913.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g25837.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g48381.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g17250.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g47516.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g19864.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g44872.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g19909.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g19909.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g43430.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g5751.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g19909.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g19909.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g8789.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g43317.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g30744.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g30744.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g43769.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g33459.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g33459.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g42711.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g15358.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g15358.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g27568.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g41895.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g41895.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g20212.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g20212.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g38034.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g45541.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g18337.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g10971.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g29161.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g18337.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g22188.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g44966.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g29161.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g10971.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g30984.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g4049.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g10493.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g5457.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g5457.t1 not in Acicarpha.bed                                                             blastfilter.py:65
           WARNING  g31944.t1 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  g10493.t2 not in Acicarpha.bed                                                            blastfilter.py:65
           WARNING  too many warnings.. suppressed                                                            blastfilter.py:67
           DEBUG    running the cscore filter (cscore>=0.70) ..                                              blastfilter.py:108
           DEBUG    after filter (0->0) ..                                                                   blastfilter.py:111
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                        blastfilter.py:116
           DEBUG    after filter (0->0) ..                                                                   blastfilter.py:156
[11:45:49] DEBUG    Assuming --qbed=Acicarpha.bed --sbed=Helianthus.bed                                          synteny.py:390
           DEBUG    Load file `Acicarpha.bed`                                                                        base.py:34
           DEBUG    Load file `Helianthus.bed`                                                                       base.py:34
           DEBUG    Load file `Acicarpha.Helianthus.last.filtered`                                                   base.py:34
           DEBUG    A total of 0 BLAST imported from `Acicarpha.Helianthus.last.filtered`.                       synteny.py:278
           DEBUG    Chaining distance = 20                                                                      synteny.py:1794
           DEBUG    Load file `Acicarpha.Helianthus.anchors`                                                         base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.                                                     synteny.py:1371
Traceback (most recent call last):
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 963, in <module>
    main()
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/apps/base.py", line 136, in dispatch
    globals[action](sys.argv[2:])
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 730, in ortholog
    scan(dargs)
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1811, in scan
    summary([anchor_file])
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1372, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.
```

The installation instructions state that this is likely because LAST is not installed, but I am pretty certain it is. There are some warnings that go along with it, but I don't think they are influencing my issue (though please let me know if I am wrong).

I installed it initially by git cloning the GitLab repository -- git clone https://gitlab.com/mcfrith/last.git -- then added it to my path
```
(py37) [ermoore3@karen jcvi]$ export PATH=$PATH:/home/ermoore3/last/bin
(py37) [ermoore3@karen jcvi]$ export PATH=$PATH:/home/ermoore3/last/bin/lastdb
(py37) [ermoore3@karen jcvi]$ export PATH=$PATH:/home/ermoore3/last/bin/lastal
(py37) [ermoore3@karen jcvi]$ echo $PATH
:/home/ermoore3/miniconda2/envs/py37/bin:/home/ermoore3/miniconda2/condabin:/opt/apps/sratoolkit/3.0.7/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/openmpi/openmpi-1.4/bin:/home/ermoore3/.local/bin:/home/ermoore3/bin:/home/ermoore3/miniconda2/envs/py37/bin/:/home/ermoore3/miniconda2/envs/py37/bin/lastdb:/home/ermoore3/miniconda2/envs/py37/bin/lastal:/home/ermoore3/last/bin:/home/ermoore3/last/bin/lastdb:/home/ermoore3/last/bin/lastal
```

I then tried installing it by using bioconda in my conda environment (py37) -- conda install bioconda::last -- where you can see last installed
```
(py37) [ermoore3@karen jcvi]$ conda list
# packages in environment at /home/ermoore3/miniconda2/envs/py37:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    anaconda
_openmp_mutex             5.1                       1_gnu    anaconda
absl-py                   2.0.0                    pypi_0    pypi
argcomplete               3.1.2                    pypi_0    pypi
argh                      0.27.2                   pypi_0    pypi
biopython                 1.81                     pypi_0    pypi
boto3                     1.29.4                   pypi_0    pypi
botocore                  1.32.4                   pypi_0    pypi
brewer2mpl                1.4.1                    pypi_0    pypi
bx-python                 0.10.0                   pypi_0    pypi
c-ares                    1.19.1               h5eee18b_0
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17               pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
crossmap                  0.6.6                    pypi_0    pypi
curl                      8.2.1                h37d81fd_0
cycler                    0.11.0                   pypi_0    pypi
cython                    3.0.5                    pypi_0    pypi
deap                      1.4.1                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
ete3                      3.1.3                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
ftpretty                  0.4.0                    pypi_0    pypi
future                    0.18.2           py37h89c1867_5    conda-forge
gffutils                  0.12                     pypi_0    pypi
goatools                  1.3.11                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.2                   pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
jcvi                      1.3.8                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h568e23c_1
last                      874                  h2e03b76_4    bioconda
ld_impl_linux-64          2.38                 h1181459_1    anaconda
libcurl                   8.2.1                h91b91d3_0
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.4                h6a678d5_0    anaconda
libgcc-ng                 11.2.0               h1234567_1    anaconda
libgomp                   11.2.0               h1234567_1    anaconda
libnghttp2                1.52.0               ha637b67_1
libssh2                   1.10.0               h37d81fd_2
libstdcxx-ng              11.2.0               h1234567_1    anaconda
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
more-itertools            9.1.0                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    anaconda
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    anaconda
ortools                   9.5.2237                 pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
protobuf                  4.24.4                   pypi_0    pypi
pybedtools                0.9.1                    pypi_0    pypi
pybigwig                  0.3.22                   pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pyfaidx                   0.7.2.2                  pypi_0    pypi
pygments                  2.17.1                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pypdf2                    3.0.1                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
python                    3.7.16               h7a1cb2a_0    anaconda
python-dateutil           2.8.2                    pypi_0    pypi
python-graphviz           0.20.1                   pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2023.3.post1             pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    anaconda
requests                  2.31.0                   pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
s3transfer                0.7.0                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
simplejson                3.19.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    anaconda
statsmodels               0.13.5                   pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    anaconda
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0    anaconda
xlsxwriter                3.1.9                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    anaconda
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    anaconda
```

When I type "lastal --version" I get "lastal 1513" as an output. If I type "~/last/bin/lastal --version" to look at the git cloned version, I get "lastal 1526". Thus, it seems to be registering that lastal is available and usable, although jcvi is not.

I know this was a lot of information, but I would appreciate any help you can provide. I attached my associated bed and cds files if you want to look into those. 

Please let me know if you need anything else from me!

[Acicarpha.bed.gz](https://github.com/tanghaibao/jcvi/files/14042049/Acicarpha.bed.gz)
[Acicarpha.cds.gz](https://github.com/tanghaibao/jcvi/files/14042050/Acicarpha.cds.gz)
[Helianthus.bed.gz](https://github.com/tanghaibao/jcvi/files/14042051/Helianthus.bed.gz)
[Helianthus.cds.gz](https://github.com/tanghaibao/jcvi/files/14042052/Helianthus.cds.gz)

**Comment by tanghaibao** [comment]
@erika-r-moore 

Please make sure that the gene names match between the 4th column of the BED file and the names in the CDS file.

Currently you have something like `gene_0` in BED but `g1.t1` in CDS.

```console
$ gzcat Acicarpha.bed.gz | head
scaffold_1	114530	126059	gene_0	0	+
scaffold_1	128088	128364	gene_15	0	-
scaffold_1	204346	212332	gene_21	0	+
scaffold_1	242795	256147	gene_54	0	+
scaffold_1	347951	387785	gene_66	0	+
scaffold_1	432515	432863	gene_96	0	-
scaffold_1	432990	433632	gene_102	0	-
scaffold_1	467640	508247	gene_108	0	+
scaffold_1	513221	543906	gene_199	0	-
scaffold_1	609363	611952	gene_244	0	+

$ gzcat Acicarpha.cds.gz | head
>g1.t1
ATGATAATTTATCCAACTATAGAAACCTTTTGGGAAACGGACGGCGGCCATAGAGACTCC
CGTCCGCCGCTACGCCGACAGAGCAGGTCACtccgtcgtccgtcgtctgttcgccgtcgg
ccgactgtcgtccgtcctcagtccttctttctccgtcatccgtcgtcGCACAGAGCAGTG
ATGGATTGTAACCGAGAAGAGGCATTGAGGGCCAAAGAGATGGCAGAGAAGAAGATGGAG
AACAAAGACTTCTCTGGGGCTCTAAAGATTGCACAGAAGGCCCAACAGCTTTATCCTGAT
TTAGAAAACGTTTCACAAATGATTGTCGTTTGTGAAGTCCACTGCTCTGCCGAAAACAAA
ATCTACAATTCCACCACCGACAAAGACTGGTATAGTATCCTCAAAATCGAGCCTTCGGCT
GATGATTTGTCGATTAAAAAACAATACAGAAAGCTGGCTCTTGTACTTCATCCTGATAAA
AACAAGTTTTCTGGCTCTGCTGATGCCTTCAAGCTAATCGGTGAAGCTCAAAGAGTGCTT
```

**Comment by erika-r-moore** [comment]
Hello,

Thank you for the speedy response! I looked back at my files and my input gff3 and cds files do have matching gene names (e.g., g1.t1):
```
(py37) [ermoore3@karen braker]$ head Acicarpha_braker.cds
>g1.t1
ATGATAATTTATCCAACTATAGAAACCTTTTGGGAAACGGACGGCGGCCATAGAGACTCC
CGTCCGCCGCTACGCCGACAGAGCAGGTCACtccgtcgtccgtcgtctgttcgccgtcgg
ccgactgtcgtccgtcctcagtccttctttctccgtcatccgtcgtcGCACAGAGCAGTG
ATGGATTGTAACCGAGAAGAGGCATTGAGGGCCAAAGAGATGGCAGAGAAGAAGATGGAG
AACAAAGACTTCTCTGGGGCTCTAAAGATTGCACAGAAGGCCCAACAGCTTTATCCTGAT
TTAGAAAACGTTTCACAAATGATTGTCGTTTGTGAAGTCCACTGCTCTGCCGAAAACAAA
ATCTACAATTCCACCACCGACAAAGACTGGTATAGTATCCTCAAAATCGAGCCTTCGGCT
GATGATTTGTCGATTAAAAAACAATACAGAAAGCTGGCTCTTGTACTTCATCCTGATAAA
AACAAGTTTTCTGGCTCTGCTGATGCCTTCAAGCTAATCGGTGAAGCTCAAAGAGTGCTT
(py37) [ermoore3@karen braker]$ head Acicarpha_braker.gff3
scaffold_1      AUGUSTUS        gene    114531  126059  .       +       .       ID=g1;
scaffold_1      AUGUSTUS        mRNA    114531  126059  0.55    +       .       ID=g1.t1;Parent=g1;
scaffold_1      AUGUSTUS        start_codon     114531  114533  .       +       0       ID=g1.t1.start1;Parent=g1.t1;
scaffold_1      AUGUSTUS        CDS     114531  114574  0.63    +       0       ID=g1.t1.CDS1;Parent=g1.t1;
scaffold_1      AUGUSTUS        exon    114531  114574  .       +       .       ID=g1.t1.exon1;Parent=g1.t1;
scaffold_1      AUGUSTUS        intron  114575  114694  0.62    +       .       ID=g1.t1.intron1;Parent=g1.t1;
scaffold_1      AUGUSTUS        CDS     114695  114828  0.67    +       1       ID=g1.t1.CDS2;Parent=g1.t1;
scaffold_1      AUGUSTUS        exon    114695  114828  .       +       .       ID=g1.t1.exon2;Parent=g1.t1;
scaffold_1      AUGUSTUS        intron  114829  124146  0.99    +       .       ID=g1.t1.intron2;Parent=g1.t1;
scaffold_1      AUGUSTUS        CDS     124147  125738  0.63    +       2       ID=g1.t1.CDS3;Parent=g1.t1;
```

It seem that when I try to generate bed files using "jcvi.formats.gff bed" that the gene names change from "g1.t1" to the "gene_0", "gene_15", etc. I changed the key feature from "Name" to "ID" and it changed the gene names to "g1", not "g1.g1": 
```
(py37) [ermoore3@karen new]$ head Helianthus.bed
Ha412HOChr01    185     5412    g1      0       +
Ha412HOChr01    5443    34016   g2      0       +
Ha412HOChr01    188428  190485  g3      0       +
Ha412HOChr01    215402  230735  g4      0       +
Ha412HOChr01    230851  231877  g5      0       -
Ha412HOChr01    234857  239066  g6      0       -
Ha412HOChr01    246406  246887  g7      0       -
Ha412HOChr01    249819  253697  g8      0       +
Ha412HOChr01    263939  266842  g9      0       -
Ha412HOChr01    268130  271080  g10     0       -
```

Running "jcvi.compara.catalog" with this new bed file still gives me the original error. 

Do you have any suggestions on how to generate the bed file so the gene names remain the same?

The command I used to generate the above bed file is:
`python -m jcvi.formats.gff bed --key=ID Acicarpha_braker.gff3 -o Acicarpha.bed`

Thanks!

**Comment by tanghaibao** [comment]
@erika-r-moore 

So there are a few options to pay attention to for the GFF to BED conversion script. You ran:

```console
python -m jcvi.formats.gff bed --key=ID Acicarpha_braker.gff3 -o Acicarpha.bed
```

You'd need to test this, but I think you need to add `--type=mRNA` option. The default for option `--type` is gene, so its grabbing the GFF3 lines that has type `gene` and then extract the `ID` (`--key`) from that line. I saw that doing it this way, we get names like `g1`, `g2` where in your CDS you have `g1.t1`, `g2.t2` etc. Adding the `--type=mRNA` might get you the correct names.

**Comment by erika-r-moore** [comment]
It worked when I added --type=mRNA! Thank you so much for your help on this!

**Comment by erika-r-moore** [comment]
Hello, I was curious if JCVI can generate anchor files with transcriptome data? 

I have a dataset of transcriptome assemblies (generated with Trinity) that I have converted to cds and gff3 files with TransDecoder. I then treated the cds and gff3 files like genome annotation files to use as input in JCVI. However, I get a similar error to this issue but do not know how to solve it as I made sure that my bed and cds file names are the same. 
```
(py37) [ermoore3@karen jcvi]$ head Aci_ML_Trinity.bed
TRINITY_DN0_c0_g1_i1    0       2659    TRINITY_DN0_c0_g1_i1.p1 0       +
TRINITY_DN0_c0_g1_i2    0       2243    TRINITY_DN0_c0_g1_i2.p1 0       +
TRINITY_DN0_c0_g1_i3    0       1780    TRINITY_DN0_c0_g1_i3.p1 0       +
TRINITY_DN0_c0_g1_i4    0       2158    TRINITY_DN0_c0_g1_i4.p1 0       +
TRINITY_DN0_c0_g1_i5    0       2240    TRINITY_DN0_c0_g1_i5.p1 0       +
TRINITY_DN0_c0_g1_i5    0       2240    TRINITY_DN0_c0_g1_i5.p2 0       +
TRINITY_DN0_c0_g1_i6    0       1279    TRINITY_DN0_c0_g1_i6.p1 0       +
TRINITY_DN0_c0_g1_i7    0       1654    TRINITY_DN0_c0_g1_i7.p1 0       +
TRINITY_DN0_c0_g1_i8    0       1085    TRINITY_DN0_c0_g1_i8.p1 0       +
TRINITY_DN0_c0_g1_i9    0       1865    TRINITY_DN0_c0_g1_i9.p1 0       +
(py37) [ermoore3@karen jcvi]$ head Aci_ML_Trinity.cds
>TRINITY_DN0_c0_g1_i1.p1
ATGGCCACCTCTTTCTTTTCAGGACTAAACTTACCATCTGATGACTCTGGCTCTGGCTCT
GGTTCATCCTCTAGCTATAATGGTCACTCACAACCTGAAGTTGTTACCATGAGTAAAGTA
GCAGGGGATCAACTATACACATACCCGTCTCACGTGAATGCGGCAAGCTTTCTATCCATT
AAGTTGTCAGGAATTGACAATTTCACCCAATGGCGAGAACAATTGATGTGCCTTCTAGAT
AGCCATGATATGCTCGGTTTCATTGATGGAGAATCCGAAGACCCCGAGGCCAAATCCCGA
GAATGGAGAAGATCAGATATGCTTGTGAAAGGATGGATATTAGGTTCTCTAAGTGAAAAT
GTTGTCACCACTGTTGTCGGCCTGCCCACTGCAAACCATGTTTGGAAGAGGCTAGAATTT
GCTTACCAACCTCGTCAAAGGATGGATCCCATGACCACAACGACCATCGAAAAAGATCGC
ACGGAGCATTTATCATTGTATAGAGCTTGTTTGGAGGGGATATGGGAGAAAGCCCAAGAA
```


The error I am getting:
```
(py37) [ermoore3@karen jcvi]$ python -m jcvi.compara.catalog ortholog Aci_ML_Trinity Aci_ML_Trinity --no_strip_names
[15:33:15] DEBUG    File `Aci_ML_Trinity.Aci_ML_Trinity.last` found. Computation skipped.                         base.py:1380
           DEBUG    File `Aci_ML_Trinity.Aci_ML_Trinity.last.P98L0.inverse` found. Computation skipped.           base.py:1380
           DEBUG    File `Aci_ML_Trinity.Aci_ML_Trinity.last.P98L0.inverse.filtered` found. Computation skipped.  base.py:1380
           DEBUG    Assuming --qbed=Aci_ML_Trinity.bed --sbed=Aci_ML_Trinity.bed                                synteny.py:390
           DEBUG    Looks like self-self comparison.                                                            synteny.py:403
           DEBUG    Load file `Aci_ML_Trinity.bed`                                                                  base.py:34
[15:33:16] DEBUG    Load file `Aci_ML_Trinity.bed`                                                                  base.py:34
           DEBUG    Load file `Aci_ML_Trinity.Aci_ML_Trinity.last.P98L0.inverse.filtered`                           base.py:34
           DEBUG    A total of 27868 BLAST imported from                                                        synteny.py:278
                    `Aci_ML_Trinity.Aci_ML_Trinity.last.P98L0.inverse.filtered`.
           DEBUG    Chaining distance = 20                                                                     synteny.py:1794
           DEBUG    Load file `Aci_ML_Trinity.Aci_ML_Trinity.anchors`                                               base.py:34
           DEBUG    A total of 0 anchor was found. Aborted.                                                    synteny.py:1371
Traceback (most recent call last):
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 963, in <module>
    main()
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/apps/base.py", line 136, in dispatch
    globals[action](sys.argv[2:])
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/catalog.py", line 730, in ortholog
    scan(dargs)
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1811, in scan
    summary([anchor_file])
  File "/home/ermoore3/miniconda2/envs/py37/lib/python3.7/site-packages/jcvi/compara/synteny.py", line 1372, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.
```

Therefore, I am curious if this error is from the underlying data being transcriptomic instead of genomic. Otherwise, could you provide some advice as to why this error may be coming up now? Please let me know if you need any clarifications!
