### ISSUE TITLE
Macrosynteny visualization

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [tanghaibao/jcvi#63]
Macrosynteny visualization.i have installed mactex.now i want macrosynteny visualization.i found this error.but i have grape.bed file with data in my data list.i try many time with format changing of grape.bed file.
appledeMacBook-Pro-3:Downloads Abdullah$ python -m jcvi.graphics.karyotype seqids layout
20:08:01 [base] Load file layout
20:08:01 [base] Load file grape.bed\
Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 320, in 
main()
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 308, in main
Karyotype(fig, root, seqidsfile, layoutfile)
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 259, in init
layout = Layout(layoutfile, generank=generank)
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 81, in init
generank=generank))
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/graphics/karyotype.py", line 52, in init
self.bed = Bed(args[7])
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/formats/bed.py", line 110, in init
for line in must_open(filename):
File "/Users/Abdullah/Library/Python/2.7/lib/python/site-packages/jcvi/formats/base.py", line 391, in must_open
fp = open(filename, mode)
IOError: [Errno 2] No such file or directory: 'grape.bed\'
appledeMacBook-Pro-3:Downloads Abdullah$

**Comment by ABDULLAHGUJJAR** [comment]
THank You so much @tanghaibao @vivekkrish for you cooperation and guidance.i am really thankful @vivekkrish.

**Comment by vivekkrish** [comment]
You are welcome!

Is this error still persisting? If not, please continue the discussion in #65 and close the current issue.

**Comment by ABDULLAHGUJJAR** [comment]
Now i have only #65 issue,i have close other issue.kindly help me in this issue i want add more chromosomes in top and bottom for microsynteny.

Sent from my iPhone

On 6 Sep 2017, at 2:55 AM, Vivek Krishnakumar <notifications@github.com<mailto:notifications@github.com>> wrote:


You are welcome!

Is this error still persisting? If not, please continue the discussion in #65<https://github.com/tanghaibao/jcvi/issues/65> and close the current issue.
