### ISSUE TITLE
Qusetion about Microsynteny

### ISSUE THREAD

**Issue by Toney823** [tanghaibao/jcvi#645]
Hi Dr. Tang, 

When I was doing the microsynteny of my assembly, I saw that the first column of the block file was unique in its IDs, which will draw a bezier curve from one gene on the reference to another gene on the query. But, is there any chance I can draw a curve from one gene on the reference to two genes on the query or even more?

All the best,
Xikai Yu

**Comment by Toney823** [comment]
The genes on the query were a set of tandem repeat genes, so I can`t split the query into muti fragments.  
Also, when I was trying to simply triple the gene on the reference like this:  
  
  
g1	.
r*g2    Cspi12441.mRNA1
r*g2    Cspi12440.mRNA1
r*g2    *Cspi12439.mRNA1
g3    .
  
  
An error came out:
Traceback (most recent call last):
  File "/data0/stu_yuxikai/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data0/stu_yuxikai/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data0/stu_yuxikai/miniconda3/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 651, in <module>
    main()
  File "/data0/stu_yuxikai/miniconda3/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 625, in main
    Synteny(
  File "/data0/stu_yuxikai/miniconda3/lib/python3.9/site-packages/jcvi/graphics/synteny.py", line 466, in __init__
    a, b = gg[(i, ga)], gg[(j, gb)]
KeyError: (1, 'r*Cspi12441.mRNA1')

**Comment by Toney823** [comment]
Never mind, I just simply triple this g2 from
g2    1    2
to
g2_0    1    2  
g2_1    1    2  
g2_2    1    2  
problem solved :)
