### ISSUE TITLE
python3 -m jcvi.compara.catalog ortholog这步报错

### ISSUE THREAD

**Issue by Sherry520** [tanghaibao/jcvi#679]
您好，我分析共线性这步报错了
## 我的命令：
带--no_strip_names的也试了，一样的错误。不设--cscore的也试了
`python3 -m jcvi.compara.catalog ortholog Zm-CML103-REFERENCE-NAM-1_0 Zm-B97-REFERENCE-NAM-1_0 --cscore=.99`
## 报错：
[06/14/24 09:52:56] DEBUG    File `Zm-CML103-REFERENCE-NAM-1_0.Zm-B97-REFERENCE-NAM-1_0.last` found. Computation skipped.                                                                                                        base.py:1382
                    DEBUG    Assuming --qbed=Zm-CML103-REFERENCE-NAM-1_0.bed --sbed=Zm-B97-REFERENCE-NAM-1_0.bed                                                                                                               synteny.py:390
                    DEBUG    Load file `Zm-CML103-REFERENCE-NAM-1_0.bed`                                                                                                                                                           base.py:36
                    DEBUG    Load file `Zm-B97-REFERENCE-NAM-1_0.bed`                                                                                                                                                              base.py:36
                    DEBUG    Load BLAST file `Zm-CML103-REFERENCE-NAM-1_0.Zm-B97-REFERENCE-NAM-1_0.last` (total 5 lines)                                                                                                    blastfilter.py:45
                    DEBUG    Load file `Zm-CML103-REFERENCE-NAM-1_0.Zm-B97-REFERENCE-NAM-1_0.last`                                                                                                                                 base.py:36
                    WARNING  chr10_69353227-69357058:. not in Zm-CML103-REFERENCE-NAM-1_0.bed                                                                                                                               blastfilter.py:64
                    WARNING  chr10_69353227-69357058:. not in Zm-CML103-REFERENCE-NAM-1_0.bed                                                                                                                               blastfilter.py:64
                    WARNING  chr10_69353227-69357058:. not in Zm-CML103-REFERENCE-NAM-1_0.bed                                                                                                                               blastfilter.py:64
                    WARNING  chr10_69353227-69357058:. not in Zm-CML103-REFERENCE-NAM-1_0.bed                                                                                                                               blastfilter.py:64
                    WARNING  chr10_69353227-69357058:. not in Zm-CML103-REFERENCE-NAM-1_0.bed                                                                                                                               blastfilter.py:64
                    DEBUG    running the cscore filter (cscore>=0.99) ..                                                                                                                                                   blastfilter.py:107
                    DEBUG    after filter (0->0) ..                                                                                                                                                                        blastfilter.py:109
                    DEBUG    running the local dups filter (tandem_Nmax=10) ..                                                                                                                                             blastfilter.py:114
                    DEBUG    after filter (0->0) ..                                                                                                                                                                        blastfilter.py:154
                    DEBUG    Assuming --qbed=Zm-CML103-REFERENCE-NAM-1_0.bed --sbed=Zm-B97-REFERENCE-NAM-1_0.bed                                                                                                               synteny.py:390
                    DEBUG    Load file `Zm-CML103-REFERENCE-NAM-1_0.bed`                                                                                                                                                           base.py:36
                    DEBUG    Load file `Zm-B97-REFERENCE-NAM-1_0.bed`                                                                                                                                                              base.py:36
                    DEBUG    Load file `Zm-CML103-REFERENCE-NAM-1_0.Zm-B97-REFERENCE-NAM-1_0.last.filtered`                                                                                                                        base.py:36
                    DEBUG    A total of 0 BLAST imported from `Zm-CML103-REFERENCE-NAM-1_0.Zm-B97-REFERENCE-NAM-1_0.last.filtered`.                                                                                            synteny.py:277
                    DEBUG    Chaining distance = 20                                                                                                                                                                           synteny.py:1794
                    DEBUG    Load file `Zm-CML103-REFERENCE-NAM-1_0.Zm-B97-REFERENCE-NAM-1_0.anchors`                                                                                                                              base.py:36
                    DEBUG    A total of 0 anchor was found. Aborted.                                                                                                                                                          synteny.py:1371
Traceback (most recent call last):
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 742, in ortholog
    scan(dargs)
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 1811, in scan
    summary([anchor_file])
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 1372, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gyh/miniconda3/envs/jcvi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gyh/miniconda3/envs/jcvi/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 982, in <module>
    main()
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 88, in main
    p.dispatch(globals())
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/apps/base.py", line 131, in dispatch
    globals[action](sys.argv[2:])
  File "/home/gyh/.local/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 749, in ortholog
    raise ValueError(e) from e
ValueError: A total of 0 anchor was found. Aborted.

## 这是我的bed文件
` more Zm-CML103-REFERENCE-NAM-1_0.bed`
`chr10   69353226        69357058        Zm-CML103-REFERENCE-NAM-1.0`
## 这是我的cds文件：
`more Zm-CML103-REFERENCE-NAM-1_0.cds`
![image](https://github.com/tanghaibao/jcvi/assets/22561797/4f8607b5-bc84-45cf-b20e-4d699e48a779)

**Comment by Sherry520** [comment]
cds的序列名字应该是什么格式才符合标准，我的cds文件是用seqkit工具从参考fa文件提取的；bed文件是0-base的，到了cds文件，起始坐标是应该比bed起始坐标加1

**Comment by tanghaibao** [comment]
@Sherry520 

cds序列名称必须和 bed文件第四列出现的名字相匹配。
用你的例子，`Zm-CML103-REFERENCE-NAM-1-0`就可以了，不要前面的那一串。
