### ISSUE TITLE
Genomic landscape error

### ISSUE THREAD

**Issue by lkulandaivelu** [tanghaibao/jcvi#686]
Dear colleague,

We do not manage to perform the genome landscape analysis on the Arabidopsis exemple that you provided.

We tried on two different HPC.

Here is the error message:

[gdroc@core-login1 jcvi]$ singularity exec jcvi.sif python -m jcvi.graphics.landscape stack TAIR10_chr_all.fas     --stacks=Repeats     --window=250000     --shift=50000
[07/08/24 10:08:31] INFO     `latex` not found. latex use is disabled.                                                                                                                                                                          base.py:614
                    INFO     `lp` not found. latex use is disabled.                                                                                                                                                                             base.py:616
                    INFO     Set text.usetex=False. Font styles may be inconsistent.                                                                                                                                                            base.py:453
                    DEBUG    Line/stack-plot options: window=250000 shift=50000 subtract=None                                                                                                                                              landscape.py:567
                    DEBUG    Load file `Repeats.bed.50000.span.bins`                                                                                                                                                                             base.py:36
                    DEBUG    Load file `TAIR10_chr_all.fas.sizes`                                                                                                                                                                                base.py:36
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/jcvi/graphics/landscape.py", line 1221, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/jcvi/graphics/landscape.py", line 139, in main
    p.dispatch(globals())
  File "/usr/local/lib/python3.8/site-packages/jcvi/apps/base.py", line 131, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python3.8/site-packages/jcvi/graphics/landscape.py", line 1201, in stack
    draw_stacks(
  File "/usr/local/lib/python3.8/site-packages/jcvi/graphics/landscape.py", line 1147, in draw_stacks
    stackplot(ax, binfiles, nbins, palette, chr, window, shift)
  File "/usr/local/lib/python3.8/site-packages/jcvi/graphics/landscape.py", line 1089, in stackplot
    m += s
ValueError: operands could not be broadcast together with shapes (4,) (5,) (4,)

Thanking you in advance for your help

Letizia Kulandaivelu

**Comment by tanghaibao** [comment]
@lkulandaivelu 

This is a bug that I failed to spot. Many thanks for reporting it. 
It turns out ChrC (organelle) in the input genome has a length less than 250000, leading to the error.

This has been fixed in the commit above and new version.

Haibao
