### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by jailynai** [tanghaibao/jcvi#693]
$ python -m jcvi.assembly.hic bam2mat HiC.sort.bam 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/lulu/miniconda3/envs/mamba/lib/python3.11/site-packages/jcvi/assembly/hic.py", line 1772, in <module>
    main()
  File "/Users/lulu/miniconda3/envs/mamba/lib/python3.11/site-packages/jcvi/assembly/hic.py", line 578, in main
    p.dispatch(globals())
  File "/Users/lulu/miniconda3/envs/mamba/lib/python3.11/site-packages/jcvi/apps/base.py", line 131, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/lulu/miniconda3/envs/mamba/lib/python3.11/site-packages/jcvi/assembly/hic.py", line 964, in bam2mat
    if op.exists(opts.seqids)
       ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by tanghaibao** [comment]
@jallynai

Thanks for reporting the bug. I just committed a patch (and more tests).

Haibao
