### ISSUE TITLE
Synteny Pattern 

### ISSUE THREAD

**Issue by tamim07** [tanghaibao/jcvi#707]
Hi, I am trying to identify the syntenic pattern. I have three genomes to compare one is diploid A (2x), B- hexaploid(6x) and C- allododecaploid (12x).  The results I am getting A-B (1:4) instead of 1:3, A-C(1:6). and B-C (2:2) instead of 2:3 while giving the parameter --no_strip_names --cscore=.99. I have attached the the figures and here is my example commands:

python -m jcvi.compara.catalog ortholog A B --no_strip_names --cscore=.99

python -m jcvi.compara.synteny depth --histogram A.B.anchors
 
[A-B.pdf](https://github.com/user-attachments/files/17028809/A-B.pdf)
[A-C.depth.pdf](https://github.com/user-attachments/files/17028810/A-C.depth.pdf)
[A-C.pdf](https://github.com/user-attachments/files/17028812/A-C.pdf)
[B_C.depth.pdf](https://github.com/user-attachments/files/17028813/B_C.depth.pdf)
[B_C.pdf](https://github.com/user-attachments/files/17028814/B_C.pdf)
[A-B.depth.pdf](https://github.com/user-attachments/files/17028815/A-B.depth.pdf)

Could you please help to get the right pattern? Thanks

**Comment by tanghaibao** [comment]
@tamim07 

Seems complicated. Please also also send results with `--cscore=0.7` and I'll take a look.

**Comment by tamim07** [comment]
Thanks for your quick reply. This become more compliocated while runing in default programme A-B = 1:4 (instead of 1:3), A-C = 1:7 (instead of 1:6) and B-C = 4:6 (instead of 2:3). However, I have managed to generate microsynteny with i=3 and i=6 for B and C blocks reference with A.  Thanks

[B-C_default.pdf](https://github.com/user-attachments/files/17035390/B-C_default.pdf)
[Microsynteny_B_i3_C_i6_blocks.pdf](https://github.com/user-attachments/files/17035391/Microsynteny_B_i3_C_i6_blocks.pdf)
[A-B_default.depth.pdf](https://github.com/user-attachments/files/17035392/A-B_default.depth.pdf)
[A-B_default.pdf](https://github.com/user-attachments/files/17035393/A-B_default.pdf)
[A-C_default.depth.pdf](https://github.com/user-attachments/files/17035394/A-C_default.depth.pdf)
[A-C_default.pdf](https://github.com/user-attachments/files/17035395/A-C_default.pdf)
[B-C_default.depth.pdf](https://github.com/user-attachments/files/17035396/B-C_default.depth.pdf)

**Comment by tanghaibao** [comment]
@tamim07 

Thanks.
Somehow the `A-B_default.pdf` is the same as `A-B.pdf` (look at the number of gene pairs at the top). Same with `A-C_default.pdf` vs `A-C.pdf`. `B-C` is good.

**Comment by tamim07** [comment]
Yes. it is. Any suggestion from your end? Any parameter to play with? Thanks

**Comment by tanghaibao** [comment]
Can you double check `A-B_default` and `A-C_default`? I find it unusual to have exactly same gene pairs when filtering with `0.99` vs `0.7 (default)`.

**Comment by tanghaibao** [comment]
From the results you send me:

1. Roughly A:B:C = 1:4:6, which means that that A is 2x, B is 8x, C is 12x. (For this pattern, you use the `default` cscore setting).
2. The `0.99` cscore is setting instead shows only *reciprocal best match*. This is useful to check subgenomes that are closer. The reason `B-C` is so different from `B-C_default` is that they share some subgenomes. Just as an example, 8x is AAAAAABB,  12x is AAAAAACCCCCC (here the A/B/C are subgenomes), then the pattern will look very different.

My suggestions:
1. Make sure you run cscore `default` and `0.99` separately. See my comments above, better use separate folders to avoid getting confused with cached results. It's unlikely that these results are the same, as currently seen.
2. Once we have the full results (3 from `default` and 3 from `0.99`, with different results), we'll then try to interpret.

**Comment by tamim07** [comment]
Thanks for your suggestion. I have re run the programme. The default results shows A:B = 1:4 (39,769 pair), A:C=1:7 (47,263 pair) and B:C = 4:6 (121,709 pairs), on the otherhand, the cs0.99 results showed A:B = 1:4 (20,213 pair), A:C=1:6 (19,697 pair) and B:C = 2:2 (32,289 pairs)
The results varies with previous analysis probably due to the different version of A genomes.

[A_B_default.pdf](https://github.com/user-attachments/files/17067083/A_B_default.pdf)
[A-C_cs0.99.depth.pdf](https://github.com/user-attachments/files/17067084/A-C_cs0.99.depth.pdf)
[A-C_cs0.99.pdf](https://github.com/user-attachments/files/17067085/A-C_cs0.99.pdf)
[A-C_default.depth.pdf](https://github.com/user-attachments/files/17067086/A-C_default.depth.pdf)
[A-C_default.pdf](https://github.com/user-attachments/files/17067087/A-C_default.pdf)
[B-C_cs0.99.depth.pdf](https://github.com/user-attachments/files/17067088/B-C_cs0.99.depth.pdf)
[B-C_cs0.99.pdf](https://github.com/user-attachments/files/17067089/B-C_cs0.99.pdf)
[B-C_default.depth.pdf](https://github.com/user-attachments/files/17067090/B-C_default.depth.pdf)
[B-C_default.pdf](https://github.com/user-attachments/files/17067091/B-C_default.pdf)
[A_B_cs0.99.depth.pdf](https://github.com/user-attachments/files/17067092/A_B_cs0.99.depth.pdf)
[A_B_cs0.99.pdf](https://github.com/user-attachments/files/17067093/A_B_cs0.99.pdf)
[A_B_default.depth.pdf](https://github.com/user-attachments/files/17067094/A_B_default.depth.pdf)

I do appreciate your help. Thanks

**Comment by tanghaibao** [comment]
@tamim07 

The 1:4:6 pattern is very clear - which means A:B:C=2x:8x:12x. Also the 4x and 6x regions are equally distant to the diploid. This is because the pattern of 1:4 and 1:6 remains even when filtering down to reciprocal best (cscore=0.99).

At least this part is clear.

What's interesting is the pattern between B:C. You see B:C=4:6 in the default setting, which agrees with the paragraph above, that is fine. However, when filtering down to reciprocal best, some of the region pairs are closer among the 4x6 grid. This suggests that there are some shared sub-genomes in B and C.

This becomes a more complicated research problem and goes beyond what I can help here. What I can suggest as next step is that you should calculate Ks for all gene pairs, plot the distributions of the Ks values. More importantly, with the Ks values you can repeat the dot plot again, with different colors of Ks, using the following command.

```console
python -m jcvi.graphics.dotplot B-C_default.ks
```

This visualize the anchorfile in a dotplot. `B-C_default.ks` contains two columns
indicating gene pairs, followed by an optional column (e.g. Ks value).

**Comment by tamim07** [comment]
Hi there,
Thanks for your suggestion.  Here is the kaks_plots between B_C.
 
[B_C_default_kaks.pdf](https://github.com/user-attachments/files/17111434/B_C_default_kaks.pdf)

This puts me in a challenging situation. The literature indicates that B is hexaploid (6x), and C is an allododecaploid (12x). C is the result of genome duplication of D (6x), which is a hybrid of B (6x) and E (6x). I know it sounds complicated. I’ve included a reference figure where C represents S. anglica (12x), B is S. alterniflora (6x), and A is the distantly related species O. thomaeum (2x). I'm struggling to piece together how to solve this.

![1-s2 0-S1055790317301628-gr2](https://github.com/user-attachments/assets/d14aefe2-caf8-4b15-99f4-571cba64783a)
https://www.sciencedirect.com/science/article/pii/S1055790317301628#b0355

I am wondering, if can I make a plot using quota commands. 
python -m jcvi.compara.synteny depth --histogram --xmax 3 --quota 1:3 A.B.anchors 

Would you please share your thoughts? 

Finally, I want to show a figure like this. 

[blocks.pdf](https://github.com/user-attachments/files/17113731/blocks.pdf)

I do appreciate your help. Thanks

**Comment by tanghaibao** [comment]
I do not see the color differences in the ks plot sent. It looks like we need to add the option to show the colormap.

```
python -m jcvi.graphics.dotplot B-C_default.ks --cmaptext "Ks"
```

I understand your situation. You can always screen with quota in all the comparisons:

```
python -m jcvi.compara.catalog ortholog A B --quota 1:3
```

However, this will leave some chromosomes in B unaccounted for. Try this command, and see for yourself. We can review the situation of A:B later when you have the Ks colors overlaid on the dotplot (above), but at this point it does look like 1:4, which brings B at 8x.

You have the freedom to do what you want. My past experience is to do the right thing. Check genome sizes, or chromosome karyotype, flow cytometry. Sometimes past knowledge may not be accurate.

**Comment by tamim07** [comment]
Hi,
I got this error:
python -m jcvi.graphics.dotplot --qbed Salterniflora.bed --sbed Sanglica.bed Salterniflora_Sanglica_kaks --cmaptext "ks"

[09/24/24 19:12:02] DEBUG    Load file `Salterniflora.bed`                                                                                                    base.py:36
[09/24/24 19:12:03] DEBUG    Load file `Sanglica.bed`                                                                                                         base.py:36
[09/24/24 19:12:04] DEBUG    Capping values within [0.0, 2.0]                                                                                             dotplot.py:286
Traceback (most recent call last):
  File "/gpfs/home/evz22uzu/.conda/envs/jcvi_new/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfs/home/evz22uzu/.conda/envs/jcvi_new/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/home/evz22uzu/.conda/envs/jcvi_new/lib/python3.8/site-packages/jcvi/graphics/dotplot.py", line 549, in <module>
    dotplot_main(sys.argv[1:])
  File "/gpfs/home/evz22uzu/.conda/envs/jcvi_new/lib/python3.8/site-packages/jcvi/graphics/dotplot.py", line 518, in dotplot_main
    dotplot(
  File "/gpfs/home/evz22uzu/.conda/envs/jcvi_new/lib/python3.8/site-packages/jcvi/graphics/dotplot.py", line 332, in dotplot
    x, y, c = zip(*data)
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by tanghaibao** [comment]
@tamim07 

You are getting very deep use of the JCVI package ;-) so it can get frustrating for you to know how to use these functions.

1. For ks calculation, it's possible to do it with JCVI, however unfortunately I have not added a tutorial yet. You need to compute these somehow and add a 3rd column with the Ks values in the `.anchors` file.

2. After you run with `--quota 1:4`, look for a file that looks like `A.B.lifted.1x4.anchors` and redo the dotplot:

```
python -m jcvi.graphics.dotplot A.B.lifted.1x4.anchors
```

**Comment by tamim07** [comment]
Apology for delayed response. Here is the two figures: 

[A-B.lifted.1x4.pdf](https://github.com/user-attachments/files/17194959/A-B.lifted.1x4.pdf)
[A-B_kaks.pdf](https://github.com/user-attachments/files/17194961/A-B_kaks.pdf)

Thanks

**Comment by tamim07** [comment]
Hi Haibao,


Thanks for your reply. I got a recent paper, the karyotyping showing B is
allotetraploid which means our analysis was correct A:B:C (1:4:6). It
solves my current issues.

However, I can't explain the Ks distribution.
Again, according to the literature C is evolved derivatives of B shown
earlier figures. But the Ks distribution showing 2 recent WGD events
occurred in B, however, 1 recent and one anicient WGD occurred in C.
Therefore I can't explain how C becomes 12x coming from 8x and how the
duplication event occurred in B that are not present in C? Here I have
attched the histogram, Salt - means B and Sang- means C.
