### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by lindonghuia** [tanghaibao/jcvi#709]
作者您好，我在运行 python -m jcvi.graphics.karyotype seqids  layout出现了这样的报错
[10/12/24 16:34:06] DEBUG    Load file `layout`                                                                                              base.py:36
                    DEBUG    Load file `xihulu.bed`                                                                                          base.py:36
                    DEBUG    Load file `tiangua.bed`                                                                                         base.py:36
Traceback (most recent call last):
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/karyotype.py", line 474, in <module>
    main(sys.argv[1:])
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/karyotype.py", line 454, in main
    Karyotype(
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/karyotype.py", line 365, in __init__
    t = layout[i]
IndexError: list index out of range

以下是我的latout文件
(jcvi) lindonghui@swzx05:/data05/lindonghui/work/06_xihulu/04_mcscan$ more layout
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .1,    .8,       0,      , xihulu, top, xihulu.bed, center
 .4,     .1,    .8,       0,      , tiangua, top, tiangua.bed, center
# edges
e, 0, 1, xihulu.tiangua.anchors.simple
(jcvi) lindonghui@swzx05:/data05/lindonghui/work/06_xihulu/04_mcscan$ more seqids
Chr01,Chr02,Chr03,Chr04,Chr05
GWHDTVT00000001,GWHDTVT00000002,GWHDTVT00000003,GWHDTVT00000004

此外，我在运行前一步时出现了这样的错误

(jcvi) lindonghui@swzx05:/data05/lindonghui/work/06_xihulu/04_mcscan$ python -m jcvi.compara.catalog     ortholog         xihulu  tiangua         --no_strip_names
[10/12/24 16:36:18] DEBUG    File `xihulu.tiangua.last` found. Computation skipped.                                                        base.py:1382
                    DEBUG    File `xihulu.tiangua.last.filtered` found. Computation skipped.                                               base.py:1382
                    DEBUG    File `xihulu.tiangua.lifted.anchors` found. Computation skipped.                                              base.py:1382
                    DEBUG    Assuming --qbed=xihulu.bed --sbed=tiangua.bed                                                               synteny.py:390
                    DEBUG    Load file `xihulu.bed`                                                                                          base.py:36
                    DEBUG    Load file `tiangua.bed`                                                                                         base.py:36
                    DEBUG    Showing a random subset of 10000 data points (total 21553) for clarity.                                     dotplot.py:233
[10/12/24 16:36:19] DEBUG    xsize=27627 ysize=24499                                                                                     dotplot.py:349
Traceback (most recent call last):
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 982, in <module>
    main()
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 88, in main
    p.dispatch(globals())
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/apps/base.py", line 131, in dispatch
    globals[action](sys.argv[2:])
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 768, in ortholog
    dotplot_main(dargs)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/dotplot.py", line 518, in dotplot_main
    dotplot(
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/dotplot.py", line 352, in dotplot
    xlim, _ = plot_breaks_and_labels(
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/dotplot.py", line 159, in plot_breaks_and_labels
    th = TextHandler(fig, usetex=usetex)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/base.py", line 94, in __init__
    self.build_height_array(fig, usetex=usetex)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/base.py", line 110, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i, usetex=usetex)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/base.py", line 102, in get_text_width_height
    tp = mpl.textpath.TextPath((0, 0), txt, size=size, usetex=usetex)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/matplotlib/textpath.py", line 355, in __init__
    *text_to_path.get_text_path(prop, s, ismath=ismath),
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/matplotlib/textpath.py", line 109, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/matplotlib/textpath.py", line 219, in get_glyphs_tex
    dvifile = TexManager().make_dvi(s, self.FONT_SCALE)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/matplotlib/texmanager.py", line 295, in make_dvi
    cls._run_checked_subprocess(
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/matplotlib/texmanager.py", line 258, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: latex was not able to process the following string:
b'chr01'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error --output-directory=tmpuc6_ory2 c86bca16e72db77513e4bcf36d49be7d.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=latex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt latex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/share/tlpkg /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/share/texmf-dist/scripts/texlive /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/perl5/site_perl/5.22.0 /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/perl5/5.22.0/x86_64-linux-thread-multi /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/perl5/5.22.0 .) at /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /data05/lindonghui/software/mamba/mambaforge/envs/jcvi/bin/mktexfmt line 25.
I can't find the format file `latex.fmt'!
但是除了pdf其他文件都输出了，请问这是否影响后续分析
感谢！！

**Comment by zhangyixing3** [comment]
你生成图表时，报错的原因可能是因为缺少 LaTeX。你可以在运行命令时添加 `--notex` 参数，或者在服务器上安装 LaTeX。
普通用户在服务器上安装 LaTeX，可以参考这篇文章：[如何在不使用 root 权限下安装 LaTeX](https://blog.csdn.net/u012110870/article/details/115511722)。

**Comment by zhangyixing3** [comment]
python -m jcvi.compara.catalog ortholog xihulu tiangua --no_strip_names
这步报latex was not able to process the following string，报错的原因可能是因为缺少 LaTeX。你可以在运行命令时添加 `--notex` 参数，或者在服务器上安装 LaTeX。
普通用户在服务器上安装 LaTeX，可以参考这篇文章：[如何在不使用 root 权限下安装 LaTeX](https://blog.csdn.net/u012110870/article/details/115511722)。

python -m jcvi.graphics.karyotype seqids layout
这步报错，是因为你的 layou文件错误
```
# y, xstart, xend, rotation, color, label, va, bed
.6, .1, .8, 0, , xihulu, top, xihulu.bed, center
.4, .1, .8, 0, , tiangua, top, tiangua.bed, center

 # edges
e, 0, 1, xihulu.tiangua.anchors.simple
```
改成
```
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .1,    .8,       0,      , xihulu, top, xihulu.bed
 .4,     .1,    .8,       0,      , tiangua, top, tiangua.bed
# edges
e, 0, 1, grape.peach.anchors.simple
```

**Comment by lindonghuia** [comment]
# y, xstart, xend, rotation, color, label, va,&nbsp; bed
&nbsp;.6,&nbsp; &nbsp; &nbsp;.1,&nbsp; &nbsp; .8,&nbsp; &nbsp; &nbsp; &nbsp;0,&nbsp; &nbsp; &nbsp; , xihulu, top, xihulu.bed
&nbsp;.4,&nbsp; &nbsp; &nbsp;.1,&nbsp; &nbsp; .8,&nbsp; &nbsp; &nbsp; &nbsp;0,&nbsp; &nbsp; &nbsp; , huanggua, top, huanggua.bed
# edges
e, 0, 1, xihulu.huanggua.anchors.simple

感谢您的回复！latex的安装已经顺利解决，但我使用您给我的格式，仍然出现相同的报错
(jcvi) ***@***.***:/data05/lindonghui/work/06_xihulu/04_mcscan/03_xhl_hg$ python -m jcvi.graphics.karyotype seqids layout
[10/14/24 09:37:45] DEBUG&nbsp; &nbsp; Load file `layout`&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; base.py:36
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; DEBUG&nbsp; &nbsp; Load file `xihulu.bed`&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; base.py:36
[10/14/24 09:37:46] DEBUG&nbsp; &nbsp; Load file `huanggua.bed`&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; base.py:36
Traceback (most recent call last):
&nbsp; File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
&nbsp; &nbsp; return _run_code(code, main_globals, None,
&nbsp; File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 86, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/karyotype.py", line 474, in <module&gt;
&nbsp; &nbsp; main(sys.argv[1:])
&nbsp; File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/karyotype.py", line 454, in main
&nbsp; &nbsp; Karyotype(
&nbsp; File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/karyotype.py", line 365, in __init__
&nbsp; &nbsp; t = layout[i]
IndexError: list index out of range

感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tanghaibao/jcvi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月13日(星期天) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tanghaibao/jcvi] list index out of range (Issue #709)





 
python -m jcvi.compara.catalog ortholog xihulu tiangua --no_strip_names
 这步报latex was not able to process the following string，报错的原因可能是因为缺少 LaTeX。你可以在运行命令时添加 --notex 参数，或者在服务器上安装 LaTeX。
 普通用户在服务器上安装 LaTeX，可以参考这篇文章：如何在不使用 root 权限下安装 LaTeX。
 
python -m jcvi.graphics.karyotype seqids layout
 这步报错，是因为你的 layou文件错误
 # y, xstart, xend, rotation, color, label, va, bed .6, .1, .8, 0, , xihulu, top, xihulu.bed, center .4, .1, .8, 0, , tiangua, top, tiangua.bed, center  # edges e, 0, 1, xihulu.tiangua.anchors.simple  
改成
 # y, xstart, xend, rotation, color, label, va,  bed  .6,     .1,    .8,       0,      , xihulu, top, xihulu.bed  .4,     .1,    .8,       0,      , tiangua, top, tiangua.bed # edges e, 0, 1, grape.peach.anchors.simple

**Comment by yinziiiiii** [comment]
I have the same problem, do you solved the problem？
