### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by lindonghuia** [tanghaibao/jcvi#730]
我在绘制区域共线性时出现了这样的问题
(jcvi) lindonghui@swzx05:/data05/lindonghui/work/06_xihulu/04_mcscan/09_region$ python -m jcvi.graphics.synteny blocks  xihulu_xigua.bed layout
[12/23/24 13:05:02] DEBUG    Load file `xihulu_xigua.bed`                                                                                        base.py:36
                    DEBUG    Load file `blocks`                                                                                                  base.py:36
                    DEBUG    Load file `layout`                                                                                                  base.py:36
Traceback (most recent call last):
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/synteny.py", line 737, in <module>
    main(sys.argv[1:])
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/synteny.py", line 703, in main
    Synteny(
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/graphics/synteny.py", line 465, in __init__
    ext = bf.get_extent(i, order)
  File "/data05/lindonghui/software/mamba/mambaforge/envs/jcvi/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 75, in get_extent
    si, start = min(ocol)
ValueError: min() arg is an empty sequence

一下是我的layout 和block文件
(jcvi) lindonghui@swzx05:/data05/lindonghui/work/06_xihulu/04_mcscan/09_region$ more layout
# x,   y, rotation,   ha,     va,   color, ratio,            label
0.5, 0.6,        0, left, center, ,     1,      xihulu
0.5, 0.4,        0, left, center, ,     1, huanggua
# edges
e, 0, 1

(jcvi) lindonghui@swzx05:/data05/lindonghui/work/06_xihulu/04_mcscan/09_region$ more blocks
evm.model.Chr13.255     ClG42_01g0033100.10
evm.model.Chr13.256     ClG42_01g0033300.10
evm.model.Chr13.257     ClG42_01g0033900.10
evm.model.Chr13.258     ClG42_01g0033900.10
evm.model.Chr13.259     ClG42_01g0034000.10
evm.model.Chr13.260     ClG42_01g0034200.10
evm.model.Chr13.261     ClG42_01g0034800.10
evm.model.Chr13.262     ClG42_01g0035000.10
evm.model.Chr13.263     ClG42_01g0035200.10
evm.model.Chr13.264     ClG42_01g0035300.10
evm.model.Chr13.265     ClG42_01g0035400.10
evm.model.Chr13.266     ClG42_01g0035500.10
evm.model.Chr13.267     ClG42_01g0035600.10
evm.model.Chr13.268     ClG42_01g0035800.10

**Comment by Feeneyli** [comment]
I have the same issue.

**Comment by xxllgg** [comment]
Make sure the BED file you merged keeps the same order as in the blocks file. For example, if your blocks file is between xihulu and huanggua, then the merged BED file must be named xihulu_huanggua.bed, created by: `cat xihulu.bed huanggua.bed > xihulu_huanggua.bed`. I noticed your BED file is named xihulu_xigua.bed, so this might be incorrect.

**Comment by qingxi586** [comment]
同样的问题，会出现ValueError: min() arg is an empty sequence是因为你的block文件中，比如你选了10个基因进行微共线性，但是其中有一个基因组没有一个基因与你所选的参考基因组的10基因具有共线性关系，所以不能绘图成功，因为jcvi不知道这种情况下该绘制多长的染色体，绘制哪个区间的染色体，你只需要扩大你的block文件的选取范围 多选一些基因就可以了
