### ISSUE TITLE
pandas KeyError: 'version'

### ISSUE THREAD

**Issue by lurebgi** [tanghaibao/jcvi#77]
Hi, I got this error all the time to run Mscan

12:21:54 [base] Load file `manakin_gc_z.bed`
12:21:54 [base] Load file `regius_z.bed`
12:21:54 [base] Load file `manakin_gc_z.regius_z.last`
12:21:54 [synteny] A total of 1361 BLAST imported from `manakin_gc_z.regius_z.last`.
12:21:54 [base] Load file `manakin_gc_z.regius_z.anchors`
12:21:54 [synteny] A total of 569 anchors imported.
12:21:54 [synteny] 170 new pairs found.
12:21:54 [synteny] Removed 0 existing anchors.
12:21:54 [synteny] Corrected scores for 9 anchors.
12:21:54 [synteny] Anchors written to `manakin_gc_z.regius_z.lifted.anchors`.
12:21:54 [base] Load file `manakin_gc_z.regius_z.lifted.anchors`
A total of 739 (NR:595) anchors found in 57 clusters.
Stats: Min=4 Max=63 N=57 Mean=12.9649122807 SD=8.99505695111 Median=11.0 Sum=739
NR stats: Min=4 Max=35 N=57 Mean=10.4385964912 SD=5.86101465337 Median=9.0 Sum=595
Traceback (most recent call last):
  File "/home/user/luohao/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/user/luohao/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/compara/catalog.py", line 825, in <module>
    main()
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/compara/catalog.py", line 659, in ortholog
    from jcvi.graphics.dotplot import dotplot_main
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/graphics/dotplot.py", line 33, in <module>
    from jcvi.graphics.base import plt, Rectangle, set_human_axis, savefig, \
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/graphics/base.py", line 287, in <module>
    setup_theme()
  File "/home/user/luohao/lib64/python2.7/site-packages/jcvi/graphics/base.py", line 268, in setup_theme
    import seaborn as sns
  File "/apps/python/lib/python2.7/site-packages/seaborn/__init__.py", line 6, in <module>
    from .rcmod import *
  File "/apps/python/lib/python2.7/site-packages/seaborn/rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params
  File "/apps/python/lib/python2.7/site-packages/seaborn/palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "/apps/python/lib/python2.7/site-packages/seaborn/utils.py", line 8, in <module>
    import pandas as pd
  File "/home/user/luohao/lib/python2.7/site-packages/pandas/__init__.py", line 64, in <module>
    __version__ = v.get('closest-tag',v['version'])
KeyError: 'version'

any clue?

Thank, 
Luohao

**Comment by tanghaibao** [comment]
@lurebgi 

It seems to be a problem with seaborn. Can you try upgrading either seaborn or pandas to the latest version? Something like:

```bash
pip install -U seaborn
```

**Comment by lurebgi** [comment]
Not sure about seaborn. But I asked the system admin to install it into the
system instead of my local environment, it worked.

**Comment by tanghaibao** [comment]
@lurebgi 
Glad it works this time. Closing issue for now.
