### ISSUE TITLE
PDF file for visualisation

### ISSUE THREAD

**Issue by wolverineJT** [tanghaibao/jcvi#79]
Hi. We are getting all results files but no PDF file for visualization. Please can you indicate whats going wrong.
thanks
Jibran

**Comment by tanghaibao** [comment]
@wolverineJT 
Would you please send the command and screen output (or error messages) so that I can reproduce? There are many commands within this package and I don't know which one you refer to. Thanks -

**Comment by wolverineJT** [comment]
Reading liftover chains
Mapping coordinates
^[[0;33m15:02:48 [base]^[[0m^[[0;35m sort -k1,1 -k2,2n -k3,3n -k4,4 PG18.lifted.bed -o PG18.lifted.bed^[[0m
^[[0;33m15:02:48 [base]^[[0m^[[0;35m Load file `PG18.bed`^[[0m
^[[0;33m15:02:48 [allmaps]^[[0m^[[0;35m Map contains 118 markers in 2 linkage groups.^[[0m
^[[0;33m15:02:48 [base]^[[0m^[[0;35m Load file `PG18_scaffolds.fasta.sizes`^[[0m
^[[0;33m15:02:49 [base]^[[0m^[[0;35m Load file `PG18.chr.agp`^[[0m
^[[0;33m15:02:49 [base]^[[0m^[[0;35m Load file `PG18.agp`^[[0m
^[[0;33m15:02:51 [base]^[[0m^[[0;35m Load file `PG18.lifted.bed`^[[0m
^[[0;33m15:02:51 [allmaps]^[[0m^[[0;35m Map contains 0 markers in 0 linkage groups.^[[0m
^[[0;33m15:02:51 [base]^[[0m^[[0;35m Load file `weights.txt`^[[0m
^[[0;33m15:02:51 [base]^[[0m^[[0;35m Imported 2 records from `weights.txt`.^[[0m
Traceback (most recent call last):
  File "/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1525, in path
    "--figsize={0}".format(opts.figsize)])
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1867, in plotall
    plot(xargs + [seqid])
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1699, in plot
    weights = Weights(weightsfile, mapnames)
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 625, in __init__
    pivot_weight, o, pivot = self.get_pivot(mapnames)
  File "/powerplant/workspace/appscratch/miniconda/cfphxd_allmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 646, in get_pivot
    for m, w in self.items() if m in mapnames)
ValueError: max() arg is an empty sequence
