### ISSUE TITLE
MCscan species number

### ISSUE THREAD

**Issue by lurebgi** [tanghaibao/jcvi#80]
Hi, 

When I have more than 8 species to plot the karyotype, it reported

/usr/bin/python -m jcvi.graphics.karyotype seqids.backup layout.backup
13:50:58 [base] Load file `layout.backup`
13:50:58 [base] Load file `medium_ground_finch_z.bed`
13:50:58 [base] Load file `flycatcher_z.bed`
13:50:58 [base] Load file `ground_tit_female_z.bed`
13:50:58 [base] Load file `great_tit_z.bed`
13:50:58 [base] Load file `lycocorax_z.bed`
13:50:58 [base] Load file `rubra_z.bed`
13:50:58 [base] Load file `regius_z.bed`
13:50:58 [base] Load file `hooded_crow_z.bed`
13:50:58 [base] Load file `manakin_gc_pacbio_z.bed`
Traceback (most recent call last):
  File "/apps/python2/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/python2/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/python3/3.6.3:/apps/python2/2.7.14/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 330, in <module>
    main()
  File "/apps/python3/3.6.3:/apps/python2/2.7.14/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 318, in main
    Karyotype(fig, root, seqidsfile, layoutfile)
  File "/apps/python3/3.6.3:/apps/python2/2.7.14/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 269, in __init__
    layout = Layout(layoutfile, generank=generank)
  File "/apps/python3/3.6.3:/apps/python2/2.7.14/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 87, in __init__
    self.assign_colors()
  File "/apps/python3/3.6.3:/apps/python2/2.7.14/lib/python2.7/site-packages/jcvi/graphics/base.py", line 97, in assign_colors
    colorset = sample(colorset, len(self))
  File "/apps/python2/2.7.14/lib/python2.7/random.py", line 325, in sample
    raise ValueError("sample larger than population")
**ValueError: sample larger than population**

Any way to fix that?

Thanks a lot!

Best,
Luohao

**Comment by tanghaibao** [comment]
@lurebgi 
This happens when the species number is greater than palette size (which is 8 colors). I modified the code to allow sampling colors greater than 8 - however some tracks will have the same color. If this is a concern, read the following. Otherwise, the fix should have worked for you already.

There is nothing special about the 8 colors, I picked those because they go nicely together as suggested by colorbrewer.

You could probably add more colors to the palette. The code is here:
https://github.com/tanghaibao/jcvi/blob/master/graphics/base.py#L95

Just write your own colors to how many you want like:
```
colorset = ["red", "black", "tomato", "#00FF00" ...] 
```
