### ISSUE TITLE
Trouble with dotplot

### ISSUE THREAD

**Issue by eltauri** [tanghaibao/jcvi#82]
I can't seem to figure out the issue here

````
23:28:57 [synteny] Assuming --qbed=Ps_ref.bed --sbed=19SMN4.bed
23:28:57 [base] Load file `Ps_ref.bed`
23:28:57 [base] Load file `19SMN4.bed`
23:28:58 [dotplot] xsize=4182 ysize=4469
Traceback (most recent call last):
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 825, in <module>
    main()
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 73, in main
    p.dispatch(globals())
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/compara/catalog.py", line 663, in ortholog
    dotplot_main(dargs)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 357, in dotplot_main
    title=opts.title, stdpf=(not opts.nostdpf))
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 235, in dotplot
    sepcolor=sepcolor, minfont=minfont, stdpf=stdpf)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/graphics/dotplot.py", line 79, in plot_breaks_and_labels
    th = TextHandler(fig)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/graphics/base.py", line 52, in __init__
    self.build_height_array(fig)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/graphics/base.py", line 66, in build_height_array
    w, h = TextHandler.get_text_width_height(fig, size=i)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/jcvi/graphics/base.py", line 58, in get_text_width_height
    tp = mpl.textpath.TextPath((0,0), txt, size=size, usetex=usetex)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/textpath.py", line 445, in __init__
    usetex=usetex)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/textpath.py", line 525, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/textpath.py", line 150, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/textpath.py", line 304, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/dviread.py", line 868, in find_tex_file
    stderr=subprocess.PIPE)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/eltauri/anaconda/envs/python2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
````

**Comment by tanghaibao** [comment]
@eltauri 
Seems to be a problem with some macOS version:
https://stackoverflow.com/questions/34584000/why-does-matplotlib-not-work-on-my-mac-os-x-recently-updated-to-el-capitan

In the post, someone recommended re-installing MacTex. 

Haibao
