### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by AGI-admin** [tanghaibao/jcvi#89]
Hi, I am getting the following error with the test data on Step 2, after installing into a Python 3.5 environment on a RHEL 6.9 machine (installation steps included, skip to end to see error):

```
[root@sma ~]# scl enable rh-python35 bash
[root@sma ~]# pip install biopython numpy deap networkx matplotlib jcvi
...
Requirement already satisfied: numpy in /opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages
...
Requirement already satisfied: matplotlib in /opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages
...
Requirement already satisfied: python-dateutil in /opt/rh/rh-python35/root/usr/lib/python3.5/site-packages (from matplotlib)
Requirement already satisfied: pytz in /opt/rh/rh-python35/root/usr/lib/python3.5/site-packages (from matplotlib)
Requirement already satisfied: cycler in /opt/rh/rh-python35/root/usr/lib/python3.5/site-packages (from matplotlib)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,>=1.5.6 in /opt/rh/rh-python35/root/usr/lib/python3.5/site-packages (from matplotlib)
Requirement already satisfied: six>=1.5 in /opt/rh/rh-python35/root/usr/lib/python3.5/site-packages (from python-dateutil->matplotlib)
...
Successfully installed biopython-1.70 deap-1.2.2 decorator-4.2.1 jcvi-0.7.7 networkx-2.0
[root@sma ~]# cd /tmp
[root@sma tmp]# wget --no-check-certificate https://www.dropbox.com/s/onsjieazu0uytgk/ALLMAPS-install.sh 
...
2018-01-19 13:28:10 (90.7 MB/s) - “ALLMAPS-install.sh” saved [609/609]
[root@sma tmp]# sh ALLMAPS-install.sh 
...
[root@sma tmp]# cp concorde faSize liftOver /usr/local/bin/
[root@sma ~]# exit
logout

> scl enable rh-python35 tcsh
> cd /tmp
> wget https://www.dropbox.com/s/b497bi2b594m6fp/ALLMAPS-testdata.zip
...
> unzip ALLMAPS-testdata.zip 
> cd ALLMAPS-testdata
> python -m jcvi.assembly.allmaps merge JMMale.csv JMFemale.csv -o JM-2.bed
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/jcvi/assembly/allmaps.py", line 753
    print '=' * 10
            ^
SyntaxError: Missing parentheses in call to 'print'
> 

```

**Comment by tanghaibao** [comment]
@AGI-admin 
Unfortunately, only python-2 is currently supported with no py3 support yet.

Haibao

**Comment by AGI-admin** [comment]
Thanks it is working now with Python 2.7.13
