### ISSUE TITLE
KeyError: '910' - what does it mean?

### ISSUE THREAD

**Issue by alslonik** [tanghaibao/jcvi#95]
I am running ALLMAPS and  it runs alright, but suddenly falls with the above error:
```
   627+
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.7-py2.7-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.7-py2.7-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.7-py2.7-linux-x86_64.egg/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.7-py2.7-linux-x86_64.egg/jcvi/assembly/allmaps.py", line 1512, in path
    gaptype="map")
  File "/usr/local/lib/python2.7/dist-packages/jcvi-0.7.7-py2.7-linux-x86_64.egg/jcvi/formats/agp.py", line 671, in order_to_agp
    size = sizes[ctg]
KeyError: '910'
```
What does it mean?

**Comment by alslonik** [comment]
figured it out. my csv file was wrong.
