### ISSUE TITLE
"assembly.allmaps path" error with distance matrix - bad format - on test data

### ISSUE THREAD

**Issue by lplough** [tanghaibao/jcvi#97]
I was just attempting to get the test or example data through the ALLmaps pipeline. 

with code 
`/usr/bin/python2.7 -m jcvi.assembly.allmaps path ./JM-2.bed ./ALLMAPS-testdata/scaffolds.fasta `
I get this error:

`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/Users/louisplough/code/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 1484, in path
    ngen=ngen, npop=npop, cpus=cpus, seed=seed)
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 142, in __init__
    self.prepare_linkage_groups()  # populate all data
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 249, in prepare_linkage_groups
    function=self.function, linkage=self.linkage)
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 92, in __init__
    self.oo[k] = get_rho(physical_to_cm)
  File "/Users/louisplough/code/jcvi/assembly/allmaps.py", line 791, in get_rho
    rho = spearmanr(x, y)
  File "/Users/louisplough/code/jcvi/algorithms/formula.py", line 112, in spearmanr
    return 1 - distancematrix((x, y), dist="s")[1][0]
  File "/Library/Python/2.7/site-packages/Bio/Cluster/__init__.py", line 493, in distancematrix
    _cluster.distancematrix(data, mask, weight, transpose, dist, matrix)
RuntimeError: unexpected format.
`

Has anyone else seen this? If it is a dependency that is not working properly, the error seems cryptic - all dependencies were installed, and appeared to be successful at the time of install...

**Comment by lplough** [comment]
```
$ python -c "import Bio; print(Bio.__version__)"

1.71.dev0

```

I suspected something w/ Biopython but re-running tests showed it was working well...I think 1.71 is the latest?

**Comment by tanghaibao** [comment]
Hmm... this is weird.
Let me know if you see this error again.

Haibao

**Comment by lplough** [comment]
I continue to see it (I ran on my data, the test data, etc). 

I am running on a mac. Ill try my Linux box and let you know -- Im sure it is something very silly. I could show the entire code from that failed command if you like (including the progress until the cluster call failed).

**Comment by lplough** [comment]
It seems to be something with numpy or the biopython installation relying on a flawed numpy install. 
I tried to update both numpy and biopython (really, all python dependencies)  and now I am getting a more consistent but no less difficult to solve  error:

```
~/Downloads/code/ALLMAPS-testdata# /usr/bin/python2.7 -m jcvi.assembly.allmaps path JM-2.bed scaffolds.fasta
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/users/root/Downloads/code/jcvi/assembly/allmaps.py", line 32, in <module>
    from jcvi.graphics.landscape import draw_gauge
  File "/data/users/root/Downloads/code/jcvi/graphics/landscape.py", line 22, in <module>
    from jcvi.graphics.base import plt, Rectangle, CirclePolygon, savefig, \
  File "/data/users/root/Downloads/code/jcvi/graphics/base.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 14, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import
```

What is crazy is thought I had a completely normal build of both biopython and numpy, as they are dependencies for many other programs I run- but I guess not, atleast for numpy. Anyway, the numpy path might be the problem as I have multiple pythons installed (2.7 and 3) so perhaps there is confusion there? Or multiple numpy installs?  
What version of numpy should I have (or should be compatible)?

**Comment by lplough** [comment]
I should say, I have tried to update, uninstall, reinstall, etc numpy using packing tools, from source, etc, and none seem to work - I get various flavors of this error. Outside the scope of your software, but any help woudl be much appreciated...

**Comment by tanghaibao** [comment]
@lplough yes this is a usual headache with python setup. It may be a good idea to set up a virtual environment using [`virtualenv`](https://virtualenv.pypa.io/en/stable/). The issue seems to lie within `numpy` since even `matplotlib` cannot import `numpy`. What happens if you try to directly import `numpy`? 

```bash
python -c "import numpy as np; print(np.__version__)"
```

**Comment by lplough** [comment]
Hmmm. Yes, I've had this headache before. Just to be clear - I am calling python2.7 directly...I assume python 2.X is what the software is tested with? with python3.X i get an immediate print error...

```
python2.7 -c "import numpy as np; print(np.__version__)"
1.14.3
```
Anyway, perhaps the virtual env would be better...

**Comment by lplough** [comment]
was able to run through data in the virtual env. Thanks.
